export const AUDI_DATA = [
  {
    Make: "Audi",
    Model: "100",
    "Start Year": 1989,
    "End Year": 1994,
    Chassis: "C3/C4",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "100 Quattro",
    "Start Year": 1989,
    "End Year": 1994,
    Chassis: "C3/C4",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "200",
    "Start Year": 1989,
    "End Year": 1991,
    Chassis: "C3",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "200 Quattro",
    "Start Year": 1989,
    "End Year": 1991,
    Chassis: "C3",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "4000",
    "Start Year": 1986,
    "End Year": 1987,
    Chassis: "B2",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "No immobilizer in US market",
  },
  {
    Make: "Audi",
    Model: "4000 Quattro",
    "Start Year": 1986,
    "End Year": 1987,
    Chassis: "B2",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "No immobilizer in US market",
  },
  {
    Make: "Audi",
    Model: "5000",
    "Start Year": 1986,
    "End Year": 1988,
    Chassis: "C3",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "No immobilizer in US market",
  },
  {
    Make: "Audi",
    Model: "5000 Quattro",
    "Start Year": 1986,
    "End Year": 1988,
    Chassis: "C3",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "No immobilizer in US market",
  },
  {
    Make: "Audi",
    Model: "80",
    "Start Year": 1988,
    "End Year": 1992,
    Chassis: "B3",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "80 Quattro",
    "Start Year": 1988,
    "End Year": 1992,
    Chassis: "B3",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "90",
    "Start Year": 1988,
    "End Year": 1995,
    Chassis: "B3/B4",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "90 Quattro",
    "Start Year": 1988,
    "End Year": 1995,
    Chassis: "B3/B4",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "A3",
    "Start Year": 2006,
    "End Year": 2013,
    Chassis: "8P",
    "Immobilizer Type": "IMMO III / IMMO IV",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Cluster-based",
  },
  {
    Make: "Audi",
    Model: "A3",
    "Start Year": 2015,
    "End Year": 2020,
    Chassis: "8V",
    "Immobilizer Type": "IMMO IV (MQB)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "Cluster-based. KESSY optional. AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "A3",
    "Start Year": 2022,
    "End Year": 2026,
    Chassis: "8Y",
    "Immobilizer Type": "IMMO IV (MQB Evo)",
    "Key Style": "Flip or Smart (KESSY opt)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "MQB Evo. RH850 cluster. AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "A3 Cabriolet",
    "Start Year": 2015,
    "End Year": 2019,
    Chassis: "8V",
    "Immobilizer Type": "IMMO IV (MQB)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "A3 e-tron",
    "Start Year": 2016,
    "End Year": 2018,
    Chassis: "8V",
    "Immobilizer Type": "IMMO IV (MQB)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "A4",
    "Start Year": 1996,
    "End Year": 1999,
    Chassis: "B5",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "B5 pre-facelift. No IMMO in US",
  },
  {
    Make: "Audi",
    Model: "A4",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "B5",
    "Immobilizer Type": "IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Cluster K-Line",
  },
  {
    Make: "Audi",
    Model: "A4",
    "Start Year": 2002,
    "End Year": 2005,
    Chassis: "B6",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Cluster CAN",
  },
  {
    Make: "Audi",
    Model: "A4",
    "Start Year": 2006,
    "End Year": 2008,
    Chassis: "B7",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "B7",
  },
  {
    Make: "Audi",
    Model: "A4",
    "Start Year": 2009,
    "End Year": 2012,
    Chassis: "B8",
    "Immobilizer Type": "BCM2 A4-type (unlocked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "All CS in BCM2. No sync data. AKL via OBD or bench",
  },
  {
    Make: "Audi",
    Model: "A4",
    "Start Year": 2013,
    "End Year": 2016,
    Chassis: "B8",
    "Immobilizer Type": "BCM2 A4-type (locked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "BCM2 locked but all CS still in BCM2. No sync data",
  },
  {
    Make: "Audi",
    Model: "A4",
    "Start Year": 2017,
    "End Year": 2024,
    Chassis: "B9",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "Order dealer key for AKL",
  },
  {
    Make: "Audi",
    Model: "A4 Avant",
    "Start Year": 1998,
    "End Year": 1999,
    Chassis: "B5",
    "Immobilizer Type": "None / IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "1998-99 None; 2000-01 IMMO II",
  },
  {
    Make: "Audi",
    Model: "A4 Avant",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "B5",
    "Immobilizer Type": "None / IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "1998-99 None; 2000-01 IMMO II",
  },
  {
    Make: "Audi",
    Model: "A4 Avant",
    "Start Year": 2002,
    "End Year": 2005,
    Chassis: "B6",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "B6",
  },
  {
    Make: "Audi",
    Model: "A4 Avant Quattro",
    "Start Year": 1998,
    "End Year": 1999,
    Chassis: "B5",
    "Immobilizer Type": "None / IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "1998-99 None; 2000-01 IMMO II",
  },
  {
    Make: "Audi",
    Model: "A4 Avant Quattro",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "B5",
    "Immobilizer Type": "None / IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "1998-99 None; 2000-01 IMMO II",
  },
  {
    Make: "Audi",
    Model: "A4 Avant Quattro",
    "Start Year": 2002,
    "End Year": 2005,
    Chassis: "B6",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "B6",
  },
  {
    Make: "Audi",
    Model: "A4 Cabriolet",
    "Start Year": 2003,
    "End Year": 2006,
    Chassis: "B6",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "B6",
  },
  {
    Make: "Audi",
    Model: "A4 Cabriolet",
    "Start Year": 2007,
    "End Year": 2009,
    Chassis: "B7",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "B7",
  },
  {
    Make: "Audi",
    Model: "A4 Quattro",
    "Start Year": 1996,
    "End Year": 1999,
    Chassis: "B5",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "B5 pre-facelift",
  },
  {
    Make: "Audi",
    Model: "A4 Quattro",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "B5",
    "Immobilizer Type": "IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "B5 facelift",
  },
  {
    Make: "Audi",
    Model: "A4 Quattro",
    "Start Year": 2002,
    "End Year": 2005,
    Chassis: "B6",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Cluster CAN",
  },
  {
    Make: "Audi",
    Model: "A4 Quattro",
    "Start Year": 2006,
    "End Year": 2008,
    Chassis: "B7",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "B7",
  },
  {
    Make: "Audi",
    Model: "A4 Quattro",
    "Start Year": 2009,
    "End Year": 2012,
    Chassis: "B8",
    "Immobilizer Type": "BCM2 A4-type (unlocked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "All CS in BCM2. No sync data",
  },
  {
    Make: "Audi",
    Model: "A4 Quattro",
    "Start Year": 2013,
    "End Year": 2016,
    Chassis: "B8",
    "Immobilizer Type": "BCM2 A4-type (locked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "BCM2 locked. No sync data needed",
  },
  {
    Make: "Audi",
    Model: "A4 Quattro",
    "Start Year": 2017,
    "End Year": 2024,
    Chassis: "B9",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "A4 allroad",
    "Start Year": 2013,
    "End Year": 2016,
    Chassis: "B8",
    "Immobilizer Type": "BCM2 A4-type (locked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "BCM2 locked. No sync data needed",
  },
  {
    Make: "Audi",
    Model: "A4 allroad",
    "Start Year": 2017,
    "End Year": 2024,
    Chassis: "B9",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "A5",
    "Start Year": 2008,
    "End Year": 2012,
    Chassis: "8T/8F",
    "Immobilizer Type": "BCM2 A4-type (unlocked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "All CS in BCM2. No sync data",
  },
  {
    Make: "Audi",
    Model: "A5",
    "Start Year": 2013,
    "End Year": 2017,
    Chassis: "8T/8F",
    "Immobilizer Type": "BCM2 A4-type (locked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "BCM2 locked. No sync data needed",
  },
  {
    Make: "Audi",
    Model: "A5 (sedan/SB, replaces A4)",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "B10",
    "Immobilizer Type": "IMMO V+ (PPC)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "E3 1.2 electronics",
  },
  {
    Make: "Audi",
    Model: "A5 Cabriolet",
    "Start Year": 2010,
    "End Year": 2012,
    Chassis: "8F",
    "Immobilizer Type": "BCM2 A4-type (unlocked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "All CS in BCM2",
  },
  {
    Make: "Audi",
    Model: "A5 Cabriolet",
    "Start Year": 2013,
    "End Year": 2017,
    Chassis: "8F",
    "Immobilizer Type": "BCM2 A4-type (locked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "BCM2 locked. No sync data needed",
  },
  {
    Make: "Audi",
    Model: "A5 Sportback",
    "Start Year": 2018,
    "End Year": 2024,
    Chassis: "F5",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "A6",
    "Start Year": 1995,
    "End Year": 1997,
    Chassis: "C4",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "C4",
  },
  {
    Make: "Audi",
    Model: "A6",
    "Start Year": 1998,
    "End Year": 1999,
    Chassis: "C5",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Early C5",
  },
  {
    Make: "Audi",
    Model: "A6",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "C5",
    "Immobilizer Type": "IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Cluster K-Line",
  },
  {
    Make: "Audi",
    Model: "A6",
    "Start Year": 2002,
    "End Year": 2004,
    Chassis: "C5",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Cluster CAN",
  },
  {
    Make: "Audi",
    Model: "A6",
    "Start Year": 2005,
    "End Year": 2011,
    Chassis: "C6",
    "Immobilizer Type": "J518 (EZS-KESSY)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66 (EXT cut)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "J518 module. 8E transponder. KESSY optional",
  },
  {
    Make: "Audi",
    Model: "A6",
    "Start Year": 2012,
    "End Year": 2018,
    Chassis: "C7",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "CS NOT in BCM2! Need sync data from 3rd party or pull ECU+TCU+ELV",
  },
  {
    Make: "Audi",
    Model: "A6",
    "Start Year": 2019,
    "End Year": 2024,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "A6",
    "Start Year": 2026,
    "End Year": 2026,
    Chassis: "C8",
    "Immobilizer Type": "IMMO V+ (PPC)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "A6 Avant",
    "Start Year": 1995,
    "End Year": 1997,
    Chassis: "C4",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "C4",
  },
  {
    Make: "Audi",
    Model: "A6 Avant",
    "Start Year": 1999,
    "End Year": 1999,
    Chassis: "C5",
    "Immobilizer Type": "None / IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "1999 None; 2000-01 IMMO II",
  },
  {
    Make: "Audi",
    Model: "A6 Avant",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "C5",
    "Immobilizer Type": "None / IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "1999 None; 2000-01 IMMO II",
  },
  {
    Make: "Audi",
    Model: "A6 Avant",
    "Start Year": 2002,
    "End Year": 2004,
    Chassis: "C5",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "C5",
  },
  {
    Make: "Audi",
    Model: "A6 Avant",
    "Start Year": 2005,
    "End Year": 2005,
    Chassis: "C5",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "C5",
  },
  {
    Make: "Audi",
    Model: "A6 Quattro",
    "Start Year": 1995,
    "End Year": 1997,
    Chassis: "C4",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "C4",
  },
  {
    Make: "Audi",
    Model: "A6 Quattro",
    "Start Year": 1998,
    "End Year": 1999,
    Chassis: "C5",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Early C5",
  },
  {
    Make: "Audi",
    Model: "A6 Quattro",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "C5",
    "Immobilizer Type": "IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "C5",
  },
  {
    Make: "Audi",
    Model: "A6 Quattro",
    "Start Year": 2002,
    "End Year": 2004,
    Chassis: "C5",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "C5",
  },
  {
    Make: "Audi",
    Model: "A6 Quattro",
    "Start Year": 2005,
    "End Year": 2011,
    Chassis: "C6",
    "Immobilizer Type": "J518 (EZS-KESSY)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66 (EXT cut)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "J518 module. KESSY optional",
  },
  {
    Make: "Audi",
    Model: "A6 Quattro",
    "Start Year": 2012,
    "End Year": 2018,
    Chassis: "C7",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "CS NOT in BCM2! Need sync data or pull modules",
  },
  {
    Make: "Audi",
    Model: "A6 Quattro",
    "Start Year": 2019,
    "End Year": 2024,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "A6 allroad",
    "Start Year": 2001,
    "End Year": 2005,
    Chassis: "C5",
    "Immobilizer Type": "IMMO II / IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "2001 IMMO II; 2002+ IMMO III",
  },
  {
    Make: "Audi",
    Model: "A6 allroad",
    "Start Year": 2006,
    "End Year": 2011,
    Chassis: "C6",
    "Immobilizer Type": "J518 (EZS-KESSY)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66 (EXT cut)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "J518 module",
  },
  {
    Make: "Audi",
    Model: "A6 allroad",
    "Start Year": 2013,
    "End Year": 2018,
    Chassis: "C7",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "CS NOT in BCM2! Sync data required",
  },
  {
    Make: "Audi",
    Model: "A6 allroad",
    "Start Year": 2020,
    "End Year": 2024,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "A6 e-tron",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "PPE",
    "Immobilizer Type": "IMMO V+ (PPE)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "A7",
    "Start Year": 2012,
    "End Year": 2018,
    Chassis: "4G8",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Same BCM2 as A6 C7. CS NOT in BCM2! Sync data required",
  },
  {
    Make: "Audi",
    Model: "A7",
    "Start Year": 2019,
    "End Year": 2024,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "A8",
    "Start Year": 1997,
    "End Year": 1999,
    Chassis: "D2",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "D2",
  },
  {
    Make: "Audi",
    Model: "A8",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "D2",
    "Immobilizer Type": "IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "D2",
  },
  {
    Make: "Audi",
    Model: "A8",
    "Start Year": 2002,
    "End Year": 2003,
    Chassis: "D2",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "D2",
  },
  {
    Make: "Audi",
    Model: "A8",
    "Start Year": 2004,
    "End Year": 2010,
    Chassis: "D3",
    "Immobilizer Type": "J518 (KESSY)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66 (EXT cut)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "KESSY standard. 8E transponder",
  },
  {
    Make: "Audi",
    Model: "A8",
    "Start Year": 2011,
    "End Year": 2018,
    Chassis: "D4",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "CS NOT in BCM2! Need sync data. ELV present pre-2012 only",
  },
  {
    Make: "Audi",
    Model: "A8",
    "Start Year": 2019,
    "End Year": 2024,
    Chassis: "D5",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "Slim key style",
  },
  {
    Make: "Audi",
    Model: "A8",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "D5",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "Slim key style",
  },
  {
    Make: "Audi",
    Model: "A8 L",
    "Start Year": 1997,
    "End Year": 1999,
    Chassis: "D2",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "D2",
  },
  {
    Make: "Audi",
    Model: "A8 L",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "D2",
    "Immobilizer Type": "IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "D2",
  },
  {
    Make: "Audi",
    Model: "A8 L",
    "Start Year": 2002,
    "End Year": 2003,
    Chassis: "D2",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "D2",
  },
  {
    Make: "Audi",
    Model: "A8 L",
    "Start Year": 2004,
    "End Year": 2010,
    Chassis: "D3",
    "Immobilizer Type": "J518 (KESSY)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66 (EXT cut)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "KESSY standard",
  },
  {
    Make: "Audi",
    Model: "A8 L",
    "Start Year": 2011,
    "End Year": 2018,
    Chassis: "D4",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "CS NOT in BCM2! Sync data required",
  },
  {
    Make: "Audi",
    Model: "A8 L",
    "Start Year": 2019,
    "End Year": 2024,
    Chassis: "D5",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "A8 L",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "D5",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "Cabriolet",
    "Start Year": 1994,
    "End Year": 1998,
    Chassis: "B4",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "B4 platform",
  },
  {
    Make: "Audi",
    Model: "Coupe GT",
    "Start Year": 1986,
    "End Year": 1987,
    Chassis: "B2/B3",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "No immobilizer in US market",
  },
  {
    Make: "Audi",
    Model: "Coupe Quattro",
    "Start Year": 1986,
    "End Year": 1988,
    Chassis: "B2/B3",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "No immobilizer in US market",
  },
  {
    Make: "Audi",
    Model: "Q3",
    "Start Year": 2015,
    "End Year": 2018,
    Chassis: "8U",
    "Immobilizer Type": "IMMO IV",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Cluster-based. No sync data needed for AKL",
  },
  {
    Make: "Audi",
    Model: "Q3",
    "Start Year": 2019,
    "End Year": 2025,
    Chassis: "F3",
    "Immobilizer Type": "IMMO IV (MQB)",
    "Key Style": "Flip or Smart (KESSY opt)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "MQB A2. AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "Q3",
    "Start Year": 2026,
    "End Year": 2026,
    Chassis: "F3",
    "Immobilizer Type": "IMMO IV (MQB Evo)",
    "Key Style": "Flip or Smart (KESSY opt)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "MQB Evo. AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "Q4 e-tron",
    "Start Year": 2022,
    "End Year": 2026,
    Chassis: "MEB",
    "Immobilizer Type": "IMMO IV (MEB)",
    "Key Style": "Smart Key (MEB)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "MEB electric. Cluster-based. AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "Q4 e-tron Sportback",
    "Start Year": 2022,
    "End Year": 2026,
    Chassis: "MEB",
    "Immobilizer Type": "IMMO IV (MEB)",
    "Key Style": "Smart Key (MEB)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "MEB electric. Cluster-based. AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "Q5",
    "Start Year": 2009,
    "End Year": 2012,
    Chassis: "8R",
    "Immobilizer Type": "BCM2 A4-type (unlocked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "All CS in BCM2. No sync data",
  },
  {
    Make: "Audi",
    Model: "Q5",
    "Start Year": 2013,
    "End Year": 2017,
    Chassis: "8R",
    "Immobilizer Type": "BCM2 A4-type (locked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "BCM2 locked. No sync data needed",
  },
  {
    Make: "Audi",
    Model: "Q5",
    "Start Year": 2018,
    "End Year": 2024,
    Chassis: "FY",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "Q5",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "PPC",
    "Immobilizer Type": "IMMO V+ (PPC)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "Q6 e-tron",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "PPE",
    "Immobilizer Type": "IMMO V+ (PPE)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "Q7",
    "Start Year": 2007,
    "End Year": 2015,
    Chassis: "4L",
    "Immobilizer Type": "J518 (EZS-KESSY)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66 (EXT cut)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "J518 module. Notorious steering lock failures",
  },
  {
    Make: "Audi",
    Model: "Q7",
    "Start Year": 2017,
    "End Year": 2024,
    Chassis: "4M",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "Q7",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "4M",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "Q8",
    "Start Year": 2019,
    "End Year": 2024,
    Chassis: "4M",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "Q8",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "4M",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "Q8 e-tron",
    "Start Year": 2023,
    "End Year": 2025,
    Chassis: "GE",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "GE facelift",
  },
  {
    Make: "Audi",
    Model: "Q8 e-tron Sportback",
    "Start Year": 2023,
    "End Year": 2025,
    Chassis: "GE",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "GE facelift",
  },
  {
    Make: "Audi",
    Model: "Quattro",
    "Start Year": 1986,
    "End Year": 1991,
    Chassis: "B2",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "Ur-Quattro. No immobilizer",
  },
  {
    Make: "Audi",
    Model: "R8 Coupe",
    "Start Year": 2008,
    "End Year": 2015,
    Chassis: "Type 42",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Type 42. Cluster-based. Not BCM2",
  },
  {
    Make: "Audi",
    Model: "R8 Coupe",
    "Start Year": 2017,
    "End Year": 2023,
    Chassis: "Type 4S",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Type 4S. Same BCM2 arch as A6/A7/A8. Sync data required for AKL",
  },
  {
    Make: "Audi",
    Model: "R8 Spyder",
    "Start Year": 2011,
    "End Year": 2015,
    Chassis: "Type 42",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Type 42. Not BCM2",
  },
  {
    Make: "Audi",
    Model: "R8 Spyder",
    "Start Year": 2017,
    "End Year": 2023,
    Chassis: "Type 4S",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Type 4S. Sync data required for AKL",
  },
  {
    Make: "Audi",
    Model: "RS 3",
    "Start Year": 2017,
    "End Year": 2020,
    Chassis: "8V",
    "Immobilizer Type": "IMMO IV (MQB)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "RS 3",
    "Start Year": 2022,
    "End Year": 2026,
    Chassis: "8Y",
    "Immobilizer Type": "IMMO IV (MQB Evo)",
    "Key Style": "Flip or Smart (KESSY opt)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "MQB Evo. AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "RS 4",
    "Start Year": 2007,
    "End Year": 2008,
    Chassis: "B7",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "B7",
  },
  {
    Make: "Audi",
    Model: "RS 5",
    "Start Year": 2013,
    "End Year": 2015,
    Chassis: "8T",
    "Immobilizer Type": "BCM2 A4-type (locked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "BCM2 locked. No sync data needed",
  },
  {
    Make: "Audi",
    Model: "RS 5",
    "Start Year": 2018,
    "End Year": 2024,
    Chassis: "F5",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "RS 5 Sportback",
    "Start Year": 2019,
    "End Year": 2024,
    Chassis: "F5",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "RS 6",
    "Start Year": 2003,
    "End Year": 2004,
    Chassis: "C5",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "Mfg. Restricted",
    Lishi: "HU66",
    Notes: "C5",
  },
  {
    Make: "Audi",
    Model: "RS 6 Avant",
    "Start Year": 2021,
    "End Year": 2024,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "RS 6 Avant",
    "Start Year": 2025,
    "End Year": 2025,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "RS 7",
    "Start Year": 2014,
    "End Year": 2018,
    Chassis: "4G8",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Sync data required",
  },
  {
    Make: "Audi",
    Model: "RS 7",
    "Start Year": 2020,
    "End Year": 2020,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "RS 7",
    "Start Year": 2021,
    "End Year": 2024,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "RS 7",
    "Start Year": 2025,
    "End Year": 2025,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "RS Q8",
    "Start Year": 2020,
    "End Year": 2024,
    Chassis: "4M",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "RS Q8",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "4M",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "RS e-tron GT",
    "Start Year": 2022,
    "End Year": 2026,
    Chassis: "J1",
    "Immobilizer Type": "Porsche J1",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "Porsche style (HU162T)",
    "Code Series": "Contact dealer",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "Taycan platform. NOT BCM2",
  },
  {
    Make: "Audi",
    Model: "S3",
    "Start Year": 2015,
    "End Year": 2020,
    Chassis: "8V",
    "Immobilizer Type": "IMMO IV (MQB)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "S3",
    "Start Year": 2022,
    "End Year": 2026,
    Chassis: "8Y",
    "Immobilizer Type": "IMMO IV (MQB Evo)",
    "Key Style": "Flip or Smart (KESSY opt)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "MQB Evo. AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "S4",
    "Start Year": 2000,
    "End Year": 2002,
    Chassis: "B5",
    "Immobilizer Type": "IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Cluster K-Line",
  },
  {
    Make: "Audi",
    Model: "S4",
    "Start Year": 2004,
    "End Year": 2005,
    Chassis: "B6",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "6001-8100",
    Lishi: "HU66",
    Notes: "B6",
  },
  {
    Make: "Audi",
    Model: "S4",
    "Start Year": 2006,
    "End Year": 2009,
    Chassis: "B7",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "6001-8100",
    Lishi: "HU66",
    Notes: "B7",
  },
  {
    Make: "Audi",
    Model: "S4",
    "Start Year": 2010,
    "End Year": 2012,
    Chassis: "B8",
    "Immobilizer Type": "BCM2 A4-type (unlocked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "All CS in BCM2",
  },
  {
    Make: "Audi",
    Model: "S4",
    "Start Year": 2013,
    "End Year": 2016,
    Chassis: "B8",
    "Immobilizer Type": "BCM2 A4-type (locked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "BCM2 locked. No sync data needed",
  },
  {
    Make: "Audi",
    Model: "S4",
    "Start Year": 2018,
    "End Year": 2024,
    Chassis: "B9",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "S4 (Ur-S4)",
    "Start Year": 1992,
    "End Year": 1994,
    Chassis: "C4",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "C4 platform",
  },
  {
    Make: "Audi",
    Model: "S5",
    "Start Year": 2008,
    "End Year": 2012,
    Chassis: "8T/8F",
    "Immobilizer Type": "BCM2 A4-type (unlocked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "All CS in BCM2",
  },
  {
    Make: "Audi",
    Model: "S5",
    "Start Year": 2013,
    "End Year": 2017,
    Chassis: "8T/8F",
    "Immobilizer Type": "BCM2 A4-type (locked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "BCM2 locked. No sync data needed",
  },
  {
    Make: "Audi",
    Model: "S5",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "B10",
    "Immobilizer Type": "IMMO V+ (PPC)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "S5 Sportback",
    "Start Year": 2018,
    "End Year": 2024,
    Chassis: "F5",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "S6",
    "Start Year": 2001,
    "End Year": 2001,
    Chassis: "C5",
    "Immobilizer Type": "IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "C5",
  },
  {
    Make: "Audi",
    Model: "S6",
    "Start Year": 2002,
    "End Year": 2003,
    Chassis: "C5",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "C5",
  },
  {
    Make: "Audi",
    Model: "S6",
    "Start Year": 2007,
    "End Year": 2011,
    Chassis: "C6",
    "Immobilizer Type": "J518 (EZS-KESSY)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66 (EXT cut)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "J518 module",
  },
  {
    Make: "Audi",
    Model: "S6",
    "Start Year": 2013,
    "End Year": 2018,
    Chassis: "C7",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "CS NOT in BCM2! Sync data required",
  },
  {
    Make: "Audi",
    Model: "S6",
    "Start Year": 2019,
    "End Year": 2024,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "S6 (C4)",
    "Start Year": 1995,
    "End Year": 1997,
    Chassis: "C4",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "C4 platform",
  },
  {
    Make: "Audi",
    Model: "S6 e-tron",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "PPE",
    "Immobilizer Type": "IMMO V+ (PPE)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "S7",
    "Start Year": 2013,
    "End Year": 2018,
    Chassis: "4G8",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "Sync data required",
  },
  {
    Make: "Audi",
    Model: "S7",
    "Start Year": 2019,
    "End Year": 2024,
    Chassis: "C8",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "S8",
    "Start Year": 2001,
    "End Year": 2003,
    Chassis: "D2",
    "Immobilizer Type": "IMMO II / IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "2001 IMMO II; 2002+ IMMO III",
  },
  {
    Make: "Audi",
    Model: "S8",
    "Start Year": 2007,
    "End Year": 2010,
    Chassis: "D3",
    "Immobilizer Type": "J518 (KESSY)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66 (EXT cut)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "KESSY standard",
  },
  {
    Make: "Audi",
    Model: "S8",
    "Start Year": 2013,
    "End Year": 2018,
    Chassis: "D4",
    "Immobilizer Type": "BCM2 A6-type (SYNC DATA)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "CS NOT in BCM2! Sync data required",
  },
  {
    Make: "Audi",
    Model: "S8",
    "Start Year": 2020,
    "End Year": 2024,
    Chassis: "D5",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "SQ5",
    "Start Year": 2014,
    "End Year": 2017,
    Chassis: "8R",
    "Immobilizer Type": "BCM2 A4-type (locked)",
    "Key Style": "Smart Key (round)",
    "AKL Difficulty": "Aftermarket \u2014 BCM2 pull",
    "Key Blank": "HU66 (smart insert)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "BCM2 locked. No sync data needed",
  },
  {
    Make: "Audi",
    Model: "SQ5",
    "Start Year": 2018,
    "End Year": 2024,
    Chassis: "FY",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "SQ5",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "PPC",
    "Immobilizer Type": "IMMO V+ (PPC)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "SQ6 e-tron",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "PPE",
    "Immobilizer Type": "IMMO V+ (PPE)",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "SQ7",
    "Start Year": 2020,
    "End Year": 2024,
    Chassis: "4M",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "SQ7",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "4M",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "SQ8",
    "Start Year": 2020,
    "End Year": 2024,
    Chassis: "4M",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "SQ8",
    "Start Year": 2025,
    "End Year": 2026,
    Chassis: "4M",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
  {
    Make: "Audi",
    Model: "SQ8 e-tron",
    "Start Year": 2023,
    "End Year": 2025,
    Chassis: "GE",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "GE facelift",
  },
  {
    Make: "Audi",
    Model: "SQ8 e-tron Sportback",
    "Start Year": 2023,
    "End Year": 2025,
    Chassis: "GE",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "GE facelift",
  },
  {
    Make: "Audi",
    Model: "TT Coupe",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "8N Mk1",
    "Immobilizer Type": "IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "TT Coupe",
    "Start Year": 2002,
    "End Year": 2006,
    Chassis: "8N Mk1",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "TT Coupe",
    "Start Year": 2008,
    "End Year": 2015,
    Chassis: "8J Mk2",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "TT Coupe",
    "Start Year": 2016,
    "End Year": 2019,
    Chassis: "8S Mk3",
    "Immobilizer Type": "IMMO IV (MQB)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "TT RS",
    "Start Year": 2012,
    "End Year": 2013,
    Chassis: "8J Mk2",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "TT RS",
    "Start Year": 2018,
    "End Year": 2022,
    Chassis: "8S Mk3",
    "Immobilizer Type": "IMMO IV (MQB)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "TT Roadster",
    "Start Year": 2000,
    "End Year": 2001,
    Chassis: "8N Mk1",
    "Immobilizer Type": "IMMO II",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 easy",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "TT Roadster",
    "Start Year": 2002,
    "End Year": 2006,
    Chassis: "8N Mk1",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "TT Roadster",
    "Start Year": 2008,
    "End Year": 2015,
    Chassis: "8J Mk2",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "TT Roadster",
    "Start Year": 2016,
    "End Year": 2019,
    Chassis: "8S Mk3",
    "Immobilizer Type": "IMMO IV (MQB)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "TTS",
    "Start Year": 2009,
    "End Year": 2015,
    Chassis: "8J Mk2",
    "Immobilizer Type": "IMMO III",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "Aftermarket \u2014 standard",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "TTS",
    "Start Year": 2016,
    "End Year": 2019,
    Chassis: "8S Mk3",
    "Immobilizer Type": "IMMO IV (MQB)",
    "Key Style": "Flip/Switchblade",
    "AKL Difficulty": "SYNC DATA NEEDED (AKL)",
    "Key Blank": "HU66",
    "Code Series": "0001-6000",
    Lishi: "HU66",
    Notes:
      "AKL: read IMMO data from cluster (Xhorse MQB adapter) + 3rd party sync data. Add key easy (from working key)",
  },
  {
    Make: "Audi",
    Model: "V8 Quattro",
    "Start Year": 1990,
    "End Year": 1994,
    Chassis: "D1",
    "Immobilizer Type": "None",
    "Key Style": "N/A",
    "AKL Difficulty": "Cut key only",
    "Key Blank": "X139/V35",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
    Notes: "",
  },
  {
    Make: "Audi",
    Model: "e-tron",
    "Start Year": 2019,
    "End Year": 2023,
    Chassis: "GE",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo derived",
  },
  {
    Make: "Audi",
    Model: "e-tron GT",
    "Start Year": 2022,
    "End Year": 2026,
    Chassis: "J1",
    "Immobilizer Type": "Porsche J1",
    "Key Style": "Smart Key (slim)",
    "AKL Difficulty": "Dealer only (PPC/PPE/J1)",
    "Key Blank": "Porsche style (HU162T)",
    "Code Series": "Contact dealer",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "Taycan platform. NOT BCM2",
  },
  {
    Make: "Audi",
    Model: "e-tron Sportback",
    "Start Year": 2020,
    "End Year": 2023,
    Chassis: "GE",
    "Immobilizer Type": "BCM2 (MLB Evo)",
    "Key Style": "Smart Key (wide)",
    "AKL Difficulty": "Dealer key recommended (MLB Evo)",
    "Key Blank": "HU162T (smart insert)",
    "Code Series": "Contact dealer / TBD",
    Lishi: "HU162T(9) / HU162T(10)",
    Notes: "MLB Evo",
  },
];
