export const CDJ_DATA = [
  {
    Make: "Chrysler",
    Model: "LeBaron",
    "Start Year": 1985,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes:
      "Pin tumbler single-sided key. 2-key system: door/ign and trunk/glove.",
  },
  {
    Make: "Chrysler",
    Model: "New Yorker",
    "Start Year": 1985,
    "End Year": 1988,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "Pin tumbler 2-key system. E-body/C-body.",
  },
  {
    Make: "Chrysler",
    Model: "Fifth Avenue",
    "Start Year": 1985,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "M-body. Pin tumbler 2-key system.",
  },
  {
    Make: "Chrysler",
    Model: "Laser",
    "Start Year": 1985,
    "End Year": 1986,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "G-body. Pin tumbler 2-key system.",
  },
  {
    Make: "Dodge",
    Model: "Aries",
    "Start Year": 1985,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "K-car. Pin tumbler 2-key system.",
  },
  {
    Make: "Dodge",
    Model: "600",
    "Start Year": 1985,
    "End Year": 1988,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "G-body. Pin tumbler 2-key system.",
  },
  {
    Make: "Dodge",
    Model: "Lancer",
    "Start Year": 1985,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "H-body. Pin tumbler 2-key system.",
  },
  {
    Make: "Dodge",
    Model: "Omni",
    "Start Year": 1985,
    "End Year": 1990,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "L-body subcompact. Pin tumbler 2-key system.",
  },
  {
    Make: "Dodge",
    Model: "Charger (L-body)",
    "Start Year": 1985,
    "End Year": 1987,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "L-body subcompact. Not to be confused with later LX Charger.",
  },
  {
    Make: "Dodge",
    Model: "Diplomat",
    "Start Year": 1985,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "M-body. Popular police/taxi car. Pin tumbler 2-key system.",
  },
  {
    Make: "Dodge",
    Model: "Daytona",
    "Start Year": 1985,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "G-body sport. Pin tumbler single-sided key. 2-key system.",
  },
  {
    Make: "Dodge",
    Model: "Daytona",
    "Start Year": 1990,
    "End Year": 1992,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "G-body sport. Double-sided wafer. One key does all.",
  },
  {
    Make: "Dodge",
    Model: "Daytona",
    "Start Year": 1993,
    "End Year": 1993,
    "Key Blank": "Y155",
    "Blade/Keyway": "Y155",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "J1-3580",
    Notes: "G-body sport. Y155 bastard key — 1993 only.",
  },
  {
    Make: "Jeep",
    Model: "CJ-7",
    "Start Year": 1985,
    "End Year": 1986,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "AMC/Jeep",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "AMC era Jeep. Pin tumbler.",
  },
  {
    Make: "Jeep",
    Model: "Wrangler YJ",
    "Start Year": 1987,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "YJ Wrangler. Pin tumbler single-sided key.",
  },
  {
    Make: "Jeep",
    Model: "Wrangler YJ",
    "Start Year": 1990,
    "End Year": 1993,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "YJ Wrangler. Double-sided wafer. One key does all.",
  },
  {
    Make: "Jeep",
    Model: "Wrangler YJ",
    "Start Year": 1994,
    "End Year": 1995,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "YJ Wrangler. Y157 double-sided, 7 cuts, 4 depths.",
  },
  {
    Make: "Jeep",
    Model: "Cherokee XJ",
    "Start Year": 1985,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "XJ Cherokee. Pin tumbler single-sided key. 2-key system.",
  },
  {
    Make: "Jeep",
    Model: "Cherokee XJ",
    "Start Year": 1990,
    "End Year": 1993,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "XJ Cherokee. Double-sided wafer. One key does all.",
  },
  {
    Make: "Jeep",
    Model: "Cherokee XJ",
    "Start Year": 1994,
    "End Year": 1996,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "XJ Cherokee. Y157 double-sided, 7 cuts, 4 depths. No immobilizer.",
  },
  {
    Make: "Jeep",
    Model: "Grand Cherokee ZJ",
    "Start Year": 1993,
    "End Year": 1993,
    "Key Blank": "Y155",
    "Blade/Keyway": "Y155",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "J1-3580",
    Notes: "ZJ Grand Cherokee. Y155 bastard key — 1993 only. No immobilizer.",
  },
  {
    Make: "Jeep",
    Model: "Grand Cherokee ZJ",
    "Start Year": 1994,
    "End Year": 1998,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "ZJ Grand Cherokee. Y157, 7 cuts, No immobilizer.",
  },
  {
    Make: "Jeep",
    Model: "Comanche MJ",
    "Start Year": 1985,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "MJ Comanche pickup. Pin tumbler single-sided key.",
  },
  {
    Make: "Jeep",
    Model: "Comanche MJ",
    "Start Year": 1990,
    "End Year": 1992,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "MJ Comanche pickup. Double-sided wafer. One key does all.",
  },
  {
    Make: "Jeep",
    Model: "Wagoneer (XJ-based)",
    "Start Year": 1985,
    "End Year": 1990,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "XJ-based Wagoneer. Pin tumbler.",
  },
  {
    Make: "Jeep",
    Model: "Grand Wagoneer (SJ)",
    "Start Year": 1985,
    "End Year": 1991,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "AMC/Jeep",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "Full-size SJ platform. Final year of the SJ. Pin tumbler.",
  },
  {
    Make: "Chrysler",
    Model: "LeBaron",
    "Start Year": 1990,
    "End Year": 1993,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "LeBaron. Double-sided wafer. One key does all.",
  },
  {
    Make: "Chrysler",
    Model: "LeBaron",
    "Start Year": 1994,
    "End Year": 1995,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "LeBaron. Y157, 7 cuts,",
  },
  {
    Make: "Chrysler",
    Model: "New Yorker / Fifth Ave",
    "Start Year": 1990,
    "End Year": 1993,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "C-body. Double-sided wafer. One key does all.",
  },
  {
    Make: "Chrysler",
    Model: "Imperial",
    "Start Year": 1990,
    "End Year": 1993,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "Y-body. Double-sided wafer.",
  },
  {
    Make: "Chrysler",
    Model: "TC by Maserati",
    "Start Year": 1989,
    "End Year": 1991,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "LeBaron derivative. Double-sided wafer.",
  },
  {
    Make: "Dodge",
    Model: "Shadow",
    "Start Year": 1987,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "P-body Shadow. Pin tumbler single-sided key.",
  },
  {
    Make: "Dodge",
    Model: "Shadow",
    "Start Year": 1990,
    "End Year": 1993,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "P-body Shadow. Double-sided wafer.",
  },
  {
    Make: "Dodge",
    Model: "Shadow",
    "Start Year": 1994,
    "End Year": 1994,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "P-body Shadow. Y157, 7 cuts, Final year.",
  },
  {
    Make: "Dodge",
    Model: "Spirit",
    "Start Year": 1989,
    "End Year": 1992,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "AA-body Spirit. Double-sided wafer.",
  },
  {
    Make: "Dodge",
    Model: "Spirit",
    "Start Year": 1993,
    "End Year": 1993,
    "Key Blank": "Y155",
    "Blade/Keyway": "Y155",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "J1-3580",
    Notes: "AA-body Spirit. Y155 bastard key — 1993 only.",
  },
  {
    Make: "Dodge",
    Model: "Spirit",
    "Start Year": 1994,
    "End Year": 1995,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "AA-body Spirit. Y157, 7 cuts,",
  },
  {
    Make: "Dodge",
    Model: "Dynasty",
    "Start Year": 1988,
    "End Year": 1989,
    "Key Blank": "Y149/Y152/Y153",
    "Blade/Keyway": "Y149/Y152/Y153",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "EP1-3000 / ES1-3000",
    Notes: "C-body Dynasty. Pin tumbler single-sided key.",
  },
  {
    Make: "Dodge",
    Model: "Dynasty",
    "Start Year": 1990,
    "End Year": 1992,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "C-body Dynasty. Double-sided wafer.",
  },
  {
    Make: "Dodge",
    Model: "Dynasty",
    "Start Year": 1993,
    "End Year": 1993,
    "Key Blank": "Y155",
    "Blade/Keyway": "Y155",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "J1-3580",
    Notes: "C-body Dynasty. Y155 bastard key — 1993 only. Final year.",
  },
  {
    Make: "Dodge",
    Model: "Viper",
    "Start Year": 1992,
    "End Year": 1995,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "Double-sided wafer. No immobilizer.",
  },
  {
    Make: "Chrysler",
    Model: "New Yorker (LH)",
    "Start Year": 1994,
    "End Year": 1996,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "LH platform. 7 cuts, 4 depths,",
  },
  {
    Make: "Chrysler",
    Model: "LHS",
    "Start Year": 1994,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "LH platform. 7 cuts,",
  },
  {
    Make: "Chrysler",
    Model: "Concorde",
    "Start Year": 1993,
    "End Year": 1993,
    "Key Blank": "Y155",
    "Blade/Keyway": "Y155",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "J1-3580",
    Notes: "LH Concorde. Y155 bastard key — 1993 only.",
  },
  {
    Make: "Chrysler",
    Model: "Concorde",
    "Start Year": 1994,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "LH Concorde. Y157, 7 cuts, No immobilizer.",
  },
  {
    Make: "Chrysler",
    Model: "Cirrus",
    "Start Year": 1995,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "JA platform. , 7 cuts.",
  },
  {
    Make: "Chrysler",
    Model: "Sebring (JX conv)",
    "Start Year": 1996,
    "End Year": 2000,
    "Key Blank": "Y157 / Y160-PT (98+)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None / 4E (opt 98+)",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key / Transponder (opt)",
    "Immo System": "No Immobilizer (96-97) / SKIM opt (98+)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580 (96-97) / M0001-2618 (98+)",
    Notes:
      "JX platform CDJ convertible. NOT the Mitsubishi coupe. (96-97), (98+).",
  },
  {
    Make: "Chrysler",
    Model: "Town & Country",
    "Start Year": 1991,
    "End Year": 1993,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "AS minivan Town & Country. Double-sided wafer.",
  },
  {
    Make: "Chrysler",
    Model: "Town & Country",
    "Start Year": 1994,
    "End Year": 1995,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "AS minivan Town & Country. Y157, 7 cuts,",
  },
  {
    Make: "Dodge",
    Model: "Intrepid",
    "Start Year": 1993,
    "End Year": 1993,
    "Key Blank": "Y155",
    "Blade/Keyway": "Y155",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "J1-3580",
    Notes: "LH Intrepid. Y155 bastard key — 1993 only.",
  },
  {
    Make: "Dodge",
    Model: "Intrepid",
    "Start Year": 1994,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "LH Intrepid. Y157, 7 cuts, No immobilizer.",
  },
  {
    Make: "Dodge",
    Model: "Neon",
    "Start Year": 1995,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "PL platform. , 7 cuts. No immobilizer.",
  },
  {
    Make: "Dodge",
    Model: "Stratus",
    "Start Year": 1995,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "JA platform. , 7 cuts.",
  },
  {
    Make: "Dodge",
    Model: "Viper",
    "Start Year": 1996,
    "End Year": 2002,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "SR platform. , 7 cuts. No immobilizer.",
  },
  {
    Make: "Dodge",
    Model: "Ram 1500",
    "Start Year": 1994,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "BR/BE platform (2nd gen). , 7 cuts. No immobilizer.",
  },
  {
    Make: "Dodge",
    Model: "Ram 2500/3500",
    "Start Year": 1994,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "BR/BE platform. , 7 cuts.",
  },
  {
    Make: "Dodge",
    Model: "Ram Van/Wagon",
    "Start Year": 1994,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "B-van platform. , 7 cuts.",
  },
  {
    Make: "Dodge",
    Model: "Dakota",
    "Start Year": 1994,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "AN platform (2nd gen). , 7 cuts.",
  },
  {
    Make: "Dodge",
    Model: "Caravan/Grand Caravan",
    "Start Year": 1991,
    "End Year": 1993,
    "Key Blank": "Y154",
    "Blade/Keyway": "Y154",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "G0-1394",
    Notes: "AS minivan. Double-sided wafer.",
  },
  {
    Make: "Dodge",
    Model: "Caravan/Grand Caravan",
    "Start Year": 1994,
    "End Year": 1995,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "AS minivan. Y157, 7 cuts,",
  },
  {
    Make: "Dodge",
    Model: "Caravan/Grand Caravan",
    "Start Year": 1996,
    "End Year": 2000,
    "Key Blank": "Y157 / Y160-PT (98+)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None / 4E (opt 98+)",
    "Transponder Chip": "N/A / 315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Metal Key / Transponder (opt)",
    "Immo System": "No Immobilizer (96-97) / SKIM opt (98+)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580 (96-97) / M0001-2618 (98+)",
    Notes: "NS platform. (96-97), (98+). SKIM optional 98-00.",
  },
  {
    Make: "Chrysler",
    Model: "Town & Country",
    "Start Year": 1996,
    "End Year": 2000,
    "Key Blank": "Y157 / Y160-PT (98+)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None / 4E (opt 98+)",
    "Transponder Chip": "N/A / 315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Metal Key / Transponder (opt)",
    "Immo System": "No Immobilizer (96-97) / SKIM opt (98+)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580 (96-97) / M0001-2618 (98+)",
    Notes: "NS platform. (96-97), (98+). SKIM optional 98-00.",
  },
  {
    Make: "Plymouth",
    Model: "Voyager/Grand Voyager",
    "Start Year": 1996,
    "End Year": 2000,
    "Key Blank": "Y157 / Y160-PT (98+)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None / 4E (opt 98+)",
    "Transponder Chip": "N/A / 315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Metal Key / Transponder (opt)",
    "Immo System": "No Immobilizer (96-97) / SKIM opt (98+)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580 (96-97) / M0001-2618 (98+)",
    Notes: "NS platform. Same as Caravan/T&C. (96-97), (98+).",
  },
  {
    Make: "Jeep",
    Model: "Cherokee XJ",
    "Start Year": 1997,
    "End Year": 2001,
    "Key Blank": "Y157 / Y160-PT (98+)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None (97) / 4E (98+)",
    "Transponder Chip": "N/A / 315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Metal Key / Transponder",
    "Immo System": "No Immobilizer (97) / SKIM (98-01)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580 (97) / M0001-2618 (98-01)",
    Notes: "XJ final years. 97: , no immo. 98-01: , SKIM. OBP w/2 keys.",
  },
  {
    Make: "Jeep",
    Model: "Wrangler TJ",
    "Start Year": 1997,
    "End Year": 2006,
    "Key Blank": "Y157 / Y160-PT (opt)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None (97-00) / 4E (opt 01-06)",
    "Transponder Chip": "N/A / 315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Metal Key / Transponder (opt)",
    "Immo System": "No Immobilizer (97-00) / SKIM opt (01-06)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580 (97) / M0001-2618 (98+)",
    Notes:
      "TJ platform. SKIM very rare on TJ — many owners delete it. All SKIM-equipped TJ used Y160-PT with 4E chip and separate remotes. No Y164/Y165 or RHK on TJ. OHT RHK started with JK (2007+).",
  },
  {
    Make: "Chrysler",
    Model: "Concorde",
    "Start Year": 1998,
    "End Year": 2004,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "LH platform. , 8 cuts. OBP w/2 working keys.",
  },
  {
    Make: "Chrysler",
    Model: "LHS",
    "Start Year": 1998,
    "End Year": 2001,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "LH platform. , 8 cuts. OBP w/2 keys.",
  },
  {
    Make: "Chrysler",
    Model: "300M",
    "Start Year": 1999,
    "End Year": 2004,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "LH platform. , 8 cuts. OBP w/2 keys.",
  },
  {
    Make: "Chrysler",
    Model: "Cirrus",
    "Start Year": 1998,
    "End Year": 2000,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "JA platform. , 8 cuts.",
  },
  {
    Make: "Chrysler",
    Model: "Sebring Sedan",
    "Start Year": 2001,
    "End Year": 2006,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM (opt 01-04 / std 05+)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "JR platform. Not the Mitsubishi coupe.",
  },
  {
    Make: "Chrysler",
    Model: "Sebring Conv",
    "Start Year": 2001,
    "End Year": 2006,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "JR platform CDJ convertible.",
  },
  {
    Make: "Chrysler",
    Model: "Sebring (JS)",
    "Start Year": 2007,
    "End Year": 2010,
    "Key Blank": "Y165-PT / OHT RHK / FOBIK (IYZ-C01C)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "ID46",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "SKIM / WCM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "JS platform. Y165-PT transponder or FOBIK (IYZ-C01C). OHT RHK for RKE models. No smart key option.",
  },
  {
    Make: "Chrysler",
    Model: "200 (1st gen)",
    "Start Year": 2011,
    "End Year": 2014,
    "Key Blank": "FOBIK (IYZ-C01C) / Smart Key (M3N-40821302 opt)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK / Smart Key (opt)",
    "Immo System": "WCM (FOBIK / PEPS opt)",
    Platform: "CDJ",
    Proximity: "Optional",
    "Code Series": "M0001-2618",
    Notes:
      "JS platform. FOBIK standard (IYZ-C01C). Smart key optional upper trims — FCC M3N-40821302, ID46. Tombstone smart key cross-compatible with 300/Charger 11-18 family.",
  },
  {
    Make: "Chrysler",
    Model: "200 (2nd gen)",
    "Start Year": 2015,
    "End Year": 2017,
    "Key Blank": "Smart Key (M3M-40821302)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag AES (4A / NXP AES 128-bit)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "WCM (PEPS)",
    Platform: "CDJ",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "UF platform. Smart key only — FCC M3M-40821302 (M3M not M3N), 4A chip (NXP AES 128-bit). Same FCC ID as 300/Charger/Challenger 2019+. Physical key shape different from 300 tombstone — Chrysler 200-specific smart key.",
  },
  {
    Make: "Chrysler",
    Model: "PT Cruiser",
    "Start Year": 2001,
    "End Year": 2004,
    "Key Blank": "Y160-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "PT platform. 4E transponder. Y160-PT (01-04). OHT remote head key for RKE models. OBP w/2 keys.",
  },
  {
    Make: "Chrysler",
    Model: "PT Cruiser",
    "Start Year": 2005,
    "End Year": 2010,
    "Key Blank": "Y165-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "ID46",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "PT platform. ID46 transponder. Y165-PT (05-10). OHT remote head key for RKE models. OBP w/2 keys.",
  },
  {
    Make: "Chrysler",
    Model: "Town & Country",
    "Start Year": 2001,
    "End Year": 2004,
    "Key Blank": "Y160-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "RS/RG platform. 4E transponder. OHT remote head key for RKE models. OBP w/2 keys. No pin code issues.",
  },
  {
    Make: "Chrysler",
    Model: "Town & Country",
    "Start Year": 2005,
    "End Year": 2007,
    "Key Blank": "Y164-PT / M3N RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "ID46",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "RS/RG platform. ID46 transponder. M3N remote head key. Pin code NOT readable through diag port — must pull from module or obtain from code broker/dealer.",
  },
  {
    Make: "Chrysler",
    Model: "Town & Country",
    "Start Year": 2008,
    "End Year": 2016,
    "Key Blank": "FOBIK (IYZ-C01C / M3N5WY783X w/Keyless Go)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK / FOBIK w/Keyless Go (opt)",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "Optional (Keyless Go)",
    "Code Series": "M0001-2618",
    Notes:
      "RT platform. FOBIK standard (IYZ-C01C). Keyless Go FOBIK optional (M3N5WY783X — push-button pop-out blade). No tombstone smart key. Y170-PT pod key available. ID46. WIN4 module (2011-2015); WIN2 module (2008-2010).",
  },
  {
    Make: "Chrysler",
    Model: "Pacifica (1st gen)",
    "Start Year": 2004,
    "End Year": 2008,
    "Key Blank": "Y164-PT / M3N RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "ID46",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "CS platform. Y164-PT transponder key. Pin code NOT readable through diag port — must pull from module or obtain from code broker/dealer. M3N remote head key.",
  },
  {
    Make: "Chrysler",
    Model: "Pacifica (2nd gen)",
    "Start Year": 2017,
    "End Year": 2025,
    "Key Blank": "Smart Key (Y157 insert)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "AES (Hitag AES)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "WCM (PEPS)",
    Platform: "CDJ",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "RU platform. Smart key standard. Same tombstone family as Charger/Challenger. SGM: behind radio, or passenger side rear door pillar (behind panel at rear of right sliding door opening). Star connector: top right corner behind glovebox.",
  },
  {
    Make: "Chrysler",
    Model: "Aspen",
    "Start Year": 2007,
    "End Year": 2009,
    "Key Blank": "Y165-PT / OHT RHK / FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "SKIM / WCM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "HB platform (same as Durango).",
  },
  {
    Make: "Chrysler",
    Model: "300",
    "Start Year": 2005,
    "End Year": 2010,
    "Key Blank": "Y165-PT / OHT RHK / Y170-PT / FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "SKIM / WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "LX platform. 05-07 transponder, 08+ FOBIK. OBP w/2 keys. WIN4 module (2008-2010).",
  },
  {
    Make: "Chrysler",
    Model: "300",
    "Start Year": 2011,
    "End Year": 2018,
    "Key Blank": "FOBIK (IYZ-C01C) / Smart Key (M3N-40821302)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK / Smart Key (opt)",
    "Immo System": "WCM (FOBIK / PEPS opt)",
    Platform: "CDJ",
    Proximity: "Optional",
    "Code Series": "M0001-2618",
    Notes:
      "LD platform. FOBIK standard (IYZ-C01C). Smart key optional on upper trims — FCC M3N-40821302, ID46 chip. Tombstone smart key cross-compatible with Charger/Challenger. SGM: behind OBD port. Star connector: trunk area behind seat, or under glovebox.",
  },
  {
    Make: "Chrysler",
    Model: "300",
    "Start Year": 2019,
    "End Year": 2023,
    "Key Blank": "Smart Key (M3M-40821302)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag AES (4A)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "WCM (PEPS)",
    Platform: "CDJ",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "LD platform. Smart key standard — FCC M3M-40821302 (note M3M not M3N), 4A chip. Tombstone smart key cross-compatible with Charger/Challenger 19+. SGM: behind OBD port. Star connector: trunk area behind seat, or under glovebox.",
  },
  {
    Make: "Dodge",
    Model: "Neon",
    "Start Year": 1998,
    "End Year": 1999,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "PL platform. , 8 cuts. SKIM introduced 98. OBP w/2 keys.",
  },
  {
    Make: "Dodge",
    Model: "Neon",
    "Start Year": 2000,
    "End Year": 2005,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "PL2 platform. OBP w/2 keys. SRT-4 same key system.",
  },
  {
    Make: "Dodge",
    Model: "Intrepid",
    "Start Year": 1998,
    "End Year": 2004,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "LH platform. OBP w/2 keys.",
  },
  {
    Make: "Dodge",
    Model: "Stratus Sedan",
    "Start Year": 1998,
    "End Year": 2006,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM (opt 98-04 / std 05+)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "JA/JR platform. SKIM optional early, standard later.",
  },
  {
    Make: "Dodge",
    Model: "Durango",
    "Start Year": 1998,
    "End Year": 2003,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM (opt 98-00 / std 01+)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "DN platform. SKIM optional early years.",
  },
  {
    Make: "Dodge",
    Model: "Durango",
    "Start Year": 2004,
    "End Year": 2009,
    "Key Blank": "Y165-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "HB/HG platform. OHT RHK for RKE-equipped models. Some 04-06 models without SKIM but with RKE require model-specific remote key (OHT not compatible).",
  },
  {
    Make: "Dodge",
    Model: "Durango",
    "Start Year": 2011,
    "End Year": 2013,
    "Key Blank": "FOBIK (IYZ-C01C)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "WD platform. FOBIK only (IYZ-C01C). No smart key option. WIN4 module (2010-2013).",
  },
  {
    Make: "Dodge",
    Model: "Durango",
    "Start Year": 2014,
    "End Year": 2025,
    "Key Blank": "Smart Key (M3N-40821302)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "WCM (PEPS)",
    Platform: "CDJ",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "WD platform. Smart key standard — FCC M3N-40821302, ID46. Grand Cherokee/Durango smart key family. SRT/Trackhawk: red key/black key option. SGM: behind glovebox. Star connector: passenger floor near trans tunnel.",
  },
  {
    Make: "Dodge",
    Model: "Dakota",
    "Start Year": 1998,
    "End Year": 2004,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "AN platform. OBP w/2 keys.",
  },
  {
    Make: "Dodge",
    Model: "Dakota",
    "Start Year": 2005,
    "End Year": 2011,
    "Key Blank": "Y165-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "ND platform. OHT RHK for RKE-equipped models. Some 05-06 models without SKIM but with RKE require model-specific remote key (OHT not compatible).",
  },
  {
    Make: "Dodge",
    Model: "Ram 1500",
    "Start Year": 1998,
    "End Year": 2001,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM (optional)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "BR/BE platform. SKIM optional on 98-01. OBP w/2 keys.",
  },
  {
    Make: "Dodge",
    Model: "Ram 1500 (DR)",
    "Start Year": 2002,
    "End Year": 2004,
    "Key Blank": "Y160-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "DR platform (3rd gen). 4E transponder. OHT remote head key for RKE models.",
  },
  {
    Make: "Dodge",
    Model: "Ram 1500 (DR)",
    "Start Year": 2005,
    "End Year": 2008,
    "Key Blank": "Y165-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "ID46",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "DR platform (3rd gen). ID46 transponder. OHT remote head key for RKE models. Potential immo variations 06-08.",
  },
  {
    Make: "Dodge",
    Model: "Ram 2500/3500",
    "Start Year": 1998,
    "End Year": 2002,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM (optional)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "BR/BE HD platform. SKIM optional.",
  },
  {
    Make: "Dodge",
    Model: "Ram 2500/3500 (D1)",
    "Start Year": 2003,
    "End Year": 2004,
    "Key Blank": "Y160-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "D1 platform (3rd gen HD). 4E transponder. OHT remote head key for RKE models.",
  },
  {
    Make: "Dodge",
    Model: "Ram 2500/3500 (D1)",
    "Start Year": 2005,
    "End Year": 2009,
    "Key Blank": "Y165-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "ID46",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "D1 platform (3rd gen HD). ID46 transponder. OHT remote head key for RKE models. Potential immo variations 06-08.",
  },
  {
    Make: "Dodge",
    Model: "Ram Van/Wagon",
    "Start Year": 1998,
    "End Year": 2003,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM (optional)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "B-van platform. SKIM optional.",
  },
  {
    Make: "Dodge",
    Model: "Viper",
    "Start Year": 2003,
    "End Year": 2010,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "ZB/ZB II platform.",
  },
  {
    Make: "Dodge",
    Model: "Viper",
    "Start Year": 2013,
    "End Year": 2017,
    "Key Blank": "FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "VX platform (Gen V). FOBIK system.",
  },
  {
    Make: "Dodge",
    Model: "Magnum",
    "Start Year": 2005,
    "End Year": 2008,
    "Key Blank": "Y165-PT / OHT RHK / FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "SKIM / WCM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "LX platform. 05-07 transponder, 08 FOBIK. WIN4 module (2008-2008).",
  },
  {
    Make: "Dodge",
    Model: "Charger",
    "Start Year": 2006,
    "End Year": 2010,
    "Key Blank": "Y165-PT / OHT RHK / FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "SKIM / WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "LX platform. 06-07 transponder, 08+ FOBIK. WIN4 module (2008-2010).",
  },
  {
    Make: "Dodge",
    Model: "Charger",
    "Start Year": 2011,
    "End Year": 2018,
    "Key Blank": "FOBIK (IYZ-C01C) / Smart Key (M3N-40821302)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK / Smart Key (opt)",
    "Immo System": "WCM (FOBIK / PEPS opt)",
    Platform: "CDJ",
    Proximity: "Optional",
    "Code Series": "M0001-2618",
    Notes:
      "LD platform. FOBIK standard (IYZ-C01C). Smart key optional upper trims — FCC M3N-40821302, ID46. Tombstone smart key cross-compatible with 300/Challenger. SGM: behind OBD port. Star connector: trunk area behind seat, or under glovebox. WIN4 module (2011-2012).",
  },
  {
    Make: "Dodge",
    Model: "Charger",
    "Start Year": 2019,
    "End Year": 2023,
    "Key Blank": "Smart Key (M3M-40821302)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag AES (4A)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "WCM (PEPS)",
    Platform: "CDJ",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "LD platform. Smart key standard — FCC M3M-40821302 (M3M not M3N), 4A chip. Cross-compatible with 300/Challenger 19+. SRT/Hellcat: red key/black key option. SGM: behind OBD port. Star connector: trunk area behind seat, or under glovebox.",
  },
  {
    Make: "Dodge",
    Model: "Challenger",
    "Start Year": 2008,
    "End Year": 2014,
    "Key Blank": "FOBIK (IYZ-C01C)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "LC platform. FOBIK only (IYZ-C01C). No smart key option. SGM: behind radio. Star connector: trunk area behind seat, or under glovebox. WIN4 module (2009-2014).",
  },
  {
    Make: "Dodge",
    Model: "Challenger",
    "Start Year": 2015,
    "End Year": 2018,
    "Key Blank": "FOBIK (IYZ-C01C) / Smart Key (M3N-40821302)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK / Smart Key (opt)",
    "Immo System": "WCM (FOBIK / PEPS opt)",
    Platform: "CDJ",
    Proximity: "Optional",
    "Code Series": "M0001-2618",
    Notes:
      "LC platform. FOBIK standard, smart key optional — FCC M3N-40821302, ID46. SRT/Hellcat: red key/black key option. SGM: behind radio. Star connector: trunk area behind seat, or under glovebox.",
  },
  {
    Make: "Dodge",
    Model: "Challenger",
    "Start Year": 2019,
    "End Year": 2023,
    "Key Blank": "Smart Key (M3M-40821302)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag AES (4A)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "WCM (PEPS)",
    Platform: "CDJ",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "LC platform. Smart key standard — FCC M3M-40821302 (M3M not M3N), 4A chip. SRT/Hellcat/Demon: red key/black key option. SGM: behind radio. Star connector: trunk area behind seat, or under glovebox.",
  },
  {
    Make: "Dodge",
    Model: "Avenger",
    "Start Year": 2008,
    "End Year": 2014,
    "Key Blank": "Y165-PT / OHT RHK / FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "WCM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "JS platform. Potential immo variations 08-12.",
  },
  {
    Make: "Dodge",
    Model: "Caliber",
    "Start Year": 2007,
    "End Year": 2012,
    "Key Blank": "Y165-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "WCM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "PM platform. Transponder key only (no FOBIK). Potential immo variations.",
  },
  {
    Make: "Dodge",
    Model: "Nitro",
    "Start Year": 2007,
    "End Year": 2011,
    "Key Blank": "Y165-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM / WCM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "KA platform.",
  },
  {
    Make: "Dodge",
    Model: "Journey",
    "Start Year": 2009,
    "End Year": 2010,
    "Key Blank": "FOBIK (IYZ-C01C)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "JC platform. FOBIK (IYZ-C01C), ID46. Cross-compatible with IYZ workhorse family. WIN2 module (2008-2010).",
  },
  {
    Make: "Dodge",
    Model: "Journey",
    "Start Year": 2011,
    "End Year": 2020,
    "Key Blank": "Smart Key (M3N-40821302)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "WCM (PEPS)",
    Platform: "CDJ",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "JC platform. Smart key standard — FCC M3N-40821302, ID46. Tombstone smart key. Same smart key as Durango 14+. NOT cross-compatible with 300/Charger/Challenger tombstones (different physical shape, 3-4 btn vs 5 btn).",
  },
  {
    Make: "Dodge",
    Model: "Dart",
    "Start Year": 2013,
    "End Year": 2016,
    "Key Blank": "FOBIK (M3N32297100) / Smart Key (M3N-40821302 opt)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK / Smart Key (opt)",
    "Immo System": "WCM (FOBIK / PEPS opt)",
    Platform: "CDJ (Fiat CUSW chassis)",
    Proximity: "Optional",
    "Code Series": "M0001-2618",
    Notes:
      "PF platform (Fiat Compact). FOBIK (FCC M3N32297100, ID46) for keyed ignition — Dart-specific, NOT cross-compatible with IYZ. Smart key optional (FCC M3N-40821302, ID46) for push-start trims. Smart key cross-compatible with 300/Charger 11-18 tombstone family.",
  },
  {
    Make: "Dodge",
    Model: "Caravan/Grand Caravan",
    "Start Year": 2001,
    "End Year": 2004,
    "Key Blank": "Y160-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "RS/RG platform. 4E transponder. OHT remote head key for RKE models. OBP w/2 keys. No pin code issues.",
  },
  {
    Make: "Dodge",
    Model: "Caravan/Grand Caravan",
    "Start Year": 2005,
    "End Year": 2007,
    "Key Blank": "Y164-PT / M3N RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "ID46",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "RS/RG platform. ID46 transponder. M3N remote head key. Pin code NOT readable through diag port — must pull from module or obtain from code broker/dealer. OBP w/2 keys.",
  },
  {
    Make: "Dodge",
    Model: "Grand Caravan",
    "Start Year": 2008,
    "End Year": 2020,
    "Key Blank": "FOBIK (IYZ-C01C / M3N5WY783X w/Keyless Go)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK / FOBIK w/Keyless Go (opt)",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "Optional (Keyless Go)",
    "Code Series": "M0001-2618",
    Notes:
      "RT platform. FOBIK standard (IYZ-C01C). Keyless Go FOBIK optional (M3N5WY783X — push-button pop-out blade). No tombstone smart key on Grand Caravan. ID46. WIN4 module (2011-2015); WIN2 module (2008-2010).",
  },
  {
    Make: "Ram",
    Model: "1500 DS (4th gen)",
    "Start Year": 2009,
    "End Year": 2012,
    "Key Blank": "FOBIK (IYZ-C01C)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "DS platform (4th gen). FOBIK (IYZ-C01C), ID46. Cross-compatible with IYZ workhorse family. WIN4 module (2009-2012).",
  },
  {
    Make: "Ram",
    Model: "1500 DS (4th gen)",
    "Start Year": 2013,
    "End Year": 2018,
    "Key Blank": "FOBIK (GQ4-53T)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "DS platform (4th gen). FOBIK (GQ4-53T), ID46. Ram-specific — NOT cross-compatible with IYZ-C01C. Also available with FOBIK w/Keyless Go on some trims.",
  },
  {
    Make: "Ram",
    Model: "1500 DS Classic",
    "Start Year": 2019,
    "End Year": 2023,
    "Key Blank": "FOBIK (GQ4-53T)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "Optional",
    "Code Series": "M0001-2618",
    Notes:
      "DS Classic (budget continuation of 4th gen). FOBIK (GQ4-53T), ID46. Ram-specific — NOT cross-compatible with IYZ-C01C.",
  },
  {
    Make: "Ram",
    Model: "1500 DT (5th gen)",
    "Start Year": 2019,
    "End Year": 2024,
    "Key Blank": "Smart Key (Y157 insert)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag AES (ID4A)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "WCM (PEPS)",
    Platform: "CDJ",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "DT platform. Smart key standard. Different smart key from 2500/3500 DT. Different programming from DS. ID46 early, ID4A ~2018+. SGM: behind OBD port. Star connector: under driver dash near headlight switch.",
  },
  {
    Make: "Ram",
    Model: "2500/3500 DT",
    "Start Year": 2019,
    "End Year": 2024,
    "Key Blank": "Smart Key",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 / Hitag AES",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "WCM (PEPS)",
    Platform: "CDJ",
    Proximity: "Optional/Standard",
    "Code Series": "M0001-2618",
    Notes:
      "DT HD platform. Different smart key from 1500 DT. Prox/smart key only, no FOBIK option. Same programming procedures as 1500 DT. SGM: behind instrument cluster. Star connector: under driver dash.",
  },
  {
    Make: "Ram",
    Model: "2500/3500 (D2)",
    "Start Year": 2010,
    "End Year": 2012,
    "Key Blank": "FOBIK (IYZ-C01C)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "D2 platform (4th gen HD). FOBIK (IYZ-C01C), ID46. Cross-compatible with IYZ workhorse family.",
  },
  {
    Make: "Ram",
    Model: "2500/3500 (D2)",
    "Start Year": 2013,
    "End Year": 2018,
    "Key Blank": "FOBIK (GQ4-53T)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "D2 platform (4th gen HD). FOBIK (GQ4-53T), ID46. Ram-specific — NOT cross-compatible with IYZ-C01C.",
  },
  {
    Make: "Ram",
    Model: "4500/5500 CC",
    "Start Year": 2008,
    "End Year": 2012,
    "Key Blank": "Y165-PT / OHT RHK / FOBIK (IYZ-C01C)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "Cab chassis. Y165-PT transponder or FOBIK (IYZ-C01C), ID46. OHT RHK for RKE models.",
  },
  {
    Make: "Ram",
    Model: "4500/5500 CC",
    "Start Year": 2013,
    "End Year": 2024,
    "Key Blank": "FOBIK (GQ4-53T)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "Cab chassis. FOBIK (GQ4-53T), ID46. Ram-specific — NOT cross-compatible with IYZ-C01C.",
  },
  {
    Make: "Ram",
    Model: "1500 (2025+, Stellantis Hi)",
    "Start Year": 2025,
    "End Year": 2025,
    "Key Blank": "Smart Key (new FCC ID)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "AES",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "Stellantis Hi (PEPS)",
    Platform: "Stellantis Hi",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "Stellantis Hi platform. New FCC ID on smart keys (different from DT era). New programming procedures. blade.",
  },
  {
    Make: "Ram",
    Model: "ProMaster",
    "Start Year": 2014,
    "End Year": 2025,
    "Key Blank": "SIP22 flip key / Smart Key",
    "Blade/Keyway": "SIP22",
    "Lishi Tool": "Hitag2 / AES",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "SIP22",
    "Key Type": "Flip Key / Smart Key",
    "Immo System": "Fiat Immo",
    Platform: "Fiat (Ducato)",
    Proximity: "Optional",
    "Code Series": "DE001-11210",
    Notes:
      "Rebadged Fiat Ducato. SIP22 keyway. Fiat immobilizer architecture, NOT CDJ. Flip key or smart key depending on year/trim. SGM: behind OBD port (right side).",
  },
  {
    Make: "Ram",
    Model: "ProMaster City",
    "Start Year": 2015,
    "End Year": 2022,
    "Key Blank": "SIP22 flip key",
    "Blade/Keyway": "SIP22",
    "Lishi Tool": "Hitag2 / AES",
    "Transponder Chip": "315 MHz",
    "FCC ID": "SIP22",
    "Key Type": "Flip Key",
    "Immo System": "Fiat Immo",
    Platform: "Fiat (Doblo)",
    Proximity: "No",
    "Code Series": "DE001-11210",
    Notes:
      "Rebadged Fiat Doblo. SIP22 keyway. Fiat immobilizer. SGM: behind OBD port (right side).",
  },
  {
    Make: "Jeep",
    Model: "Grand Cherokee WJ",
    "Start Year": 1999,
    "End Year": 2004,
    "Key Blank": "Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "WJ platform. OBP w/2 keys.",
  },
  {
    Make: "Jeep",
    Model: "Grand Cherokee WK",
    "Start Year": 2005,
    "End Year": 2010,
    "Key Blank": "Y165-PT / OHT RHK / FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "SKIM / WCM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "WK platform. 05-07 transponder, 08+ FOBIK. WIN4 module (2008-2010).",
  },
  {
    Make: "Jeep",
    Model: "Grand Cherokee WK2",
    "Start Year": 2011,
    "End Year": 2013,
    "Key Blank": "FOBIK (IYZ-C01C) / Keyless Go FOBIK (M3N5WY783X)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK / FOBIK w/Keyless Go (opt)",
    "Immo System": "WCM (FOBIK / Keyless Go FOBIK opt)",
    Platform: "CDJ",
    Proximity: "Optional (Keyless Go)",
    "Code Series": "M0001-2618",
    Notes:
      "WK2 platform. FOBIK standard (IYZ-C01C). Keyless Go FOBIK optional (push-button pop-out, FCC M3N5WY783X) — look for exterior door handle buttons. No tombstone smart key yet. SGM: behind glovebox. Star connector: passenger floor near trans tunnel. WIN4 module (2011-2012).",
  },
  {
    Make: "Jeep",
    Model: "Grand Cherokee WK2",
    "Start Year": 2014,
    "End Year": 2021,
    "Key Blank": "Smart Key (M3N-40821302)",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "WCM (PEPS)",
    Platform: "CDJ",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "WK2 platform. Smart key standard — FCC M3N-40821302, ID46. Grand Cherokee/Durango smart key family. SRT/Trackhawk: red key/black key option. SGM: behind glovebox. Star connector: passenger floor near trans tunnel.",
  },
  {
    Make: "Jeep",
    Model: "Grand Cherokee WL (L)",
    "Start Year": 2021,
    "End Year": 2025,
    "Key Blank": "Smart Key (CY24R insert)",
    "Blade/Keyway": "CY24R (reverse Y157)",
    "Lishi Tool": "AES",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "Stellantis Hi (PEPS)",
    Platform: "Stellantis Hi",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "FIRST Stellantis Hi platform vehicle. WL platform. CY24R emergency key insert (reverse of Y157). Same cutting specs and code series as Y157. New FCC ID. New programming procedures.",
  },
  {
    Make: "Jeep",
    Model: "Grand Cherokee WL (2-row)",
    "Start Year": 2022,
    "End Year": 2025,
    "Key Blank": "Smart Key (CY24R insert)",
    "Blade/Keyway": "CY24R (reverse Y157)",
    "Lishi Tool": "AES",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "Stellantis Hi (PEPS)",
    Platform: "Stellantis Hi",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "WL 2-row replaced WK2. Stellantis Hi platform. CY24R insert. Same system as GC L.",
  },
  {
    Make: "Jeep",
    Model: "Liberty KJ",
    "Start Year": 2002,
    "End Year": 2004,
    "Key Blank": "Y160-PT / OHT RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "4E",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "KJ platform. 4E transponder. OHT remote head key for RKE models. No pin code issues.",
  },
  {
    Make: "Jeep",
    Model: "Liberty KJ",
    "Start Year": 2005,
    "End Year": 2007,
    "Key Blank": "Y164-PT / M3N RHK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "ID46",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder",
    "Immo System": "SKIM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "KJ platform. ID46 transponder. M3N remote head key. Pin code NOT readable through diag port — must pull from module or obtain from code broker/dealer.",
  },
  {
    Make: "Jeep",
    Model: "Liberty KK",
    "Start Year": 2008,
    "End Year": 2012,
    "Key Blank": "FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "KK platform. FOBIK standard.",
  },
  {
    Make: "Jeep",
    Model: "Commander",
    "Start Year": 2006,
    "End Year": 2010,
    "Key Blank": "Y165-PT / OHT RHK / FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "SKIM / WCM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "XK platform. 06-07 transponder, 08+ FOBIK. WIN4 module (2008-2010).",
  },
  {
    Make: "Jeep",
    Model: "Wrangler JK",
    "Start Year": 2007,
    "End Year": 2018,
    "Key Blank": "FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "JK platform. FOBIK standard. No PEPS option. No SGM on 2018 JK.",
  },
  {
    Make: "Jeep",
    Model: "Wrangler JL",
    "Start Year": 2018,
    "End Year": 2025,
    "Key Blank": "SIP22 flip key / Smart Key insert",
    "Blade/Keyway": "SIP22",
    "Lishi Tool": "Hitag2 / AES",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "SIP22",
    "Key Type": "FOBIK (flip) / Smart Key",
    "Immo System": "WCM (FOBIK/PEPS)",
    Platform: "CDJ (Fiat keyway)",
    Proximity: "Optional",
    "Code Series": "DE001-11210",
    Notes:
      "JL platform. SIP22 keyway with flip blade (NOT Y157). Smart key has SIP22 flip-out blade, not an insert. FOBIK also uses SIP22 flip. CDJ WCM immobilizer despite Fiat keyway. SGM: behind OBD port. Star connector: behind glovebox. 12+8: above OBD port.",
  },
  {
    Make: "Jeep",
    Model: "Gladiator",
    "Start Year": 2020,
    "End Year": 2025,
    "Key Blank": "SIP22 flip key / Smart Key insert",
    "Blade/Keyway": "SIP22",
    "Lishi Tool": "Hitag2 / AES",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "SIP22",
    "Key Type": "FOBIK (flip) / Smart Key",
    "Immo System": "WCM (FOBIK/PEPS)",
    Platform: "CDJ (Fiat keyway)",
    Proximity: "Optional",
    "Code Series": "DE001-11210",
    Notes:
      "JT platform (JL-based pickup). SIP22 keyway with flip blade (NOT Y157). Same key system as JL Wrangler. SGM: behind OBD port. Star connector: behind glovebox.",
  },
  {
    Make: "Jeep",
    Model: "Cherokee KL",
    "Start Year": 2014,
    "End Year": 2023,
    "Key Blank": "FOBIK / Smart Key",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 / AES",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK / Smart Key",
    "Immo System": "WCM (FOBIK/PEPS)",
    Platform: "CDJ",
    Proximity: "Optional/Standard",
    "Code Series": "M0001-2618",
    Notes:
      "KL platform. 54T FOBIK — NOT cross-compatible with IYZ FOBIK. Cherokee-specific smart key. Same restriction as Dart and Ram DS post-2014. SGM: behind radio. Star connector: under/behind glovebox.",
  },
  {
    Make: "Jeep",
    Model: "Patriot",
    "Start Year": 2007,
    "End Year": 2017,
    "Key Blank": "Y165-PT / OHT RHK / FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "WCM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "MK platform. Transponder or FOBIK depending on year/trim.",
  },
  {
    Make: "Jeep",
    Model: "Compass (1st gen)",
    "Start Year": 2007,
    "End Year": 2017,
    "Key Blank": "Y165-PT / OHT RHK / FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Transponder / FOBIK",
    "Immo System": "WCM",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes: "MK platform. Same as Patriot.",
  },
  {
    Make: "Jeep",
    Model: "Wagoneer",
    "Start Year": 2022,
    "End Year": 2025,
    "Key Blank": "Smart Key (CY24R insert)",
    "Blade/Keyway": "CY24R (reverse Y157)",
    "Lishi Tool": "AES",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "Stellantis Hi (PEPS)",
    Platform: "Stellantis Hi",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "WS platform. Stellantis Hi. CY24R emergency insert. Same system as Grand Cherokee L.",
  },
  {
    Make: "Jeep",
    Model: "Grand Wagoneer",
    "Start Year": 2022,
    "End Year": 2025,
    "Key Blank": "Smart Key (CY24R insert)",
    "Blade/Keyway": "CY24R (reverse Y157)",
    "Lishi Tool": "AES",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "Stellantis Hi (PEPS)",
    Platform: "Stellantis Hi",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "WS platform. Stellantis Hi. CY24R emergency insert. Premium trim of Wagoneer.",
  },
  {
    Make: "Jeep",
    Model: "Renegade",
    "Start Year": 2015,
    "End Year": 2025,
    "Key Blank": "SIP22 flip key / Smart Key insert",
    "Blade/Keyway": "SIP22",
    "Lishi Tool": "Hitag2 / AES",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "SIP22",
    "Key Type": "Flip Key / Smart Key",
    "Immo System": "Fiat Immo",
    Platform: "Fiat (500X)",
    Proximity: "Optional",
    "Code Series": "DE001-11210",
    Notes:
      "Rebadged Fiat 500X platform. SIP22 keyway. Fiat immobilizer architecture. Flip key or PEPS depending on trim. Cross-compatibility issues — Renegade/Compass smart keys are their own family with limited cross-compatibility. SGM: behind OBD (18), behind radio (19+), or behind instrument cluster (PHEV). ADC-2012 RFH headliner cable also works.",
  },
  {
    Make: "Jeep",
    Model: "Compass (2nd gen)",
    "Start Year": 2017,
    "End Year": 2025,
    "Key Blank": "SIP22 flip key / Smart Key insert",
    "Blade/Keyway": "SIP22",
    "Lishi Tool": "Hitag2 / AES",
    "Transponder Chip": "315/433 MHz",
    "FCC ID": "SIP22",
    "Key Type": "Flip Key / Smart Key",
    "Immo System": "Fiat Immo",
    Platform: "Fiat (500X)",
    Proximity: "Optional",
    "Code Series": "DE001-11210",
    Notes:
      "Fiat Small Wide platform. SIP22 keyway. Fiat immo. Same platform as Renegade. Smart key is Renegade/Compass family — not cross-compatible with CDJ tombstone keys. SGM: behind instrument cluster. ADC-2012 RFH headliner cable also works.",
  },
  {
    Make: "Chrysler",
    Model: "Voyager (2020+)",
    "Start Year": 2020,
    "End Year": 2023,
    "Key Blank": "FOBIK",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "Hitag2 / AES",
    "Transponder Chip": "315 MHz",
    "FCC ID": "CY24",
    "Key Type": "FOBIK",
    "Immo System": "WCM (FOBIK)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "M0001-2618",
    Notes:
      "Budget rebadge of Pacifica. CDJ FOBIK. Not Fiat-based. SGM: behind radio.",
  },
  {
    Make: "Chrysler",
    Model: "Sebring Coupe",
    "Start Year": 1995,
    "End Year": 2000,
    "Key Blank": "MIT11-PT",
    "Blade/Keyway": "MIT6 (MIT11)",
    "Lishi Tool": "Philips Crypto (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "MIT11",
    "Key Type": "Transponder",
    "Immo System": "Mitsubishi ETACS",
    Platform: "Mitsubishi (Diamond Star)",
    Proximity: "No",
    "Code Series": "F",
    Notes:
      "Rebadged Mitsubishi Eclipse. F code series (F0001-F1571). Mitsubishi immobilizer, NOT CDJ SKIM. Requires Mitsubishi programming procedures.",
  },
  {
    Make: "Chrysler",
    Model: "Sebring Coupe",
    "Start Year": 2001,
    "End Year": 2005,
    "Key Blank": "MIT11-PT",
    "Blade/Keyway": "MIT6 (MIT11)",
    "Lishi Tool": "Philips Crypto (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "MIT11",
    "Key Type": "Transponder",
    "Immo System": "Mitsubishi ETACS",
    Platform: "Mitsubishi (Diamond Star)",
    Proximity: "No",
    "Code Series": "F",
    Notes: "Continuation. F code series. Mitsubishi immo.",
  },
  {
    Make: "Dodge",
    Model: "Stratus Coupe",
    "Start Year": 2001,
    "End Year": 2005,
    "Key Blank": "MIT11-PT",
    "Blade/Keyway": "MIT6 (MIT11)",
    "Lishi Tool": "Philips Crypto (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "MIT11",
    "Key Type": "Transponder",
    "Immo System": "Mitsubishi ETACS",
    Platform: "Mitsubishi (Diamond Star)",
    Proximity: "No",
    "Code Series": "F",
    Notes:
      "Rebadged Mitsubishi Eclipse. F code series. Same as Chrysler Sebring Coupe. Mitsubishi immo.",
  },
  {
    Make: "Chrysler",
    Model: "Sebring Convertible",
    "Start Year": 1996,
    "End Year": 2000,
    "Key Blank": "MIT11-PT",
    "Blade/Keyway": "MIT6 (MIT11)",
    "Lishi Tool": "Philips Crypto (ID46)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "MIT11",
    "Key Type": "Transponder",
    "Immo System": "Mitsubishi ETACS",
    Platform: "Mitsubishi (Diamond Star)",
    Proximity: "No",
    "Code Series": "F",
    Notes:
      "Late 90s Mitsubishi-platform convertible. F code series. Do NOT treat as CDJ.",
  },
  {
    Make: "Dodge",
    Model: "Avenger (1st gen)",
    "Start Year": 1995,
    "End Year": 2000,
    "Key Blank": "X245",
    "Blade/Keyway": "MIT4 (X245)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "MIT11",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "Mitsubishi (Diamond Star)",
    Proximity: "No",
    "Code Series": "F",
    Notes:
      "Diamond Star coupe. MIT4/X245 keyway (NOT CDJ). No immobilizer. Most are off the road. Not a common call.",
  },
  {
    Make: "Chrysler",
    Model: "Crossfire",
    "Start Year": 2004,
    "End Year": 2008,
    "Key Blank": "HU64 / Mercedes blank",
    "Blade/Keyway": "HU64",
    "Lishi Tool": "Mercedes IR/Crypto",
    "Transponder Chip": "315 MHz",
    "FCC ID": "HU64",
    "Key Type": "Transponder (Mercedes flip key)",
    "Immo System": "Mercedes EIS/ESL",
    Platform: "Mercedes (R170 SLK)",
    Proximity: "No",
    "Code Series": "0001-6400",
    Notes:
      "Rebadged Mercedes SLK (R170). HU64 keyway. Mercedes EIS immobilizer. Mercedes programming required (NOT CDJ). Mercedes code series.",
  },
  {
    Make: "Dodge",
    Model: "Sprinter (1st gen)",
    "Start Year": 2003,
    "End Year": 2006,
    "Key Blank": "S32YS / YM15 flip key",
    "Blade/Keyway": "YM15",
    "Lishi Tool": "Mercedes IR/Crypto",
    "Transponder Chip": "315 MHz",
    "FCC ID": "HU64",
    "Key Type": "Transponder (Mercedes flip key)",
    "Immo System": "Mercedes EIS",
    Platform: "Mercedes (T1N)",
    Proximity: "No",
    "Code Series": "HM6001-7110",
    Notes:
      "T1N Sprinter. HU64 keyway. Mercedes EIS immobilizer. H (HM6001-HM7000). Sold as Dodge 03-06.",
  },
  {
    Make: "Dodge/Freightliner",
    Model: "Sprinter (2nd gen)",
    "Start Year": 2007,
    "End Year": 2009,
    "Key Blank": "HU64 flip key",
    "Blade/Keyway": "HU64",
    "Lishi Tool": "Mercedes IR/Crypto",
    "Transponder Chip": "315 MHz",
    "FCC ID": "HU64",
    "Key Type": "Transponder (Mercedes flip key)",
    "Immo System": "Mercedes EIS",
    Platform: "Mercedes (NCV3)",
    Proximity: "No",
    "Code Series": "0001-6400",
    Notes:
      "NCV3 Sprinter. HU64 high security. Mercedes EIS. Code series 1003501-1006700. Sold as Dodge 07-09.",
  },
  {
    Make: "Dodge",
    Model: "Sprinter (3rd gen)",
    "Start Year": 2010,
    "End Year": 2018,
    "Key Blank": "HU64 flip key / Smart Key",
    "Blade/Keyway": "HU64",
    "Lishi Tool": "HU64",
    "Transponder Chip": "315 MHz",
    "FCC ID": "HU64",
    "Key Type": "Flip Key / Smart Key",
    "Immo System": "Mercedes EIS/EZS",
    Platform: "Mercedes (NCV3/VS30)",
    Proximity: "Optional",
    "Code Series": "0001-6400",
    Notes:
      "Continued NCV3 then VS30 platform. Mercedes immo. Branded as Ram, Freightliner, or Mercedes depending on year. HU64 keyway throughout.",
  },

  {
    Make: "Dodge",
    Model: "Hornet",
    "Start Year": 2023,
    "End Year": 2025,
    "Key Blank": "SIP22 smart key insert",
    "Blade/Keyway": "SIP22",
    "Lishi Tool": "AES",
    "Transponder Chip": "433 MHz",
    "FCC ID": "SIP22",
    "Key Type": "Smart Key",
    "Immo System": "Alfa Romeo Immo",
    Platform: "Alfa Romeo (Tonale)",
    Proximity: "Yes",
    "Code Series": "DE001-11210",
    Notes:
      "Rebadged Alfa Romeo Tonale. SIP22 keyway. Alfa Romeo immobilizer architecture. NOT CDJ programming — requires Alfa/FCA procedures.",
  },
  {
    Make: "Plymouth",
    Model: "Prowler",
    "Start Year": 1997,
    "End Year": 2002,
    "Key Blank": "Y157 / Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None (97) / 4E (99+)",
    "Transponder Chip": "N/A / 315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Metal Key / Transponder",
    "Immo System": "No Immobilizer (97) / SKIM (99-02)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580 (97) / M0001-2618 (99+)",
    Notes: "PR platform. 97: , no immo. 99-02 (sold as Chrysler): , SKIM.",
  },
  {
    Make: "Plymouth",
    Model: "Neon",
    "Start Year": 1995,
    "End Year": 2001,
    "Key Blank": "Y157 / Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None (95-97) / 4E (98+)",
    "Transponder Chip": "N/A / 315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Metal Key / Transponder",
    "Immo System": "No Immobilizer (95-97) / SKIM (98+)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580 (95-97) / M0001-2618 (98+)",
    Notes: "Same as Dodge Neon. (95-97), (98+).",
  },
  {
    Make: "Plymouth",
    Model: "Breeze",
    "Start Year": 1996,
    "End Year": 2000,
    "Key Blank": "Y157 / Y160-PT",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None (96-97) / 4E (98+)",
    "Transponder Chip": "N/A / 315 MHz",
    "FCC ID": "CY24",
    "Key Type": "Metal Key / Transponder",
    "Immo System": "No Immobilizer (96-97) / SKIM (98+)",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580 (96-97) / M0001-2618 (98+)",
    Notes: "JA platform. Same as Cirrus/Stratus. (96-97), (98+).",
  },
  {
    Make: "Eagle",
    Model: "Talon",
    "Start Year": 1990,
    "End Year": 1998,
    "Key Blank": "MIT11 / MIT11-PT",
    "Blade/Keyway": "MIT6 (MIT11)",
    "Lishi Tool": "None (90-94) / Philips Crypto (95+)",
    "Transponder Chip": "315 MHz",
    "FCC ID": "MIT11",
    "Key Type": "Metal Key / Transponder",
    "Immo System": "Mitsubishi ETACS (95+)",
    Platform: "Mitsubishi (Diamond Star)",
    Proximity: "No",
    "Code Series": "F",
    Notes:
      "Diamond Star Motors. Mitsubishi platform. F code series (w/transponder). Same as Eclipse/Talon/Laser.",
  },
  {
    Make: "Eagle",
    Model: "Vision",
    "Start Year": 1993,
    "End Year": 1993,
    "Key Blank": "Y155",
    "Blade/Keyway": "Y155",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "N/A",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "J1-3580",
    Notes:
      "LH Vision. Y155 bastard key — 1993 only. Same as Intrepid/Concorde.",
  },
  {
    Make: "Eagle",
    Model: "Vision",
    "Start Year": 1994,
    "End Year": 1997,
    "Key Blank": "Y157",
    "Blade/Keyway": "Y157 (CY24)",
    "Lishi Tool": "None",
    "Transponder Chip": "N/A",
    "FCC ID": "CY24",
    "Key Type": "Metal Key",
    "Immo System": "No Immobilizer",
    Platform: "CDJ",
    Proximity: "No",
    "Code Series": "L1-3580",
    Notes: "LH Vision. Y157, 7 cuts, Same as Intrepid/Concorde.",
  },
  {
    Make: "Eagle",
    Model: "Summit",
    "Start Year": 1989,
    "End Year": 1996,
    "Key Blank": "MIT11",
    "Blade/Keyway": "MIT6 (MIT11)",
    "Lishi Tool": "None / Philips Crypto (opt)",
    "Transponder Chip": "N/A",
    "FCC ID": "MIT11",
    "Key Type": "Metal Key / Transponder (opt)",
    "Immo System": "Mitsubishi ETACS (opt)",
    Platform: "Mitsubishi",
    Proximity: "No",
    "Code Series": "F",
    Notes: "Rebadged Mitsubishi Mirage. Mitsubishi platform.",
  },
  {
    Make: "Jeep",
    Model: "Compass (Stellantis)",
    "Start Year": 2025,
    "End Year": 2025,
    "Key Blank": "Smart Key (CY24R insert)",
    "Blade/Keyway": "CY24R (reverse Y157)",
    "Lishi Tool": "AES",
    "Transponder Chip": "433 MHz",
    "FCC ID": "CY24",
    "Key Type": "Smart Key",
    "Immo System": "Stellantis Hi (PEPS)",
    Platform: "Stellantis Hi",
    Proximity: "Yes",
    "Code Series": "M0001-2618",
    Notes:
      "New generation Compass on Stellantis STLA Medium platform. CY24R insert. No longer Fiat 500X based.",
  },
];
