export const FORD_DATA = [
  {
    Make: "Ford",
    Model: "Aerostar",
    Platform: "Aerostar",
    "Start Year": 1986,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / FA/FB",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Aspire",
    Platform: "Aspire",
    "Start Year": 1994,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "B1001-B6200",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; no transponder",
  },
  {
    Make: "Ford",
    Model: "Bronco",
    Platform: "T1/P",
    "Start Year": 1985,
    "End Year": 1996,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / FA/FB",
    "PATS Type": null,
    "Keypad Location": null,
    Notes:
      "No PATS. 1996 is split year: may have old 10-cut (H54/H67) or new 8-cut (H75) system. Last year of production.",
  },
  {
    Make: "Ford",
    Model: "Bronco",
    Platform: "T6",
    "Start Year": 2021,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel (if equipped)",
    Notes: "ILCO shows keyed at 1-4000; prox at 30001-31544; center-mill",
  },
  {
    Make: "Ford",
    Model: "Bronco II",
    Platform: "Ranger",
    "Start Year": 1985,
    "End Year": 1990,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / FA",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Bronco Sport",
    Platform: "C2",
    "Start Year": 2021,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "20001-31544",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel (if equipped)",
    Notes: "Philips 46; high security",
  },
  {
    Make: "Ford",
    Model: "C-Max",
    Platform: "C2",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500 (keyed); 11501-13000 (prox)",
    "PATS Type": "BCM; RFA/KVM",
    "Keypad Location": null,
    Notes: null,
  },
  {
    Make: "Ford",
    Model: "C-Max",
    Platform: "C2",
    "Start Year": 2014,
    "End Year": 2018,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500 (keyed); 11501-13000 (prox)",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": null,
    Notes: null,
  },
  {
    Make: "Ford",
    Model: "Contour",
    Platform: "CDW27",
    "Start Year": 1995,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-B-C-D-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; ILCO lists H78 for non-V6, H71 for 1995",
  },
  {
    Make: "Ford",
    Model: "Contour (4-Cyl)",
    Platform: "CDW27",
    "Start Year": 1998,
    "End Year": 2000,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "A-B-C-D-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; ILCO lists as H78",
  },
  {
    Make: "Ford",
    Model: "Contour (V6)",
    Platform: "CDW27",
    "Start Year": 1998,
    "End Year": 2000,
    "Ignition Type": "Keyed",
    "Key Blank": "H73-PT",
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-B-C-D-E",
    "PATS Type": "Standalone PATS / PCM",
    "Keypad Location": null,
    Notes: "10-cut; PATS 4C chip",
  },
  {
    Make: "Ford",
    Model: "Crown Victoria",
    Platform: "Panther",
    "Start Year": 1985,
    "End Year": 1991,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / FA/FB",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; double-sided; LTD CV through 1991",
  },
  {
    Make: "Ford",
    Model: "Crown Victoria",
    Platform: "Panther",
    "Start Year": 1992,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / 1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; H75 from 1997",
  },
  {
    Make: "Ford",
    Model: "Crown Victoria",
    Platform: "Panther",
    "Start Year": 1998,
    "End Year": 2002,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": null,
    Notes: "4C chip",
  },
  {
    Make: "Ford",
    Model: "Crown Victoria",
    Platform: "Panther",
    "Start Year": 2003,
    "End Year": 2011,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip; RHK available from ~2005+",
  },
  {
    Make: "Ford",
    Model: "E-Series Vans",
    Platform: "E-Series",
    "Start Year": 1985,
    "End Year": 1995,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "FA/FB / A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS. No transponder.",
  },
  {
    Make: "Ford",
    Model: "E-Series Vans",
    Platform: "E-Series",
    "Start Year": 1996,
    "End Year": 2014,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes:
      "No PATS. No transponder. Plain metal key. 1996 split year (old 10-cut or new 8-cut). Passenger/cargo vans discontinued after 2014.",
  },
  {
    Make: "Ford",
    Model: "E-Series Vans",
    Platform: "E-Series",
    "Start Year": 2015,
    "End Year": 2025,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes:
      'No PATS. No transponder. Plain metal key. Cutaway/stripped chassis only (E-350/E-450). No 2020 "Model" year (skipped).',
  },
  {
    Make: "Ford",
    Model: "EXP",
    Platform: "Escort",
    "Start Year": 1985,
    "End Year": 1988,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "EcoSport",
    Platform: "B3",
    "Start Year": 2018,
    "End Year": 2020,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "1-4000",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": null,
    Notes: "Philips 46",
  },
  {
    Make: "Ford",
    Model: "EcoSport",
    Platform: "B3",
    "Start Year": 2021,
    "End Year": 2022,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "1-4000",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": null,
    Notes: "Philips 46",
  },
  {
    Make: "Ford",
    Model: "Edge",
    Platform: "CD3",
    "Start Year": 2007,
    "End Year": 2010,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster (ICM)",
    "Keypad Location": "SJB; driver's side under dash",
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Edge",
    Platform: "CD3",
    "Start Year": 2011,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM; RFA/KVM",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "Edge",
    Platform: "CD3",
    "Start Year": 2014,
    "End Year": 2014,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "Edge",
    Platform: "CD4",
    "Start Year": 2015,
    "End Year": 2015,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "1-4000",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Philips 46; high security",
  },
  {
    Make: "Ford",
    Model: "Edge",
    Platform: "CD4",
    "Start Year": 2016,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "1-4000",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Philips 46; high security",
  },
  {
    Make: "Ford",
    Model: "Edge",
    Platform: "CD4",
    "Start Year": 2017,
    "End Year": 2017,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "1-4000",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Philips 46; high security",
  },
  {
    Make: "Ford",
    Model: "Edge",
    Platform: "CD4",
    "Start Year": 2018,
    "End Year": 2024,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "1-4000",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Philips 46; high security",
  },
  {
    Make: "Ford",
    Model: "Escape",
    Platform: "C1",
    "Start Year": 2001,
    "End Year": 2004,
    "Ignition Type": "Keyed",
    "Key Blank": "H86-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": "RAP module; behind driver's dash",
    Notes: "4D60 chip",
  },
  {
    Make: "Ford",
    Model: "Escape",
    Platform: "C1",
    "Start Year": 2005,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / ICM",
    "Keypad Location": "RAP module; behind driver's dash",
    Notes: "4D63 chip; includes Hybrid",
  },
  {
    Make: "Ford",
    Model: "Escape",
    Platform: "C1",
    "Start Year": 2008,
    "End Year": 2012,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / ICM",
    "Keypad Location": "SJB/BCM; passenger side under glove box",
    Notes: "4D63 chip; includes Hybrid",
  },
  {
    Make: "Ford",
    Model: "Escape",
    Platform: "C2",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500 (keyed); 11501-13000 (prox)",
    "PATS Type": "BCM; RFA/KVM",
    "Keypad Location":
      "SJB sticker; passenger side under glove box, on connector side",
    Notes: "80-bit; high security",
  },
  {
    Make: "Ford",
    Model: "Escape",
    Platform: "C2",
    "Start Year": 2014,
    "End Year": 2019,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500 (keyed); 11501-13000 (prox)",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "SJB sticker; passenger side under glove box, on connector side",
    Notes: "80-bit; high security",
  },
  {
    Make: "Ford",
    Model: "Escape",
    Platform: "C2",
    "Start Year": 2020,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "20001-31544",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side under dash",
    Notes: "Gen 5 PEPS; center-mill HU198; 30001-31544 confirmed",
  },
  {
    Make: "Ford",
    Model: "Escort",
    Platform: "Escort",
    "Start Year": 1985,
    "End Year": 1990,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; no transponder",
  },
  {
    Make: "Ford",
    Model: "Escort",
    Platform: "Escort (Mazda)",
    "Start Year": 1991,
    "End Year": 1996,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; no transponder",
  },
  {
    Make: "Ford",
    Model: "Escort",
    Platform: "Escort (Mazda)",
    "Start Year": 1997,
    "End Year": 2003,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "10100-12283",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; includes ZX2",
  },
  {
    Make: "Ford",
    Model: "Excursion",
    Platform: "SD/P",
    "Start Year": 2000,
    "End Year": 2005,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS / Instrument Cluster",
    "Keypad Location":
      "RAP module; above RH kick panel or behind driver's dash above radio",
    Notes: "4C chip",
  },
  {
    Make: "Ford",
    Model: "Expedition",
    Platform: "T1/P",
    "Start Year": 1997,
    "End Year": 1999,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS / Instrument Cluster",
    "Keypad Location": null,
    Notes: "4C chip",
  },
  {
    Make: "Ford",
    Model: "Expedition",
    Platform: "T1/P",
    "Start Year": 2000,
    "End Year": 2002,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS / Instrument Cluster",
    "Keypad Location": "RAP module; behind driver's dash, above radio area",
    Notes: "4C chip",
  },
  {
    Make: "Ford",
    Model: "Expedition",
    Platform: "T2/P",
    "Start Year": 2003,
    "End Year": 2006,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / Instrument Cluster (ICM)",
    "Keypad Location": "RAP module; behind driver's dash, above radio area",
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Expedition",
    Platform: "T2/P",
    "Start Year": 2007,
    "End Year": 2010,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / Instrument Cluster (ICM)",
    "Keypad Location": "SJB; passenger side footwell, A-pillar area",
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Expedition",
    Platform: "T2/P",
    "Start Year": 2011,
    "End Year": 2013,
    "Ignition Type": "Keyed",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "ICM",
    "Keypad Location": "SJB; passenger side footwell, A-pillar area",
    Notes: "80-bit; includes EL/MAX",
  },
  {
    Make: "Ford",
    Model: "Expedition",
    Platform: "T2/P",
    "Start Year": 2014,
    "End Year": 2014,
    "Ignition Type": "Keyed",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / PCM",
    "Keypad Location": "SJB; passenger side footwell, A-pillar area",
    Notes: "80-bit; includes EL/MAX",
  },
  {
    Make: "Ford",
    Model: "Expedition",
    Platform: "T2/P",
    "Start Year": 2015,
    "End Year": 2017,
    "Ignition Type": "Keyed",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / PCM",
    "Keypad Location": "SJB; passenger side footwell, A-pillar area",
    Notes: "80-bit; includes EL/MAX",
  },
  {
    Make: "Ford",
    Model: "Expedition",
    Platform: "T3/P",
    "Start Year": 2018,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "1-4000 (keyed); 10001-11500 (prox)",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Philips 46; includes MAX",
  },
  {
    Make: "Ford",
    Model: "Explorer",
    Platform: "UN/U2",
    "Start Year": 1991,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Explorer",
    Platform: "UN/U2",
    "Start Year": 1998,
    "End Year": 1998,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": null,
    Notes: "4C chip; mid-year key change 2000",
  },
  {
    Make: "Ford",
    Model: "Explorer",
    Platform: "UN/U2",
    "Start Year": 1999,
    "End Year": 2001,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location":
      "RAP module; rear cargo area near jack compartment or pass. rear seatbelt pillar",
    Notes: "4C chip; mid-year key change 2000",
  },
  {
    Make: "Ford",
    Model: "Explorer",
    Platform: "U152",
    "Start Year": 2002,
    "End Year": 2005,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / Instrument Cluster (ICM)",
    "Keypad Location":
      "RAP module; rear cargo area near jack compartment or pass. rear seatbelt pillar",
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Explorer",
    Platform: "D3/U251",
    "Start Year": 2006,
    "End Year": 2010,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / Instrument Cluster (ICM)",
    "Keypad Location":
      "SJB; under driver's side dash, above parking brake pedal",
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Explorer",
    Platform: "D4",
    "Start Year": 2011,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM; RFA/KVM",
    "Keypad Location":
      "Sticker on passenger fuse panel; under instrument panel, LH side of steering column",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "Explorer",
    Platform: "D4",
    "Start Year": 2014,
    "End Year": 2015,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "Sticker on passenger fuse panel; under instrument panel, LH side of steering column",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "Explorer",
    Platform: "D4",
    "Start Year": 2016,
    "End Year": 2017,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "1-4000",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "Sticker on passenger fuse panel; under instrument panel, LH side of steering column",
    Notes: "Philips 46",
  },
  {
    Make: "Ford",
    Model: "Explorer",
    Platform: "D4",
    "Start Year": 2018,
    "End Year": 2019,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "1-4000",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "Sticker on passenger fuse panel; under instrument panel, LH side of steering column",
    Notes: "Philips 46",
  },
  {
    Make: "Ford",
    Model: "Explorer",
    Platform: "CD6",
    "Start Year": 2020,
    "End Year": 2025,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; passenger side kick panel area",
    Notes: 'CD6 RWD "Platform"; prox only',
  },
  {
    Make: "Ford",
    Model: "Explorer Sport Trac",
    Platform: "UN/U2",
    "Start Year": 2001,
    "End Year": 2006,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / Instrument Cluster (ICM)",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Explorer Sport Trac",
    Platform: "D3/U251",
    "Start Year": 2007,
    "End Year": 2010,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / Instrument Cluster (ICM)",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "F-150",
    Platform: "T1/P",
    "Start Year": 1985,
    "End Year": 1995,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "FA/FB / A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "F-150",
    Platform: "T2/P",
    "Start Year": 1996,
    "End Year": 1998,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes:
      "1996 is split year: may have old 10-cut (H54/H67) or new 8-cut (H75) system. No PATS on regular F-150",
  },
  {
    Make: "Ford",
    Model: "F-150",
    Platform: "T2/P",
    "Start Year": 2004,
    "End Year": 2008,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location":
      "RAP module; behind dash above radio or driver kick panel",
    Notes: "4D63 chip; 11th gen 04-08; 12th 09+",
  },
  {
    Make: "Ford",
    Model: "F-150",
    Platform: "T2/P",
    "Start Year": 2009,
    "End Year": 2010,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "4D63 chip; 11th gen 04-08; 12th 09+",
  },
  {
    Make: "Ford",
    Model: "F-150",
    Platform: "T2/P",
    "Start Year": 2011,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "F-150",
    Platform: "T2/P",
    "Start Year": 2014,
    "End Year": 2014,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "F-150",
    Platform: "T3/P",
    "Start Year": 2015,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "F-150",
    Platform: "T3/P",
    "Start Year": 2017,
    "End Year": 2017,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "F-150",
    Platform: "T3/P",
    "Start Year": 2018,
    "End Year": 2020,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "Philips 46; aluminum body",
  },
  {
    Make: "Ford",
    Model: "F-150",
    Platform: "T3/P",
    "Start Year": 2021,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "P0001-P3711",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes:
      "P-series code from 2021; center-mill; Lishi HU198; per AutoSmart/NAL",
  },
  {
    Make: "Ford",
    Model: "F-150 Heritage",
    Platform: "T1/P",
    "Start Year": 1999,
    "End Year": 2004,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster",
    "Keypad Location": null,
    Notes: "4C chip; 10th gen body",
  },
  {
    Make: "Ford",
    Model: "F-150 Lightning",
    Platform: "T3/P (EV)",
    "Start Year": 2022,
    "End Year": 2025,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "P0001-P3711",
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; behind passenger kick panel",
    Notes: "P-series code; center-mill; prox only; per AutoSmart/NAL",
  },
  {
    Make: "Ford",
    Model: "F-250",
    Platform: "T1/P",
    "Start Year": 1985,
    "End Year": 1995,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "FA/FB / A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; light duty",
  },
  {
    Make: "Ford",
    Model: "F-250 (Light Duty)",
    Platform: "T1/P",
    "Start Year": 1996,
    "End Year": 1999,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster",
    "Keypad Location": null,
    Notes:
      "1996 is split year: may have old 10-cut or new 8-cut system. Under 8500# GVW; 4C chip",
  },
  {
    Make: "Ford",
    Model: "F-250 Super Duty",
    Platform: "SD/P",
    "Start Year": 1999,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": null,
    "Keypad Location":
      "RAP module; behind driver's dash, cream/white box behind radio",
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "F-250 Super Duty",
    Platform: "SD/P",
    "Start Year": 2008,
    "End Year": 2010,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "PATS standard from 2008 per key guides",
  },
  {
    Make: "Ford",
    Model: "F-250 Super Duty",
    Platform: "SD/P",
    "Start Year": 2011,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "80-bit; per 2013 PATS job aid",
  },
  {
    Make: "Ford",
    Model: "F-250 Super Duty",
    Platform: "SD/P",
    "Start Year": 2014,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "80-bit; per 2013 PATS job aid",
  },
  {
    Make: "Ford",
    Model: "F-250 Super Duty",
    Platform: "SD/P",
    "Start Year": 2017,
    "End Year": 2017,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "Stays on 10001-11500 code series per AutoSmart; side-mill HU101",
  },
  {
    Make: "Ford",
    Model: "F-250 Super Duty",
    Platform: "SD/P",
    "Start Year": 2018,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "Stays on 10001-11500 code series per AutoSmart; side-mill HU101",
  },
  {
    Make: "Ford",
    Model: "F-350",
    Platform: "T1/P",
    "Start Year": 1985,
    "End Year": 1995,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "FA/FB / A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; light duty",
  },
  {
    Make: "Ford",
    Model: "F-350",
    Platform: "T1/P",
    "Start Year": 1996,
    "End Year": 1998,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes:
      "1996 is split year: may have old 10-cut or new 8-cut system. No PATS.",
  },
  {
    Make: "Ford",
    Model: "F-350 Super Duty",
    Platform: "SD/P",
    "Start Year": 1999,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": null,
    "Keypad Location":
      "RAP module; behind driver's dash, cream/white box behind radio",
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "F-350 Super Duty",
    Platform: "SD/P",
    "Start Year": 2008,
    "End Year": 2010,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "PATS standard from 2008 per key guides",
  },
  {
    Make: "Ford",
    Model: "F-350 Super Duty",
    Platform: "SD/P",
    "Start Year": 2011,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "F-350 Super Duty",
    Platform: "SD/P",
    "Start Year": 2014,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "F-350 Super Duty",
    Platform: "SD/P",
    "Start Year": 2017,
    "End Year": 2017,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "Assumed same as F-250; stays on 10001-11500; verify per vehicle",
  },
  {
    Make: "Ford",
    Model: "F-350 Super Duty",
    Platform: "SD/P",
    "Start Year": 2018,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "Assumed same as F-250; stays on 10001-11500; verify per vehicle",
  },
  {
    Make: "Ford",
    Model: "F-450 Super Duty",
    Platform: "SD/P",
    "Start Year": 1999,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": null,
    "Keypad Location":
      "RAP module; behind driver's dash, cream/white box behind radio",
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "F-450 Super Duty",
    Platform: "SD/P",
    "Start Year": 2008,
    "End Year": 2013,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM (optional?)",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "PATS may be optional; verify per vehicle",
  },
  {
    Make: "Ford",
    Model: "F-450 Super Duty",
    Platform: "SD/P",
    "Start Year": 2014,
    "End Year": 2016,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / PCM",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "PATS may be optional; verify per vehicle",
  },
  {
    Make: "Ford",
    Model: "F-450 Super Duty",
    Platform: "SD/P",
    "Start Year": 2017,
    "End Year": 2017,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "Assumed same as F-250; stays on 10001-11500; verify per vehicle",
  },
  {
    Make: "Ford",
    Model: "F-450 Super Duty",
    Platform: "SD/P",
    "Start Year": 2018,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "Assumed same as F-250; stays on 10001-11500; verify per vehicle",
  },
  {
    Make: "Ford",
    Model: "F-550 Super Duty",
    Platform: "SD/P",
    "Start Year": 1999,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": null,
    "Keypad Location":
      "RAP module; behind driver's dash, cream/white box behind radio",
    Notes:
      "CHECK: ILCO lists F-250/350/450 but not F-550 explicitly; may share with F-450",
  },
  {
    Make: "Ford",
    Model: "F-550 Super Duty",
    Platform: "SD/P",
    "Start Year": 2008,
    "End Year": 2013,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM (optional?)",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "PATS may be optional; verify per vehicle",
  },
  {
    Make: "Ford",
    Model: "F-550 Super Duty",
    Platform: "SD/P",
    "Start Year": 2014,
    "End Year": 2016,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / PCM",
    "Keypad Location": "SJB; RH side of instrument panel, behind kick panel",
    Notes: "PATS may be optional; verify per vehicle",
  },
  {
    Make: "Ford",
    Model: "F-550 Super Duty",
    Platform: "SD/P",
    "Start Year": 2017,
    "End Year": 2017,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "Assumed same as F-250; stays on 10001-11500; verify per vehicle",
  },
  {
    Make: "Ford",
    Model: "F-550 Super Duty",
    Platform: "SD/P",
    "Start Year": 2018,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location":
      "BCM sticker; behind passenger kick panel, behind fuse block",
    Notes: "Assumed same as F-250; stays on 10001-11500; verify per vehicle",
  },
  {
    Make: "Ford",
    Model: "Festiva",
    Platform: "Festiva",
    "Start Year": 1988,
    "End Year": 1993,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "6500-7733",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Fiesta",
    Platform: "B3",
    "Start Year": 2011,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "ICM; RFA/KVM",
    "Keypad Location": null,
    Notes: "High security; 80-bit",
  },
  {
    Make: "Ford",
    Model: "Fiesta",
    Platform: "B3",
    "Start Year": 2014,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": null,
    Notes: "High security; 80-bit",
  },
  {
    Make: "Ford",
    Model: "Fiesta",
    Platform: "B3",
    "Start Year": 2017,
    "End Year": 2019,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": null,
    Notes: "High security; 80-bit",
  },
  {
    Make: "Ford",
    Model: "Five Hundred",
    Platform: "D3",
    "Start Year": 2005,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Flex",
    Platform: "D3",
    "Start Year": 2009,
    "End Year": 2012,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "ICM",
    "Keypad Location": "SJB; above parking brake pedal, driver's side",
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Flex",
    Platform: "D3",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM; RFA/KVM",
    "Keypad Location": "SJB; above parking brake pedal, driver's side",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "Flex",
    Platform: "D3",
    "Start Year": 2014,
    "End Year": 2019,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "SJB; above parking brake pedal, driver's side",
    Notes: "80-bit",
  },
  {
    Make: "Ford",
    Model: "Focus",
    Platform: "C1",
    "Start Year": 2000,
    "End Year": 2005,
    "Ignition Type": "Keyed",
    "Key Blank": "H86-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D60 chip; no RHK",
  },
  {
    Make: "Ford",
    Model: "Focus",
    Platform: "C1",
    "Start Year": 2006,
    "End Year": 2011,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / ICM",
    "Keypad Location": null,
    Notes: "4D63 chip; RHK available",
  },
  {
    Make: "Ford",
    Model: "Focus",
    Platform: "C2",
    "Start Year": 2012,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500 (keyed); 11501-13000 (prox)",
    "PATS Type": "ICM; RFA/KVM",
    "Keypad Location": null,
    Notes: "High security; 80-bit; includes ST/RS/Electric",
  },
  {
    Make: "Ford",
    Model: "Focus",
    Platform: "C2",
    "Start Year": 2014,
    "End Year": 2018,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500 (keyed); 11501-13000 (prox)",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": null,
    Notes: "High security; 80-bit; includes ST/RS/Electric",
  },
  {
    Make: "Ford",
    Model: "Freestar",
    Platform: "Freestar",
    "Start Year": 2004,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Freestyle",
    Platform: "D3",
    "Start Year": 2005,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Fusion",
    Platform: "CD3",
    "Start Year": 2006,
    "End Year": 2012,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster (ICM) / ICM",
    "Keypad Location": null,
    Notes: "4D63 chip; RHK available",
  },
  {
    Make: "Ford",
    Model: "Fusion",
    Platform: "CD4",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM",
    "Keypad Location": "BCM; left side lower dash",
    Notes: "Philips 46 chip; H128-PT from 2013; high security HU101 keyway",
  },
  {
    Make: "Ford",
    Model: "Fusion",
    Platform: "CD4",
    "Start Year": 2014,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM; left side lower dash",
    Notes: "Philips 46 chip; H128-PT from 2013; high security HU101 keyway",
  },
  {
    Make: "Ford",
    Model: "Fusion",
    Platform: "CD4",
    "Start Year": 2017,
    "End Year": 2020,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM; left side lower dash",
    Notes: "Philips 46 chip; H128-PT from 2013; high security HU101 keyway",
  },
  {
    Make: "Ford",
    Model: "GT",
    Platform: "GT",
    "Start Year": 2005,
    "End Year": 2006,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": null,
    Notes: "4C chip per ILCO",
  },
  {
    Make: "Ford",
    Model: "GT",
    Platform: "GT",
    "Start Year": 2017,
    "End Year": 2020,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": null,
    Notes: "Prox only",
  },
  {
    Make: "Ford",
    Model: "GT",
    Platform: "GT",
    "Start Year": 2021,
    "End Year": 2022,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": null,
    Notes: "Prox only",
  },
  {
    Make: "Ford",
    Model: "LCF / Low Cab Forward",
    Platform: "LCF",
    "Start Year": 2006,
    "End Year": 2009,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "Key info TBD; Navistar diesel",
  },
  {
    Make: "Ford",
    Model: "LCF / Low Cab Forward",
    Platform: "LCF",
    "Start Year": 2016,
    "End Year": 2025,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "Key info TBD",
  },
  {
    Make: "Ford",
    Model: "LTD",
    Platform: "Panther",
    "Start Year": 1985,
    "End Year": 1986,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Maverick",
    Platform: "C2",
    "Start Year": 2022,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "20001-31544",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel (if equipped)",
    Notes: "Philips 46; per ILCO",
  },
  {
    Make: "Ford",
    Model: "Mustang",
    Platform: "Fox",
    "Start Year": 1985,
    "End Year": 1993,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Mustang",
    Platform: "SN95",
    "Start Year": 1994,
    "End Year": 1995,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Mustang",
    Platform: "SN95",
    "Start Year": 1996,
    "End Year": 2004,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS / Instrument Cluster",
    "Keypad Location": null,
    Notes: "4C chip; H73-PT for 96 GT (10-cut); Type A 96-97, B 98, C 99-04",
  },
  {
    Make: "Ford",
    Model: "Mustang",
    Platform: "S197",
    "Start Year": 2005,
    "End Year": 2013,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / ICM",
    "Keypad Location": null,
    Notes: "4D63 chip; RHK from 2005+",
  },
  {
    Make: "Ford",
    Model: "Mustang",
    Platform: "S197",
    "Start Year": 2014,
    "End Year": 2014,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / PCM",
    "Keypad Location": null,
    Notes: "4D63 chip; RHK from 2005+",
  },
  {
    Make: "Ford",
    Model: "Mustang",
    Platform: "S550",
    "Start Year": 2015,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "N/A (no factory keypad)",
    Notes: "Philips 46 chip; high security",
  },
  {
    Make: "Ford",
    Model: "Mustang",
    Platform: "S550",
    "Start Year": 2017,
    "End Year": 2017,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "N/A (no factory keypad)",
    Notes: "Philips 46 chip; high security",
  },
  {
    Make: "Ford",
    Model: "Mustang",
    Platform: "S550",
    "Start Year": 2018,
    "End Year": 2023,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "N/A (no factory keypad)",
    Notes: "Philips 46 chip; high security",
  },
  {
    Make: "Ford",
    Model: "Mustang",
    Platform: "S650",
    "Start Year": 2024,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "N/A (no factory keypad)",
    Notes: "Philips 46 chip; high security",
  },
  {
    Make: "Ford",
    Model: "Mustang Mach-E",
    Platform: "GE1 (EV)",
    "Start Year": 2021,
    "End Year": 2025,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": null,
    Notes: "Prox only; phone-as-key",
  },
  {
    Make: "Ford",
    Model: "Probe",
    Platform: "Mazda GE",
    "Start Year": 1989,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "6500-7733 / 10100-12283",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; Mazda keyway",
  },
  {
    Make: "Ford",
    Model: "Ranger",
    Platform: "Ranger",
    "Start Year": 1985,
    "End Year": 1998,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Ranger",
    Platform: "Ranger",
    "Start Year": 2005,
    "End Year": 2011,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / Instrument Cluster (ICM)",
    "Keypad Location": null,
    Notes: "4D63 chip; Type G/C in 2007",
  },
  {
    Make: "Ford",
    Model: "Ranger",
    Platform: "T6",
    "Start Year": 2019,
    "End Year": 2025,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: 'Prox only; global "Platform"',
  },
  {
    Make: "Ford",
    Model: "Ranger (2.3L, 3.0L, 4.0L)",
    Platform: "Ranger",
    "Start Year": 2001,
    "End Year": 2004,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip on all listed engines",
  },
  {
    Make: "Ford",
    Model: "Ranger (3.0L & 4.0L V6)",
    Platform: "Ranger",
    "Start Year": 1999,
    "End Year": 2000,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": null,
    Notes: "4C chip; V6 only",
  },
  {
    Make: "Ford",
    Model: "Ranger (4-Cyl)",
    Platform: "Ranger",
    "Start Year": 1999,
    "End Year": 2000,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Taurus",
    Platform: "DN5",
    "Start Year": 1986,
    "End Year": 1995,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Taurus",
    Platform: "DN5",
    "Start Year": 1998,
    "End Year": 1999,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": "RAP module; varies by year",
    Notes: "4C chip; all engines",
  },
  {
    Make: "Ford",
    Model: "Taurus",
    Platform: "DN5",
    "Start Year": 2000,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": "RAP module; varies by year",
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Taurus",
    Platform: "D3",
    "Start Year": 2008,
    "End Year": 2009,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": "SJB; above parking brake area",
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Taurus",
    Platform: "D3",
    "Start Year": 2010,
    "End Year": 2012,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "ICM / BCM; RFA/KVM",
    "Keypad Location": "SJB/BCM; driver's side under dash",
    Notes: "80-bit; keyed and prox available",
  },
  {
    Make: "Ford",
    Model: "Taurus",
    Platform: "D3",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "ICM / BCM; RFA/KVM",
    "Keypad Location": "SJB/BCM; driver's side under dash",
    Notes: "80-bit; keyed and prox available",
  },
  {
    Make: "Ford",
    Model: "Taurus",
    Platform: "D3",
    "Start Year": 2014,
    "End Year": 2019,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "SJB/BCM; driver's side under dash",
    Notes: "80-bit; keyed and prox available",
  },
  {
    Make: "Ford",
    Model: "Taurus (Duratec/SHO)",
    Platform: "DN5",
    "Start Year": 1996,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": null,
    Notes: "4C chip; PATS on Duratec/SHO only",
  },
  {
    Make: "Ford",
    Model: "Taurus (Vulcan V6)",
    Platform: "DN5",
    "Start Year": 1996,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / 1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; Vulcan 3.0L; ILCO lists as 'Taurus LX'",
  },
  {
    Make: "Ford",
    Model: "Taurus X",
    Platform: "D3",
    "Start Year": 2008,
    "End Year": 2009,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip; Freestyle replacement",
  },
  {
    Make: "Ford",
    Model: "Tempo",
    Platform: "Tempo",
    "Start Year": 1985,
    "End Year": 1994,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / FA/FB",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Thunderbird",
    Platform: "Fox",
    "Start Year": 1985,
    "End Year": 1988,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / 1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; H75 keyway from 1996-97",
  },
  {
    Make: "Ford",
    Model: "Thunderbird",
    Platform: "MN12",
    "Start Year": 1989,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / 1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; H75 keyway from 1996-97",
  },
  {
    Make: "Ford",
    Model: "Thunderbird",
    Platform: "DEW98",
    "Start Year": 2002,
    "End Year": 2002,
    "Ignition Type": "Keyed",
    "Key Blank": "H86-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster",
    "Keypad Location": null,
    Notes: "4C chip; H86-PT (not H74-PT); H86 blade works for both apps",
  },
  {
    Make: "Ford",
    Model: "Thunderbird",
    Platform: "DEW98",
    "Start Year": 2003,
    "End Year": 2005,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Ford",
    Model: "Transit",
    Platform: "Transit",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM",
    "Keypad Location": null,
    Notes: "High security HU101 keyway; 80-bit",
  },
  {
    Make: "Ford",
    Model: "Transit",
    Platform: "Transit",
    "Start Year": 2014,
    "End Year": 2014,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": null,
    Notes: "High security HU101 keyway; 80-bit",
  },
  {
    Make: "Ford",
    Model: "Transit",
    Platform: "Transit",
    "Start Year": 2015,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM; varies (if equipped)",
    Notes: "High security HU101 keyway; 80-bit",
  },
  {
    Make: "Ford",
    Model: "Transit",
    Platform: "Transit",
    "Start Year": 2017,
    "End Year": 2019,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM; varies (if equipped)",
    Notes: "High security HU101 keyway; 80-bit",
  },
  {
    Make: "Ford",
    Model: "Transit",
    Platform: "Transit",
    "Start Year": 2020,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM; varies (if equipped)",
    Notes: "High security HU101 keyway; 80-bit",
  },
  {
    Make: "Ford",
    Model: "Transit Connect",
    Platform: "C1",
    "Start Year": 2010,
    "End Year": 2013,
    "Ignition Type": "Keyed",
    "Key Blank": "Tibbe (FO21)",
    "Service Key": null,
    "Lishi Tool": "FO21 (Tibbe)",
    "Code Series": "T111111-T444444",
    "PATS Type": "ICM",
    "Keypad Location": null,
    Notes: "Tibbe keyway; unique in Ford lineup; per Keyline",
  },
  {
    Make: "Ford",
    Model: "Transit Connect",
    Platform: "C2",
    "Start Year": 2014,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": null,
    Notes: "High security HU101; switched from Tibbe",
  },
  {
    Make: "Ford",
    Model: "Transit Connect",
    Platform: "C2",
    "Start Year": 2017,
    "End Year": 2020,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": null,
    Notes: "High security HU101; switched from Tibbe",
  },
  {
    Make: "Ford",
    Model: "Transit Connect",
    Platform: "C2",
    "Start Year": 2021,
    "End Year": 2025,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H94-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": null,
    Notes: "High security HU101; switched from Tibbe",
  },
  {
    Make: "Ford",
    Model: "Windstar",
    Platform: "Windstar",
    "Start Year": 1995,
    "End Year": 1998,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / 1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Ford",
    Model: "Windstar",
    Platform: "Windstar",
    "Start Year": 1999,
    "End Year": 2003,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT / H84-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster / PCM",
    "Keypad Location": null,
    Notes: "H72-PT 99-00 (4C); H84-PT 01-03 (4D63)",
  },
  {
    Make: "Lincoln",
    Model: "Aviator",
    Platform: "UN152",
    "Start Year": 2003,
    "End Year": 2005,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Lincoln",
    Model: "Aviator",
    Platform: "CD6",
    "Start Year": 2020,
    "End Year": 2025,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Prox only",
  },
  {
    Make: "Lincoln",
    Model: "Blackwood",
    Platform: "T2/P",
    "Start Year": 2002,
    "End Year": 2003,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster",
    "Keypad Location": null,
    Notes: "4C chip",
  },
  {
    Make: "Lincoln",
    Model: "Continental",
    Platform: "Panther",
    "Start Year": 1985,
    "End Year": 1987,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Lincoln",
    Model: "Continental",
    Platform: "FN",
    "Start Year": 1988,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Lincoln",
    Model: "Continental",
    Platform: "FN",
    "Start Year": 1998,
    "End Year": 2002,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster",
    "Keypad Location": null,
    Notes: "4C chip",
  },
  {
    Make: "Lincoln",
    Model: "Continental",
    Platform: "CD4",
    "Start Year": 2017,
    "End Year": 2017,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; passenger side",
    Notes: "Prox only",
  },
  {
    Make: "Lincoln",
    Model: "Continental",
    Platform: "CD4",
    "Start Year": 2018,
    "End Year": 2020,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; passenger side",
    Notes: "Prox only",
  },
  {
    Make: "Lincoln",
    Model: "Corsair",
    Platform: "C2",
    "Start Year": 2020,
    "End Year": 2025,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": null,
    "Code Series": "10001-11500 (2020 keyed); 20001-31544 (prox)",
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Gen 5 PEPS prox; center-mill HU198; service key HU198T",
  },
  {
    Make: "Lincoln",
    Model: "LS",
    Platform: "DEW98",
    "Start Year": 2000,
    "End Year": 2002,
    "Ignition Type": "Keyed",
    "Key Blank": "H86-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster",
    "Keypad Location": null,
    Notes: "Per Keyline: BH86-PT",
  },
  {
    Make: "Lincoln",
    Model: "LS",
    Platform: "DEW98",
    "Start Year": 2003,
    "End Year": 2006,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Lincoln",
    Model: "MKC",
    Platform: "C2",
    "Start Year": 2015,
    "End Year": 2017,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Prox only",
  },
  {
    Make: "Lincoln",
    Model: "MKC",
    Platform: "C2",
    "Start Year": 2018,
    "End Year": 2019,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Prox only",
  },
  {
    Make: "Lincoln",
    Model: "MKS",
    Platform: "D3",
    "Start Year": 2009,
    "End Year": 2012,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "ICM / BCM; RFA/KVM",
    "Keypad Location": "SJB/BCM; driver's side under dash",
    Notes: "80-bit",
  },
  {
    Make: "Lincoln",
    Model: "MKS",
    Platform: "D3",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "ICM / BCM; RFA/KVM",
    "Keypad Location": "SJB/BCM; driver's side under dash",
    Notes: "80-bit",
  },
  {
    Make: "Lincoln",
    Model: "MKS",
    Platform: "D3",
    "Start Year": 2014,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "SJB/BCM; driver's side under dash",
    Notes: "80-bit",
  },
  {
    Make: "Lincoln",
    Model: "MKT",
    Platform: "D3",
    "Start Year": 2010,
    "End Year": 2012,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "H86 / HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "RFA/KVM",
    "Keypad Location": "BCM sticker; center console area",
    Notes: "Prox only",
  },
  {
    Make: "Lincoln",
    Model: "MKT",
    Platform: "D3",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "H86 / HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "RFA/KVM",
    "Keypad Location": "BCM sticker; center console area",
    Notes: "Prox only",
  },
  {
    Make: "Lincoln",
    Model: "MKT",
    Platform: "D3",
    "Start Year": 2014,
    "End Year": 2019,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "H86 / HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; center console area",
    Notes: "Prox only",
  },
  {
    Make: "Lincoln",
    Model: "MKX",
    Platform: "CD3",
    "Start Year": 2007,
    "End Year": 2010,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster (ICM)",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "4D63 chip",
  },
  {
    Make: "Lincoln",
    Model: "MKX",
    Platform: "CD3",
    "Start Year": 2011,
    "End Year": 2012,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "RFA/KVM",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "80-bit; mostly prox but keyed option exists",
  },
  {
    Make: "Lincoln",
    Model: "MKX",
    Platform: "CD3",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "RFA/KVM",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "80-bit; mostly prox but keyed option exists",
  },
  {
    Make: "Lincoln",
    Model: "MKX",
    Platform: "CD3",
    "Start Year": 2014,
    "End Year": 2015,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "80-bit; mostly prox but keyed option exists",
  },
  {
    Make: "Lincoln",
    Model: "MKX",
    Platform: "CD4",
    "Start Year": 2016,
    "End Year": 2018,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "80-bit; mostly prox but keyed option exists",
  },
  {
    Make: "Lincoln",
    Model: "MKZ",
    Platform: "CD3",
    "Start Year": 2006,
    "End Year": 2012,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster (ICM)",
    "Keypad Location": null,
    Notes: "4D63/80-bit; as Zephyr in 2006",
  },
  {
    Make: "Lincoln",
    Model: "MKZ",
    Platform: "CD4",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM",
    "Keypad Location": "BCM; cup holder/center console area",
    Notes: "Philips 46; high security",
  },
  {
    Make: "Lincoln",
    Model: "MKZ",
    Platform: "CD4",
    "Start Year": 2014,
    "End Year": 2016,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM; cup holder/center console area",
    Notes: "Philips 46; high security",
  },
  {
    Make: "Lincoln",
    Model: "MKZ",
    Platform: "CD4",
    "Start Year": 2017,
    "End Year": 2020,
    "Ignition Type": "Keyed, Smart Key",
    "Key Blank": "H128-PT",
    "Service Key": "HU101",
    "Lishi Tool": "HU101",
    "Code Series": "10001-11500",
    "PATS Type": "BCM / RFA (prox); BCM / PCM (keyed)",
    "Keypad Location": "BCM; cup holder/center console area",
    Notes: "Philips 46; high security",
  },
  {
    Make: "Lincoln",
    Model: "Mark LT",
    Platform: "T2/P",
    "Start Year": 2006,
    "End Year": 2008,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Lincoln",
    Model: "Mark VII",
    Platform: "Fox",
    "Start Year": 1985,
    "End Year": 1992,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Lincoln",
    Model: "Mark VIII",
    Platform: "FN",
    "Start Year": 1993,
    "End Year": 1996,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Lincoln",
    Model: "Mark VIII",
    Platform: "FN",
    "Start Year": 1997,
    "End Year": 1998,
    "Ignition Type": "Keyed",
    "Key Blank": "M8",
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "SCIL",
    "Keypad Location": null,
    Notes:
      "Bespoke Motorola chip, unique to 97-98 Mark VIII worldwide. Not H72. No substitutes, no aftermarket.",
  },
  {
    Make: "Lincoln",
    Model: "Nautilus",
    Platform: "CD4",
    "Start Year": 2019,
    "End Year": 2025,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Prox only",
  },
  {
    Make: "Lincoln",
    Model: "Navigator",
    Platform: "T1/P",
    "Start Year": 1998,
    "End Year": 2002,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS / Instrument Cluster",
    "Keypad Location": null,
    Notes: "4C chip",
  },
  {
    Make: "Lincoln",
    Model: "Navigator",
    Platform: "T1/P",
    "Start Year": 2003,
    "End Year": 2006,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / ICM",
    "Keypad Location": "RAP module; behind driver's dash",
    Notes: "4D63/80-bit",
  },
  {
    Make: "Lincoln",
    Model: "Navigator",
    Platform: "T2/P",
    "Start Year": 2007,
    "End Year": 2012,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / ICM",
    "Keypad Location": "SJB; passenger side footwell",
    Notes: "4D63/80-bit",
  },
  {
    Make: "Lincoln",
    Model: "Navigator",
    Platform: "T2/P",
    "Start Year": 2013,
    "End Year": 2013,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / ICM",
    "Keypad Location": "SJB; passenger side footwell",
    Notes: "4D63/80-bit",
  },
  {
    Make: "Lincoln",
    Model: "Navigator",
    Platform: "T2/P",
    "Start Year": 2014,
    "End Year": 2017,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "BCM / PCM",
    "Keypad Location": "SJB; passenger side footwell",
    Notes: "4D63/80-bit",
  },
  {
    Make: "Lincoln",
    Model: "Navigator",
    Platform: "T3/P",
    "Start Year": 2018,
    "End Year": 2025,
    "Ignition Type": "Smart Key",
    "Key Blank": null,
    "Service Key": "HU101",
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": "BCM / RFA",
    "Keypad Location": "BCM sticker; passenger side kick panel",
    Notes: "Prox only; 4th gen",
  },
  {
    Make: "Lincoln",
    Model: "Town Car",
    Platform: "Panther",
    "Start Year": 1985,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Lincoln",
    Model: "Town Car",
    Platform: "Panther",
    "Start Year": 1998,
    "End Year": 2002,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster",
    "Keypad Location": null,
    Notes: "4C chip",
  },
  {
    Make: "Lincoln",
    Model: "Town Car",
    Platform: "Panther",
    "Start Year": 2003,
    "End Year": 2011,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Mercury",
    Model: "Capri",
    Platform: "Mazda MX-5",
    "Start Year": 1991,
    "End Year": 1994,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; Australian-built",
  },
  {
    Make: "Mercury",
    Model: "Cougar",
    Platform: "Fox",
    "Start Year": 1985,
    "End Year": 1988,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; T-Bird twin",
  },
  {
    Make: "Mercury",
    Model: "Cougar",
    Platform: "MN12",
    "Start Year": 1989,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; T-Bird twin",
  },
  {
    Make: "Mercury",
    Model: "Cougar",
    Platform: "CDW27",
    "Start Year": 1999,
    "End Year": 2002,
    "Ignition Type": "Keyed",
    "Key Blank": "H73-PT",
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-B-C-D-E",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "10-cut; 4C chip per ILCO/Keyline",
  },
  {
    Make: "Mercury",
    Model: "Grand Marquis",
    Platform: "Panther",
    "Start Year": 1985,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Mercury",
    Model: "Grand Marquis",
    Platform: "Panther",
    "Start Year": 1998,
    "End Year": 2002,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": null,
    Notes: "4C chip",
  },
  {
    Make: "Mercury",
    Model: "Grand Marquis",
    Platform: "Panther",
    "Start Year": 2003,
    "End Year": 2011,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Mercury",
    Model: "Lynx",
    Platform: "Escort",
    "Start Year": 1985,
    "End Year": 1987,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Mercury",
    Model: "Marauder",
    Platform: "Panther",
    "Start Year": 2003,
    "End Year": 2004,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Mercury",
    Model: "Mariner",
    Platform: "C1",
    "Start Year": 2005,
    "End Year": 2011,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip; Escape twin",
  },
  {
    Make: "Mercury",
    Model: "Milan",
    Platform: "CD3",
    "Start Year": 2006,
    "End Year": 2011,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Instrument Cluster (ICM)",
    "Keypad Location": null,
    Notes: "4D63 chip; Fusion twin",
  },
  {
    Make: "Mercury",
    Model: "Montego",
    Platform: "D3",
    "Start Year": 2005,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Mercury",
    Model: "Monterey",
    Platform: "Freestar",
    "Start Year": 2004,
    "End Year": 2007,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip; Freestar twin",
  },
  {
    Make: "Mercury",
    Model: "Mountaineer",
    Platform: "UN/U2",
    "Start Year": 1997,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Mercury",
    Model: "Mountaineer",
    Platform: "UN/U2",
    "Start Year": 1998,
    "End Year": 1998,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": null,
    Notes: "4C chip; mid-year change 2000",
  },
  {
    Make: "Mercury",
    Model: "Mountaineer",
    Platform: "UN/U2",
    "Start Year": 1999,
    "End Year": 2001,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": "RAP module; rear cargo area near jack compartment",
    Notes: "4C chip; mid-year change 2000",
  },
  {
    Make: "Mercury",
    Model: "Mountaineer",
    Platform: "U152",
    "Start Year": 2002,
    "End Year": 2005,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / Instrument Cluster (ICM)",
    "Keypad Location": "RAP module; rear cargo area near jack compartment",
    Notes: "4D63 chip",
  },
  {
    Make: "Mercury",
    Model: "Mountaineer",
    Platform: "D3/U251",
    "Start Year": 2006,
    "End Year": 2010,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / Instrument Cluster (ICM)",
    "Keypad Location": "SJB; under driver's side dash, above parking brake",
    Notes: "4D63 chip",
  },
  {
    Make: "Mercury",
    Model: "Mountaineer",
    Platform: "D3/U251",
    "Start Year": 2011,
    "End Year": 2011,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM / Instrument Cluster (ICM)",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Mercury",
    Model: "Mystique",
    Platform: "CDW27",
    "Start Year": 1995,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-B-C-D-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Mercury",
    Model: "Mystique (4-Cyl)",
    Platform: "CDW27",
    "Start Year": 1998,
    "End Year": 2000,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": "A-B-C-D-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; ILCO lists as Mystique GS",
  },
  {
    Make: "Mercury",
    Model: "Mystique (V6)",
    Platform: "CDW27",
    "Start Year": 1998,
    "End Year": 2000,
    "Ignition Type": "Keyed",
    "Key Blank": "H73-PT",
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-B-C-D-E",
    "PATS Type": "Standalone PATS / PCM",
    "Keypad Location": null,
    Notes: "10-cut; 4C chip; ILCO lists as Mystique LS",
  },
  {
    Make: "Mercury",
    Model: "Sable",
    Platform: "DN5",
    "Start Year": 1986,
    "End Year": 1995,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Mercury",
    Model: "Sable",
    Platform: "DN5",
    "Start Year": 1998,
    "End Year": 1999,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": null,
    Notes: "4C chip; all engines",
  },
  {
    Make: "Mercury",
    Model: "Sable",
    Platform: "DN5",
    "Start Year": 2000,
    "End Year": 2005,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip",
  },
  {
    Make: "Mercury",
    Model: "Sable",
    Platform: "D3",
    "Start Year": 2008,
    "End Year": 2009,
    "Ignition Type": "Keyed",
    "Key Blank": "H84-PT / H92-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "PCM",
    "Keypad Location": null,
    Notes: "4D63 chip; Taurus twin",
  },
  {
    Make: "Mercury",
    Model: "Sable (Duratec)",
    Platform: "DN5",
    "Start Year": 1996,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": "H72-PT",
    "Service Key": "H86",
    "Lishi Tool": "FO38",
    "Code Series": "1X-1706X",
    "PATS Type": "Standalone PATS",
    "Keypad Location": null,
    Notes: "4C chip; Duratec only",
  },
  {
    Make: "Mercury",
    Model: "Sable (Vulcan V6)",
    Platform: "DN5",
    "Start Year": 1996,
    "End Year": 1997,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / 1X-1706X",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Mercury",
    Model: "Topaz",
    Platform: "Tempo",
    "Start Year": 1985,
    "End Year": 1994,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / FA/FB",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Mercury",
    Model: "Tracer",
    Platform: "Escort (Mazda)",
    "Start Year": 1988,
    "End Year": 1999,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": "FO38",
    "Code Series": "A-E / 10100-12283",
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS",
  },
  {
    Make: "Mercury",
    Model: "Villager",
    Platform: "Nissan V40",
    "Start Year": 1993,
    "End Year": 2002,
    "Ignition Type": "Keyed",
    "Key Blank": null,
    "Service Key": null,
    "Lishi Tool": null,
    "Code Series": null,
    "PATS Type": null,
    "Keypad Location": null,
    Notes: "No PATS; Nissan Quest twin; Nissan keyway",
  },
];
