export const JAGUAR_DATA = [
  {
    Make: "Jaguar",
    Model: "E-Pace (X540)",
    "Start Year": 2018,
    "End Year": 2018,
    Platform: "X540",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Location": "Trunk, left side under fuse box",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "E-Pace (X540)",
    "Start Year": 2019,
    "End Year": 2025,
    Platform: "X540",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Location": "Trunk, left side under fuse box",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "F-Pace (X761)",
    "Start Year": 2017,
    "End Year": 2018,
    Platform: "X761",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Location": "Trunk, right side under fuse box",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "F-Pace (X761)",
    "Start Year": 2019,
    "End Year": 2025,
    Platform: "X761",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Location": "Trunk, right side under fuse box",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "F-Type (X152)",
    "Start Year": 2014,
    "End Year": 2017,
    Platform: "X152",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Location": "Passenger footwell, right side",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "F-Type (X152)",
    "Start Year": 2018,
    "End Year": 2024,
    Platform: "X152",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM/RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Location": "Passenger footwell, right side",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "I-Pace (I1)",
    "Start Year": 2019,
    "End Year": 2025,
    Platform: "I1",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Location": "Trunk, right side under fuse box",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "All-electric",
  },
  {
    Make: "Jaguar",
    Model: "S-Type",
    "Start Year": 2000,
    "End Year": 2008,
    Platform: "S-Type (X200)",
    "Key Type": "Metal Key",
    "Immobilizer System": "Ford PATS",
    "Key Blade": "Tibbe 6-cut (FO21)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "4D60 (Texas Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Ford DEW98 platform; Code series T111111-T444444",
  },
  {
    Make: "Jaguar",
    Model: "Super V8 (X350/X358)",
    "Start Year": 2005,
    "End Year": 2009,
    Platform: "X350/X358",
    "Key Type": "Flip Key",
    "Immobilizer System": "Ford PATS",
    "Key Blade": "Tibbe 6-cut (FO21)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "4D60 (Texas Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Top-tier XJ variant; Code series T111111-T444444",
  },
  {
    Make: "Jaguar",
    Model: "Vanden Plas (X350/X358)",
    "Start Year": 2004,
    "End Year": 2009,
    Platform: "X350/X358",
    "Key Type": "Flip Key",
    "Immobilizer System": "Ford PATS",
    "Key Blade": "Tibbe 6-cut (FO21)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "4D60 (Texas Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Long wheelbase luxury; Code series T111111-T444444",
  },
  {
    Make: "Jaguar",
    Model: "X-Type",
    "Start Year": 2002,
    "End Year": 2008,
    Platform: "X-Type (X400)",
    "Key Type": "Flip Key",
    "Immobilizer System": "Ford PATS",
    "Key Blade": "Tibbe 6-cut (FO21)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "4D60 (Texas Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes:
      "Ford Mondeo platform; Ford PATS system; Code series T111111-T444444",
  },
  {
    Make: "Jaguar",
    Model: "XE (X760)",
    "Start Year": 2017,
    "End Year": 2018,
    Platform: "X760",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Location": "Under rear passenger seat, right side",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "XE (X760)",
    "Start Year": 2019,
    "End Year": 2024,
    Platform: "X760",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Location": "Under rear passenger seat, right side",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "XF (X250)",
    "Start Year": 2009,
    "End Year": 2015,
    Platform: "X250",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A / KR55WK49244",
    "KVM/RFA Location": "Trunk, left side",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "XF (X260)",
    "Start Year": 2016,
    "End Year": 2018,
    Platform: "X260",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Location": "Passenger footwell, side trim panel",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "2nd generation",
  },
  {
    Make: "Jaguar",
    Model: "XF (X260)",
    "Start Year": 2019,
    "End Year": 2024,
    Platform: "X260",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Location": "Passenger footwell, side trim panel",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "2nd generation",
  },
  {
    Make: "Jaguar",
    Model: "XFR (X250)",
    "Start Year": 2010,
    "End Year": 2015,
    Platform: "X250",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A / KR55WK49244",
    "KVM/RFA Location": "Trunk, left side",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "Supercharged",
  },
  {
    Make: "Jaguar",
    Model: "XJ (X351)",
    "Start Year": 2011,
    "End Year": 2019,
    Platform: "X351",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A / KR55WK49244",
    "KVM/RFA Location": "Passenger footwell, right side",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "XJ12",
    "Start Year": 1993,
    "End Year": 1996,
    Platform: "XJ40",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Code series T11111111-T33333333",
  },
  {
    Make: "Jaguar",
    Model: "XJ6 (Series III)",
    "Start Year": 1986,
    "End Year": 1987,
    Platform: "Series III (XJ)",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Code series T11111111-T33333333",
  },
  {
    Make: "Jaguar",
    Model: "XJ6 (X300)",
    "Start Year": 1995,
    "End Year": 1997,
    Platform: "X300",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Code series T11111111-T33333333",
  },
  {
    Make: "Jaguar",
    Model: "XJ6 (XJ40)",
    "Start Year": 1988,
    "End Year": 1994,
    Platform: "XJ40",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Code series T11111111-T33333333",
  },
  {
    Make: "Jaguar",
    Model: "XJ8 (X308)",
    "Start Year": 1998,
    "End Year": 1999,
    Platform: "X308",
    "Key Type": "Metal Key",
    "Immobilizer System": "Jaguar Megamos",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "ID13 (Megamos 13)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "XJ8 (X308)",
    "Start Year": 2000,
    "End Year": 2003,
    Platform: "X308",
    "Key Type": "Metal Key",
    "Immobilizer System": "Jaguar Megamos",
    "Key Blade": "Tibbe 6-cut (FO21)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "ID48 (Megamos Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "XJ8 (X350/X358)",
    "Start Year": 2004,
    "End Year": 2009,
    Platform: "X350/X358",
    "Key Type": "Flip Key",
    "Immobilizer System": "Ford PATS",
    "Key Blade": "Tibbe 6-cut (FO21)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "4D60 (Texas Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Aluminium body; Code series T111111-T444444",
  },
  {
    Make: "Jaguar",
    Model: "XJR (X300)",
    "Start Year": 1995,
    "End Year": 1997,
    Platform: "X300",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Supercharged inline-6; Code series T11111111-T33333333",
  },
  {
    Make: "Jaguar",
    Model: "XJR (X308)",
    "Start Year": 1998,
    "End Year": 1999,
    Platform: "X308",
    "Key Type": "Metal Key",
    "Immobilizer System": "Jaguar Megamos",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "ID13 (Megamos 13)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Supercharged V8",
  },
  {
    Make: "Jaguar",
    Model: "XJR (X308)",
    "Start Year": 2000,
    "End Year": 2003,
    Platform: "X308",
    "Key Type": "Metal Key",
    "Immobilizer System": "Jaguar Megamos",
    "Key Blade": "Tibbe 6-cut (FO21)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "ID48 (Megamos Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Supercharged V8",
  },
  {
    Make: "Jaguar",
    Model: "XJR (X350/X358)",
    "Start Year": 2004,
    "End Year": 2009,
    Platform: "X350/X358",
    "Key Type": "Flip Key",
    "Immobilizer System": "Ford PATS",
    "Key Blade": "Tibbe 6-cut (FO21)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "4D60 (Texas Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Aluminium body; Supercharged; Code series T111111-T444444",
  },
  {
    Make: "Jaguar",
    Model: "XJS",
    "Start Year": 1986,
    "End Year": 1996,
    Platform: "XJS",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes:
      "Code series T11111111-T33333333; Final years; convertible and 2+2 coupe; Code series T11111111-T33333333",
  },
  {
    Make: "Jaguar",
    Model: "XK (X150)",
    "Start Year": 2007,
    "End Year": 2015,
    Platform: "X150",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A / KR55WK49244",
    "KVM/RFA Location": "Passenger footwell, left side trim",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "XK8 (X100)",
    "Start Year": 1997,
    "End Year": 1999,
    Platform: "X100",
    "Key Type": "Metal Key",
    "Immobilizer System": "Jaguar Megamos",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "ID13 (Megamos 13)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "XK8 (X100)",
    "Start Year": 2000,
    "End Year": 2000,
    Platform: "X100",
    "Key Type": "Metal Key",
    "Immobilizer System": "Jaguar Megamos",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "ID48 (Megamos Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "XK8 (X100)",
    "Start Year": 2001,
    "End Year": 2006,
    Platform: "X100",
    "Key Type": "Metal Key",
    "Immobilizer System": "Jaguar Megamos",
    "Key Blade": "Tibbe 6-cut (FO21)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "ID48 (Megamos Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Jaguar",
    Model: "XKR (X100)",
    "Start Year": 1999,
    "End Year": 1999,
    Platform: "X100",
    "Key Type": "Metal Key",
    "Immobilizer System": "Jaguar Megamos",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "ID13 (Megamos 13)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Supercharged",
  },
  {
    Make: "Jaguar",
    Model: "XKR (X100)",
    "Start Year": 2000,
    "End Year": 2000,
    Platform: "X100",
    "Key Type": "Metal Key",
    "Immobilizer System": "Jaguar Megamos",
    "Key Blade": "Tibbe 8-cut (Ilco S32FJ)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "ID48 (Megamos Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Supercharged",
  },
  {
    Make: "Jaguar",
    Model: "XKR (X100)",
    "Start Year": 2001,
    "End Year": 2006,
    Platform: "X100",
    "Key Type": "Metal Key",
    "Immobilizer System": "Jaguar Megamos",
    "Key Blade": "Tibbe 6-cut (FO21)",
    "Lishi Tool": "FO21 (Tibbe)",
    Transponder: "ID48 (Megamos Crypto)",
    "FCC ID": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "Supercharged",
  },
  {
    Make: "Jaguar",
    Model: "XKR (X150)",
    "Start Year": 2007,
    "End Year": 2015,
    Platform: "X150",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A / KR55WK49244",
    "KVM/RFA Location": "Passenger footwell, left side trim",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "Supercharged",
  },
];
