export const ROVER_DATA = [
  {
    Make: "Land Rover",
    Model: "Defender 110 (L663)",
    "Start Year": 2020,
    "End Year": 2026,
    Platform: "L663",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, behind left side trim",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Defender 130 (L663)",
    "Start Year": 2023,
    "End Year": 2026,
    Platform: "L663",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, behind left side trim",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Defender 90 (L663)",
    "Start Year": 2020,
    "End Year": 2026,
    Platform: "L663",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, behind left side trim",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Discovery (L462)",
    "Start Year": 2017,
    "End Year": 2018,
    Platform: "L462",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Type": "KVM (9S12)",
    "KVM Processor": "MC9S12",
    "KVM/RFA Location": "Cargo area, left side",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome side key (old style); TOPIx from 17MY",
  },
  {
    Make: "Land Rover",
    Model: "Discovery (L462)",
    "Start Year": 2019,
    "End Year": 2026,
    Platform: "L462",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, left side",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Discovery (Series I)",
    "Start Year": 1994,
    "End Year": 1995,
    Platform: "Discovery I",
    "Key Type": "Metal",
    "Immobilizer System": "Lucas 17VT (Remote)",
    "Key Blade": "RV4 (Ilco X239)",
    "Lishi Tool": "NE75 / NE38",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Type": "\u2014",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes:
      "Lucas 17VT alarm/immobilizer; single-button remote, 14CUX engine mgmt; no RFID chip in key",
  },
  {
    Make: "Land Rover",
    Model: "Discovery (Series I)",
    "Start Year": 1996,
    "End Year": 1998,
    Platform: "Discovery I",
    "Key Type": "Metal",
    "Immobilizer System": "Lucas 10AS (Remote)",
    "Key Blade": "RV4 (Ilco X239)",
    "Lishi Tool": "NE75 / NE38",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Type": "\u2014",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes:
      "Lucas 10AS alarm/immobilizer; two-button remote, GEMS engine mgmt; no RFID chip in key",
  },
  {
    Make: "Land Rover",
    Model: "Discovery Series II",
    "Start Year": 1999,
    "End Year": 2004,
    Platform: "Discovery I",
    "Key Type": "Remote Head",
    "Immobilizer System": "No RFID-Remote",
    "Key Blade": "RV4 (Ilco X239)",
    "Lishi Tool": "NE75 / NE38",
    Transponder: "\u2014",
    "FCC ID": "N5FVALTX3",
    "KVM/RFA Type": "BCU",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "7001-9000",
    Notes: "Remote signal is immobilizer; no RFID chip in key",
  },
  {
    Make: "Land Rover",
    Model: "Discovery Sport (L550)",
    "Start Year": 2015,
    "End Year": 2018,
    Platform: "L550",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Type": "KVM (9S12)",
    "KVM Processor": "MC9S12",
    "KVM/RFA Location": "Passenger footwell, behind glove box",
    "Programming System": "SDD / TOPIx",
    "Code Series": "\u2014",
    Notes:
      "Chrome side key (old style); Chrome side key (old style); TOPIx starts 18MY",
  },
  {
    Make: "Land Rover",
    Model: "Discovery Sport (L550)",
    "Start Year": 2019,
    "End Year": 2026,
    Platform: "L550",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Passenger footwell, behind glove box",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Freelander",
    "Start Year": 2002,
    "End Year": 2005,
    Platform: "Freelander (LN)",
    "Key Type": "Metal",
    "Immobilizer System": "Transponder (ID44)",
    "Key Blade": "HU92",
    "Lishi Tool": "HU92",
    Transponder: "ID44",
    "FCC ID": "\u2014",
    "KVM/RFA Type": "\u2014",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "0001-8000",
    Notes: "",
  },
  {
    Make: "Land Rover",
    Model: "LR2",
    "Start Year": 2008,
    "End Year": 2012,
    Platform: "LR2 (L359)",
    "Key Type": "Slot Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "PCF7945A",
    "FCC ID": "NT8-TX9",
    "KVM/RFA Type": "KVM (9S12)",
    "KVM Processor": "MC9S12",
    "KVM/RFA Location": "Behind glove box",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "Push-button start with key slot",
  },
  {
    Make: "Land Rover",
    Model: "LR2",
    "Start Year": 2013,
    "End Year": 2015,
    Platform: "LR2 (L359)",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Type": "KVM (9S12)",
    "KVM Processor": "MC9S12",
    "KVM/RFA Location": "Behind glove box",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "Chrome side key (old style)",
  },
  {
    Make: "Land Rover",
    Model: "LR3",
    "Start Year": 2005,
    "End Year": 2009,
    Platform: "LR3 (L319)",
    "Key Type": "Flip Key",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID46",
    "FCC ID": "NT8-15K6014CFFTXA",
    "KVM/RFA Type": "\u2014",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "Behind glove box",
    "Programming System": "\u2014",
    "Code Series": "0001-4000",
    Notes: "Ignition on steering column; Ford CEM immo",
  },
  {
    Make: "Land Rover",
    Model: "LR4",
    "Start Year": 2010,
    "End Year": 2018,
    Platform: "LR4 (L319)",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Type": "KVM (9S12)",
    "KVM Processor": "MC9S12",
    "KVM/RFA Location": "Cargo area, left side behind trim",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "Chrome side key (old style)",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover (L322)",
    "Start Year": 2003,
    "End Year": 2006,
    Platform: "L322",
    "Key Type": "Flip Key",
    "Immobilizer System": "BMW EWS",
    "Key Blade": "HU92",
    "Lishi Tool": "HU92",
    Transponder: "ID44",
    "FCC ID": "LX8FZV",
    "KVM/RFA Type": "\u2014",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "0001-8000",
    Notes:
      "Ignition in center console; BMW EWS immo box; SPLIT YEAR: Early 2006 = BMW EWS, console ignition, HU92",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover (L322)",
    "Start Year": 2006,
    "End Year": 2009,
    Platform: "L322",
    "Key Type": "Flip Key",
    "Immobilizer System": "VIM (LEAR)",
    "Key Blade": "HU92",
    "Lishi Tool": "HU92",
    Transponder: "ID46",
    "FCC ID": "NT8-15K6014CFFTXA",
    "KVM/RFA Type": "\u2014",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "0001-4000",
    Notes:
      "SPLIT YEAR: Late 2006 = VIM/LEAR immo, dash ignition, HU92, ID46; Ignition on dash; VIM/LEAR immo; HU92 blade; switchblade key from mid-2007",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover (L322)",
    "Start Year": 2010,
    "End Year": 2012,
    Platform: "L322",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Type": "KVM (9S12)",
    "KVM Processor": "MC9S12",
    "KVM/RFA Location": "Cargo area, left side behind trim",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "Chrome side key (old style)",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover (L405)",
    "Start Year": 2013,
    "End Year": 2016,
    Platform: "L405",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Type": "KVM (9S12)",
    "KVM Processor": "MC9S12",
    "KVM/RFA Location": "Cargo area, left side under fuse box",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "Chrome side key (old style)",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover (L405)",
    "Start Year": 2017,
    "End Year": 2022,
    Platform: "L405",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, left side under fuse box",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover (L460)",
    "Start Year": 2022,
    "End Year": 2026,
    Platform: "L460",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, left side",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover (P38)",
    "Start Year": 1995,
    "End Year": 2002,
    Platform: "P38A",
    "Key Type": "Flip Key",
    "Immobilizer System": "BECM (Remote)",
    "Key Blade": "HU39 (4-Track)",
    "Lishi Tool": "NE75 / NE38",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Type": "BECM",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes:
      "Flip key with integrated remote; remote signal is immobilizer; no RFID chip in key blade",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Classic",
    "Start Year": 1987,
    "End Year": 1993,
    Platform: "Classic",
    "Key Type": "Metal",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "HU39 (4-Track)",
    "Lishi Tool": "NE75 / NE38",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Type": "\u2014",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes: "",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Classic",
    "Start Year": 1994,
    "End Year": 1995,
    Platform: "Classic",
    "Key Type": "Metal",
    "Immobilizer System": "Lucas 17VT (Remote)",
    "Key Blade": "HU39 (4-Track)",
    "Lishi Tool": "NE75 / NE38",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "KVM/RFA Type": "\u2014",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "\u2014",
    Notes:
      "Lucas 17VT alarm/immobilizer; single-button remote fob; no RFID chip in key",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Evoque (L538)",
    "Start Year": 2012,
    "End Year": 2016,
    Platform: "L538",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Type": "KVM (9S12)",
    "KVM Processor": "MC9S12",
    "KVM/RFA Location": "Cargo area, left side under fuse box",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "Chrome side key (old style)",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Evoque (L538)",
    "Start Year": 2017,
    "End Year": 2019,
    Platform: "L538",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, left side under fuse box",
    "Programming System": "SDD / TOPIx",
    "Code Series": "\u2014",
    Notes:
      "Chrome bottom key (new style); RFA module; last SDD year; Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Evoque (L551)",
    "Start Year": 2020,
    "End Year": 2026,
    Platform: "L551",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, left side under fuse box",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Sport (L320)",
    "Start Year": 2006,
    "End Year": 2009,
    Platform: "L320",
    "Key Type": "Flip Key",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID46",
    "FCC ID": "NT8-15K6014CFFTXA",
    "KVM/RFA Type": "\u2014",
    "KVM Processor": "\u2014",
    "KVM/RFA Location": "Behind glove box",
    "Programming System": "\u2014",
    "Code Series": "0001-4000",
    Notes: "Ignition on steering column; Ford CEM immo",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Sport (L320)",
    "Start Year": 2010,
    "End Year": 2013,
    Platform: "L320",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Type": "KVM (9S12)",
    "KVM Processor": "MC9S12",
    "KVM/RFA Location": "Behind glove box",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "Chrome side key (old style)",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Sport (L461)",
    "Start Year": 2023,
    "End Year": 2026,
    Platform: "L461",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, left side",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Sport (L494)",
    "Start Year": 2014,
    "End Year": 2016,
    Platform: "L494",
    "Key Type": "Smart Key",
    "Immobilizer System": "KVM",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJTF10A",
    "KVM/RFA Type": "KVM (9S12)",
    "KVM Processor": "MC9S12",
    "KVM/RFA Location": "Cargo area, left side under fuse box",
    "Programming System": "SDD",
    "Code Series": "\u2014",
    Notes: "Chrome side key (old style)",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Sport (L494)",
    "Start Year": 2017,
    "End Year": 2022,
    Platform: "L494",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, left side under fuse box",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
  {
    Make: "Land Rover",
    Model: "Range Rover Velar (L560)",
    "Start Year": 2018,
    "End Year": 2026,
    Platform: "L560",
    "Key Type": "Smart Key",
    "Immobilizer System": "RFA",
    "Key Blade": "HU101",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "KOBJXF18A",
    "KVM/RFA Type": "RFA (ST)",
    "KVM Processor": "SPC560B",
    "KVM/RFA Location": "Cargo area, right side under fuse box",
    "Programming System": "TOPIx",
    "Code Series": "\u2014",
    Notes: "Chrome bottom key (new style); RFA module",
  },
];
