export const SAAB_DATA = [
  {
    Make: "Saab",
    Model: "900 (Classic)",
    "Start Year": 1986,
    "End Year": 1993,
    "Key Blank": "S32YS-P",
    "Blade/Keyway": "Saab profile",
    "Lishi Tool": "NE34",
    "Transponder Chip": "None",
    "FCC ID": "N/A",
    "Key Type": "Standard Ignition",
    "Immo System": "No Immobilizer",
    Platform: "Saab Classic",
    Proximity: "No",
    "RKE Frequency": "N/A",
    "Code Series": "N/A",
    Notes: "Pre-TWICE. No transponder. Mechanical key only.",
  },
  {
    Make: "Saab",
    Model: "9000",
    "Start Year": 1986,
    "End Year": 1993,
    "Key Blank": "S32YS-P",
    "Blade/Keyway": "Saab profile",
    "Lishi Tool": "NE34",
    "Transponder Chip": "None",
    "FCC ID": "N/A",
    "Key Type": "Standard Ignition",
    "Immo System": "No Immobilizer",
    Platform: "Type Four",
    Proximity: "No",
    "RKE Frequency": "N/A",
    "Code Series": "N/A",
    Notes: "Pre-TWICE. No transponder. Mechanical key only.",
  },
  {
    Make: "Saab",
    Model: "9000",
    "Start Year": 1994,
    "End Year": 1998,
    "Key Blank": "S32YS-P",
    "Blade/Keyway": "Saab profile",
    "Lishi Tool": "NE34",
    "Transponder Chip": "None",
    "FCC ID": "N/A",
    "Key Type": "Standard Ignition",
    "Immo System": "TWICE",
    Platform: "Type Four",
    Proximity: "No",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "TWICE module under driver seat. No chip in key. Separate banana remote for locks/alarm. Tech2 required to add keys. Max 4 keys.",
  },
  {
    Make: "Saab",
    Model: "900 (NG)",
    "Start Year": 1994,
    "End Year": 1998,
    "Key Blank": "S32YS-P",
    "Blade/Keyway": "Saab profile",
    "Lishi Tool": "NE34",
    "Transponder Chip": "None",
    "FCC ID": "N/A",
    "Key Type": "Standard Ignition",
    "Immo System": "TWICE",
    Platform: "GM2900",
    Proximity: "No",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "TWICE module under driver seat. No chip in key. Separate banana remote for locks/alarm. Tech2 required to add keys. Max 4 keys.",
  },
  {
    Make: "Saab",
    Model: "9-3 (OG)",
    "Start Year": 1999,
    "End Year": 2002,
    "Key Blank": "S32YS-P",
    "Blade/Keyway": "Saab profile",
    "Lishi Tool": "NE34",
    "Transponder Chip": "Saab fixed code",
    "FCC ID": "N/A",
    "Key Type": "Transponder",
    "Immo System": "TWICE",
    Platform: "GM2900",
    Proximity: "No",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "TWICE module under driver seat. Transponder integrated in key head. Tech2 to add keys. 1999 first year w/ transponder on 9-3.",
  },
  {
    Make: "Saab",
    Model: "9-3 (OG)",
    "Start Year": 2003,
    "End Year": 2003,
    "Key Blank": "S32YS-P",
    "Blade/Keyway": "Saab profile",
    "Lishi Tool": "NE34",
    "Transponder Chip": "Saab fixed code",
    "FCC ID": "N/A",
    "Key Type": "Transponder",
    "Immo System": "TWICE",
    Platform: "GM2900",
    Proximity: "No",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "Last year OG 9-3 (convertible only). TWICE under seat. Separate from 2003+ Sport Sedan which uses CIM.",
  },
  {
    Make: "Saab",
    Model: "9-3 (Sport Sedan)",
    "Start Year": 2003,
    "End Year": 2007,
    "Key Blank": "12799334",
    "Blade/Keyway": "WT4 (fob insert)",
    "Lishi Tool": "WT4",
    "Transponder Chip": "ID46 (PCF7946)",
    "FCC ID": "N/A",
    "Key Type": "Fob w/ key insert",
    "Immo System": "CIM",
    Platform: "Epsilon",
    Proximity: "No",
    "RKE Frequency": "433 MHz",
    "Code Series": "N/A",
    Notes:
      "CIM (Column Integration Module) in steering column. Fob inserts into ISM slot. ID46/PCF7946 transponder. Tech2 or CIM mail-in to program. Max 5 keys.",
  },
  {
    Make: "Saab",
    Model: "9-3 (Sport Sedan/Wagon)",
    "Start Year": 2008,
    "End Year": 2011,
    "Key Blank": "93166902",
    "Blade/Keyway": "HU100 (fob insert)",
    "Lishi Tool": "HU100",
    "Transponder Chip": "ID46 (PCF7946)",
    "FCC ID": "N/A",
    "Key Type": "Fob w/ key insert",
    "Immo System": "CIM",
    Platform: "Epsilon",
    Proximity: "No",
    "RKE Frequency": "433 MHz",
    "Code Series": "N/A",
    Notes:
      "CIM in steering column. HU100 key insert (change from WT4). Same CIM system, same ID46/PCF7946 chip. Tech2 or CIM mail-in.",
  },
  {
    Make: "Saab",
    Model: "9-3 Convertible",
    "Start Year": 2004,
    "End Year": 2011,
    "Key Blank": "12799334",
    "Blade/Keyway": "WT4 (fob insert)",
    "Lishi Tool": "WT4",
    "Transponder Chip": "ID46 (PCF7946)",
    "FCC ID": "N/A",
    "Key Type": "Fob w/ key insert",
    "Immo System": "CIM",
    Platform: "Epsilon",
    Proximity: "No",
    "RKE Frequency": "433 MHz",
    "Code Series": "N/A",
    Notes:
      "CIM system. Convertible uses DA-series key (WT4 insert) throughout entire run, does NOT switch to HU100 like sedan/wagon.",
  },
  {
    Make: "Saab",
    Model: "9-5",
    "Start Year": 1999,
    "End Year": 2002,
    "Key Blank": "S32YS-P / 5111646",
    "Blade/Keyway": "Saab profile",
    "Lishi Tool": "NE34",
    "Transponder Chip": "Saab fixed code",
    "FCC ID": "N/A",
    "Key Type": "Transponder",
    "Immo System": "TWICE",
    Platform: "GM2900",
    Proximity: "No",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "TWICE module under driver seat. Transponder in key head. 1999 9-5 early VINs use different key blank than late VINs. Tech2 to add keys.",
  },
  {
    Make: "Saab",
    Model: "9-5",
    "Start Year": 2003,
    "End Year": 2009,
    "Key Blank": "32018042",
    "Blade/Keyway": "Saab profile",
    "Lishi Tool": "NE34",
    "Transponder Chip": "Saab fixed code",
    "FCC ID": "N/A",
    "Key Type": "Transponder",
    "Immo System": "TWICE",
    Platform: "GM2900",
    Proximity: "No",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "TWICE module under driver seat. Key blade w/ transponder + separate remote transmitter. Tech2 required to add keys.",
  },
  {
    Make: "Saab",
    Model: "9-5 (2nd gen)",
    "Start Year": 2010,
    "End Year": 2011,
    "Key Blank": "20765513",
    "Blade/Keyway": "HU100 (fob insert)",
    "Lishi Tool": "HU100",
    "Transponder Chip": "ID46 (PCF7946)",
    "FCC ID": "N/A",
    "Key Type": "Fob w/ key insert",
    "Immo System": "CIM",
    Platform: "Epsilon II",
    Proximity: "No",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "2nd gen 9-5 on Epsilon II (Buick LaCrosse/Opel Insignia platform). CIM system. HU100 insert. Same key blank as 9-4X.",
  },
  {
    Make: "Saab",
    Model: "9-2X",
    "Start Year": 2005,
    "End Year": 2005,
    "Key Blank": "32007556",
    "Blade/Keyway": "NSN14",
    "Lishi Tool": "NSN14",
    "Transponder Chip": "None",
    "FCC ID": "N/A",
    "Key Type": "Standard Ignition",
    "Immo System": "No Immobilizer",
    Platform: "Subaru GD",
    Proximity: "No",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "Rebadged Subaru Impreza/WRX. NSN14 keyway. No transponder chip. Plain metal key + separate remote.",
  },
  {
    Make: "Saab",
    Model: "9-2X Aero",
    "Start Year": 2006,
    "End Year": 2006,
    "Key Blank": "32010398",
    "Blade/Keyway": "NSN14",
    "Lishi Tool": "NSN14",
    "Transponder Chip": "4D60",
    "FCC ID": "N/A",
    "Key Type": "Transponder",
    "Immo System": "Subaru immobilizer",
    Platform: "Subaru GD",
    Proximity: "No",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "Rebadged Subaru Impreza WRX. NSN14 keyway. 4D60 transponder (Subaru system). 2006 Aero only — Linear model may NOT have transponder.",
  },
  {
    Make: "Saab",
    Model: "9-7X",
    "Start Year": 2005,
    "End Year": 2009,
    "Key Blank": "B107-PT (ID13)",
    "Blade/Keyway": "GM39 (10-cut)",
    "Lishi Tool": "GM39",
    "Transponder Chip": "ID13 (PK3)",
    "FCC ID": "N/A",
    "Key Type": "Transponder",
    "Immo System": "PK3 (GM)",
    Platform: "GMT360",
    Proximity: "No",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "Rebadged Chevy Trailblazer on GMT360. GM39 keyway, Bonneville ignition lock. B107-PT04 closest GM equivalent. OEM was clunky remote-head key (integrated Trailblazer remote + chip key), hard to find — usually substitute separate key + remote. Same key as 04-08 Grand Prix.",
  },
  {
    Make: "Saab",
    Model: "9-4X",
    "Start Year": 2011,
    "End Year": 2011,
    "Key Blank": "20765513",
    "Blade/Keyway": "HU100 (fob insert)",
    "Lishi Tool": "HU100",
    "Transponder Chip": "ID46 (PCF7946)",
    "FCC ID": "N/A",
    "Key Type": "Fob w/ key insert",
    "Immo System": "CIM",
    Platform: "Theta Premium",
    Proximity: "Yes",
    "RKE Frequency": "315 MHz",
    "Code Series": "N/A",
    Notes:
      "Rebadged Cadillac SRX. Theta Premium platform. HU100 key insert, CIM system. ~803 produced. Extremely rare.",
  },
];
