// src/database/subaru.js

export const SUBARU_DATA = [
  {
    Make: "Subaru",
    Model: "ALL EARLY MODELS 85-94 (DL/GL/Loyale/XT/Justy/Legacy/Impreza)",
    "Start Year": 1985,
    "End Year": 1994,
    Chassis: "Various",
    "Key Blank": "DA25",
    "Lishi Tool": "NSN11",
    "Code Series": "X8001-X9000",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "N/A",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes:
      "No immobilizer. All pre-95 models use DA25/X8001-X9000. Some models (Impreza, Legacy, Outback, SVX) continued on DA25 past 1994 — see individual model rows.",
  },
  {
    Make: "Subaru",
    Model: "Ascent (Keyed)",
    "Start Year": 2019,
    "End Year": 2023,
    Chassis: "WM",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (8A/AES)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G077 (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "CWTB1G077 gray pod. H chip, 433MHz remote.",
  },
  {
    Make: "Subaru",
    Model: "Ascent (Keyed)",
    "Start Year": 2024,
    "End Year": 2025,
    Chassis: "WM",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (AES WS21)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G496 (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites / Smart Pro / Autel",
    AKL: "Abrites",
    Notes: "New FCC ID. 434MHz. CR2025 battery.",
  },
  {
    Make: "Subaru",
    Model: "Ascent (Smart Key)",
    "Start Year": 2019,
    "End Year": 2025,
    Chassis: "WM",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "H (8A)",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHK (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites / Smart Pro / Autel",
    AKL: "Abrites",
    Notes:
      "Autel/Smart pro may work for AKL through about 2021-22. Unverified.",
  },
  {
    Make: "Subaru",
    Model: "BRZ (Keyed)",
    "Start Year": 2013,
    "End Year": 2020,
    Chassis: "ZC",
    "Key Blank": "TR47",
    "Lishi Tool": "TOY43",
    "Code Series": "50000-69999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "Yes",
    "FCC ID": "HYQ12BBY (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes:
      "Toyota 86 platform. Uses TR47 keyway (not B110). Code series 50000-69999 (Toyota series). G chip is cloneable.",
  },
  {
    Make: "Subaru",
    Model: "BRZ (Smart Key)",
    "Start Year": 2022,
    "End Year": 2025,
    Chassis: "ZD",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "8A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AKB (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites",
    AKL: "Abrites",
    Notes:
      "Gen 2 BRZ - now smart key only (no more keyed ign). Toyota GR86 twin.",
  },
  {
    Make: "Subaru",
    Model: "BRZ (Smart Key)",
    "Start Year": 2013,
    "End Year": 2013,
    Chassis: "ZC",
    "Key Blank": "TOY48 (modified)",
    "Lishi Tool": "TOY48",
    "Code Series": "40000-49999",
    "Transponder Chip": "TBD",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14ACX (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes:
      "2013 BRZ Limited w/ push-button start. GNE board (271451-5290). P/N 88835-SG040 / 88835-CA060. Emergency blade TOY48 modified. Code series 40000-49999 (Toyota/Denso prox).",
  },
  {
    Make: "Subaru",
    Model: "BRZ (Smart Key)",
    "Start Year": 2014,
    "End Year": 2020,
    Chassis: "ZC",
    "Key Blank": "LXP90 thin (emergency)",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHC (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes:
      "2014-2020 BRZ w/ push-button start. Same HYQ14AHC smart key as Legacy/Outback/Crosstrek/Forester/WRX/STI. P/N 88835-AL04B. Emergency blade LXP90 thin (57497AL020). Code series 90000-94999 (same as all HYQ14AHC smart keys). Aftermarket may show FCC 2AOKM-SB5.",
  },
  {
    Make: "Subaru",
    Model: "Baja",
    "Start Year": 2003,
    "End Year": 2006,
    Chassis: "BT",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "None",
    "Cloneable?": "N/A",
    "FCC ID": "A269ZUA111 (433MHz)",
    "RKE Prog": "OBP",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes:
      "No immobilizer. Used BH Legacy/Outback parts bin including remotes. OBP key-cycle programming (no code word).",
  },
  {
    Make: "Subaru",
    Model: "Crosstrek (XV) (Keyed)",
    "Start Year": 2013,
    "End Year": 2015,
    Chassis: "GP",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "No",
    "FCC ID": "CWTWB1U811 (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "Originally named XV Crosstrek through 2015. Remote head key.",
  },
  {
    Make: "Subaru",
    Model: "Crosstrek (Keyed)",
    "Start Year": 2016,
    "End Year": 2017,
    Chassis: "GP",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "No",
    "FCC ID": "CWTWB1U811 (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "Name change from XV Crosstrek.",
  },
  {
    Make: "Subaru",
    Model: "Crosstrek (XV) (Smart Key)",
    "Start Year": 2013,
    "End Year": 2015,
    Chassis: "GP",
    "Key Blank": "TOY48 (modified)",
    "Lishi Tool": "TOY48",
    "Code Series": "77000-78569",
    "Transponder Chip": "TBD",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14ACX",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes:
      "Originally named XV Crosstrek through 2015. Same as Impreza smart key.",
  },
  {
    Make: "Subaru",
    Model: "Crosstrek (Smart Key)",
    "Start Year": 2016,
    "End Year": 2017,
    Chassis: "GP",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHC",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Crosstrek (Keyed)",
    "Start Year": 2018,
    "End Year": 2023,
    Chassis: "GT",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (8A/AES)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G077 (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "CWTB1G077 black pod (no sticker). H chip, 433MHz remote.",
  },
  {
    Make: "Subaru",
    Model: "Crosstrek (Smart Key)",
    "Start Year": 2018,
    "End Year": 2023,
    Chassis: "GT",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "H (8A)",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHK (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Crosstrek (Keyed)",
    "Start Year": 2024,
    "End Year": 2024,
    Chassis: "GU",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (AES WS21)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G496 (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites / Smart Pro / Autel",
    AKL: "Abrites",
    Notes: "New FCC ID. 434MHz. CR2025 battery.",
  },
  {
    Make: "Subaru",
    Model: "Crosstrek (Smart Key)",
    "Start Year": 2024,
    "End Year": 2025,
    Chassis: "GU",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "8A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AKB (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites",
    AKL: "Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Forester",
    "Start Year": 1998,
    "End Year": 2002,
    Chassis: "SF",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "OBP",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes: "No immobilizer.",
  },
  {
    Make: "Subaru",
    Model: "Forester",
    "Start Year": 2003,
    "End Year": 2008,
    Chassis: "SG",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62",
    "Cloneable?": "Yes",
    "FCC ID": "A269ZUA111 (03-04) / NHVWB1U711 (05-08)",
    "RKE Prog": "OBP / OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "2003 non-immo. 2004-07 immo on XT only. 2008 immo on XT/XT Sports only (not X/Premium/LL Bean). Still old key style thru 2008. Dealer SSM can AKL. RKE: OBP (03-05) / OBP+Code (06-08 w/ 8-digit code per cars101).",
  },
  {
    Make: "Subaru",
    Model: "Forester",
    "Start Year": 2009,
    "End Year": 2013,
    Chassis: "SH",
    "Key Blank": "DAT17",
    "Lishi Tool": "DAT17",
    "Code Series": "T0001-T3000",
    "Transponder Chip": "4D62 pwFF",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWB1U819",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes: "Dealer SSM can do AKL on these models.",
  },
  {
    Make: "Subaru",
    Model: "Forester (Keyed)",
    "Start Year": 2014,
    "End Year": 2018,
    Chassis: "SJ",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "No",
    "FCC ID": "CWTWB1U811 (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "Remote head key.",
  },
  {
    Make: "Subaru",
    Model: "Forester (Keyed)",
    "Start Year": 2019,
    "End Year": 2022,
    Chassis: "SK",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (8A/AES)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G077 (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "CWTB1G077 gray pod. H chip, 433MHz remote.",
  },
  {
    Make: "Subaru",
    Model: "Forester (Smart Key)",
    "Start Year": 2019,
    "End Year": 2024,
    Chassis: "SK",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "H (8A)",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHK (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Forester (Smart Key)",
    "Start Year": 2025,
    "End Year": 2025,
    Chassis: "SK",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "8A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AKB (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites",
    AKL: "Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Impreza",
    "Start Year": 1995,
    "End Year": 2001,
    Chassis: "GC/GF",
    "Key Blank": "DA25",
    "Lishi Tool": "NSN11",
    "Code Series": "X8001-X9000",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "N/A",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes: "DA25 through end of GC chassis (2001). No immobilizer.",
  },
  {
    Make: "Subaru",
    Model: "Impreza",
    "Start Year": 2002,
    "End Year": 2004,
    Chassis: "GD/GG",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "N/A",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes:
      "Switched to DA34 with GD chassis change in 2002. No immobilizer. Immo added 2005.",
  },
  {
    Make: "Subaru",
    Model: "Impreza",
    "Start Year": 2005,
    "End Year": 2005,
    Chassis: "GD/GG",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "NHVWB1U711 (433MHz)",
    "RKE Prog": "OBP",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes:
      "No immobilizer on base Impreza or Outback Sport. 2005 STI only had immo.",
  },
  {
    Make: "Subaru",
    Model: "Impreza",
    "Start Year": 2006,
    "End Year": 2007,
    Chassis: "GD/GG",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62",
    "Cloneable?": "Yes",
    "FCC ID": "NHVWB1U711 (433MHz)",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "Immo standard on WRX/STI. Base Impreza per cars101: immo not standard on all until 2008. Dealer SSM can AKL.",
  },
  {
    Make: "Subaru",
    Model: "Impreza",
    "Start Year": 2008,
    "End Year": 2011,
    Chassis: "GE/GH",
    "Key Blank": "DAT17",
    "Lishi Tool": "DAT17",
    "Code Series": "T0001-T3000",
    "Transponder Chip": "4D62 pwFF",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWB1U819",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "All 2008+ Imprezas have immobilizer. DAT17 laser cut key new for 2008.",
  },
  {
    Make: "Subaru",
    Model: "Impreza (Keyed)",
    "Start Year": 2012,
    "End Year": 2016,
    Chassis: "GJ/GP",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "No",
    "FCC ID": "CWTWB1U811 (315MHz)",
    "RKE Prog": "OBP+Code",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "2012 new GJ/GP body went straight to TOY43R. Remote head key.",
  },
  {
    Make: "Subaru",
    Model: "Impreza (Smart Key)",
    "Start Year": 2013,
    "End Year": 2015,
    Chassis: "GJ/GP",
    "Key Blank": "TOY48 (modified)",
    "Lishi Tool": "TOY48",
    "Code Series": "77000-78569",
    "Transponder Chip": "TBD",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14ACX",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes:
      "Modified TOY48 insert: 5 cuts track A, 4 cuts track B (5th empty). Smart key visually = Toyota/Lexus (board 5290) but NOT cross-compatible.",
  },
  {
    Make: "Subaru",
    Model: "Impreza (Smart Key)",
    "Start Year": 2016,
    "End Year": 2016,
    Chassis: "GJ/GP",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHC",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Impreza (Keyed)",
    "Start Year": 2017,
    "End Year": 2022,
    Chassis: "GK/GT",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (8A/AES)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G077 (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "CWTB1G077 black pod (no sticker). H chip, 433MHz remote.",
  },
  {
    Make: "Subaru",
    Model: "Impreza (Keyed)",
    "Start Year": 2023,
    "End Year": 2024,
    Chassis: "GK/GT",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (AES WS21)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G496 (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites / Smart Pro / Autel",
    AKL: "Abrites",
    Notes: "New FCC ID. 434MHz. CR2025 battery.",
  },
  {
    Make: "Subaru",
    Model: "Impreza (Smart Key)",
    "Start Year": 2017,
    "End Year": 2022,
    Chassis: "GK/GT",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "H (8A)",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHK (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Impreza (Smart Key)",
    "Start Year": 2023,
    "End Year": 2025,
    Chassis: "GK/GT",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "8A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AKB (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites",
    AKL: "Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Impreza Outback Sport",
    "Start Year": 1997,
    "End Year": 2001,
    Chassis: "GC/GF",
    "Key Blank": "DA25",
    "Lishi Tool": "NSN11",
    "Code Series": "X8001-X9000",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "OBP",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes: "Impreza trim. DA25 through 2001 (GC chassis). No immobilizer.",
  },
  {
    Make: "Subaru",
    Model: "Impreza Outback Sport",
    "Start Year": 2002,
    "End Year": 2004,
    Chassis: "GD/GG",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "OBP",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes:
      "Impreza trim. Switched to DA34 with GD chassis in 2002. No immobilizer.",
  },
  {
    Make: "Subaru",
    Model: "Impreza Outback Sport",
    "Start Year": 2005,
    "End Year": 2005,
    Chassis: "GD/GG",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "NHVWB1U711 (433MHz)",
    "RKE Prog": "OBP",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes: "Impreza trim. No immobilizer.",
  },
  {
    Make: "Subaru",
    Model: "Impreza Outback Sport",
    "Start Year": 2006,
    "End Year": 2007,
    Chassis: "GD/GG",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62",
    "Cloneable?": "Yes",
    "FCC ID": "NHVWB1U711 (433MHz)",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "Impreza trim. Immobilizer standard. Dealer SSM can do AKL on these models.",
  },
  {
    Make: "Subaru",
    Model: "Impreza Outback Sport",
    "Start Year": 2008,
    "End Year": 2011,
    Chassis: "GE/GH",
    "Key Blank": "DAT17",
    "Lishi Tool": "DAT17",
    "Code Series": "T0001-T3000",
    "Transponder Chip": "4D62 pwFF",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWB1U819",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "Impreza trim. Last year was 2011. Replaced by XV Crosstrek in 2013. Dealer SSM can do AKL on these models.",
  },
  {
    Make: "Subaru",
    Model: "Legacy (incl. Legacy Outback)",
    "Start Year": 1995,
    "End Year": 1999,
    Chassis: "BD/BG",
    "Key Blank": "DA25",
    "Lishi Tool": "NSN11",
    "Code Series": "X8001-X9000",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "N/A",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes:
      "No immobilizer. DA25 keyway through 1999. Includes Legacy Outback (1995-1999) which was a Legacy trim/package before Outback became its own model line in 2000.",
  },
  {
    Make: "Subaru",
    Model: "Legacy",
    "Start Year": 2000,
    "End Year": 2004,
    Chassis: "BE/BH",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "N/A",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes: "No immobilizer. Switched from DA25 to DA34 in 2000.",
  },
  {
    Make: "Subaru",
    Model: "Legacy",
    "Start Year": 2005,
    "End Year": 2006,
    Chassis: "BL/BP",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62 on equipped trims",
    "Cloneable?": "Yes (if equipped)",
    "FCC ID": "NHVWB1U711 (433MHz)",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone) if equipped",
    AKL: "All (clone) if equipped",
    Notes:
      "Immo on GT only. Base Legacy no immobilizer. Per cars101. Code word programming started 2005 on Legacy/Outback per cars101.",
  },
  {
    Make: "Subaru",
    Model: "Legacy",
    "Start Year": 2007,
    "End Year": 2009,
    Chassis: "BL/BP",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWBU766 (433MHz)",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes: "Immo standard all models 2007+. Dealer SSM can AKL.",
  },
  {
    Make: "Subaru",
    Model: "Legacy",
    "Start Year": 2010,
    "End Year": 2014,
    Chassis: "BM/BR",
    "Key Blank": "DAT17",
    "Lishi Tool": "DAT17",
    "Code Series": "T0001-T3000",
    "Transponder Chip": "4D62 pw17",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWBU766 (433) or CWTWB1U811 (315)",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "Pin code required for add/clear keys. Most aftermarket tools read pin from car. Dealer can supply from VIN.",
  },
  {
    Make: "Subaru",
    Model: "Legacy (Keyed)",
    "Start Year": 2015,
    "End Year": 2017,
    Chassis: "BN/BS",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "No",
    "FCC ID": "CWTWB1U811 (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "Remote head key.",
  },
  {
    Make: "Subaru",
    Model: "Legacy (Keyed)",
    "Start Year": 2018,
    "End Year": 2019,
    Chassis: "BN/BS",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G077 (433MHz) G-chip",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel",
    AKL: "BIU Eeprom ONLY",
    Notes:
      "CWTB1G077 black pod, G chip outlier (433MHz). AKL requires BIU eeprom. OUTLIER: G chip but new FCC. AKL = BIU removal + eeprom only.",
  },
  {
    Make: "Subaru",
    Model: "Legacy (Smart Key)",
    "Start Year": 2015,
    "End Year": 2017,
    Chassis: "BN/BS",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHC",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Legacy (Smart Key)",
    "Start Year": 2018,
    "End Year": 2022,
    Chassis: "BN/BS",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "H (8A)",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHK (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Legacy (Keyed)",
    "Start Year": 2020,
    "End Year": 2022,
    Chassis: "BT/BW",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (8A/AES)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G077 (433MHz) blue pod",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "CWTB1G077 blue pod. H chip. Blue interior pod. Verify PN.",
  },
  {
    Make: "Subaru",
    Model: "Legacy (Keyed)",
    "Start Year": 2023,
    "End Year": 2024,
    Chassis: "BT/BW",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (AES WS21)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G496 (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites / Smart Pro / Autel",
    AKL: "Abrites",
    Notes:
      "New FCC ID. 434MHz. CR2025 battery. Legacy discontinued after 2024.",
  },
  {
    Make: "Subaru",
    Model: "Legacy (Smart Key)",
    "Start Year": 2023,
    "End Year": 2024,
    Chassis: "BT/BW",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "8A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AKB (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites",
    AKL: "Abrites",
    Notes: "Legacy discontinued after 2024.",
  },
  {
    Make: "Subaru",
    Model: "Outback",
    "Start Year": 1995,
    "End Year": 1999,
    Chassis: "BG",
    "Key Blank": "DA25",
    "Lishi Tool": "NSN11",
    "Code Series": "X8001-X9000",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "N/A",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes: "No immobilizer. DA25 keyway through 1999.",
  },
  {
    Make: "Subaru",
    Model: "Outback",
    "Start Year": 2000,
    "End Year": 2004,
    Chassis: "BH",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "N/A",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes: "No immobilizer. Switched from DA25 to DA34 in 2000.",
  },
  {
    Make: "Subaru",
    Model: "Outback",
    "Start Year": 2005,
    "End Year": 2006,
    Chassis: "BP",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62 on equipped trims",
    "Cloneable?": "Yes (if equipped)",
    "FCC ID": "NHVWB1U711 (433MHz)",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone) if equipped",
    AKL: "All (clone) if equipped",
    Notes:
      "Immo on XT/LL Bean/VDC/3.0R trims only. Base Outback no immobilizer. Per cars101. Code word programming started 2005 on Legacy/Outback per cars101.",
  },
  {
    Make: "Subaru",
    Model: "Outback",
    "Start Year": 2007,
    "End Year": 2009,
    Chassis: "BP",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWBU766 (433MHz)",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "Immo standard all models 2007+ (Outback Basic added 2008). Dealer SSM can AKL.",
  },
  {
    Make: "Subaru",
    Model: "Outback",
    "Start Year": 2010,
    "End Year": 2014,
    Chassis: "BR",
    "Key Blank": "DAT17",
    "Lishi Tool": "DAT17",
    "Code Series": "T0001-T3000",
    "Transponder Chip": "4D62 pw17",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWBU766 (433) or CWTWB1U811 (315)",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "Pin code required for add/clear keys. Most aftermarket tools read pin from car. Dealer can supply from VIN.",
  },
  {
    Make: "Subaru",
    Model: "Outback (Smart Key)",
    "Start Year": 2013,
    "End Year": 2014,
    Chassis: "BR",
    "Key Blank": "DAT17",
    "Lishi Tool": "DAT17",
    "Code Series": "T0001-T3000",
    "Transponder Chip": "4D62 pw17",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AGX (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes:
      "First Subaru smart key. Emergency key is DAT17 - ONLY Subaru where smart key emergency blade = keyed ign key.",
  },
  {
    Make: "Subaru",
    Model: "Outback (Keyed)",
    "Start Year": 2015,
    "End Year": 2017,
    Chassis: "BS",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "No",
    "FCC ID": "CWTWB1U811 (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "Remote head key.",
  },
  {
    Make: "Subaru",
    Model: "Outback (Keyed)",
    "Start Year": 2018,
    "End Year": 2019,
    Chassis: "BS",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G077 (433MHz) G-chip",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel",
    AKL: "BIU Eeprom ONLY",
    Notes:
      "CWTB1G077 black pod, G chip outlier (433MHz). AKL requires BIU eeprom. OUTLIER: G chip but new FCC. AKL = BIU removal + eeprom only.",
  },
  {
    Make: "Subaru",
    Model: "Outback (Smart Key)",
    "Start Year": 2015,
    "End Year": 2019,
    Chassis: "BS",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHC",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "Half-thickness Lexus 4-track insert (Toyota 2-track).",
  },
  {
    Make: "Subaru",
    Model: "Outback (Smart Key)",
    "Start Year": 2018,
    "End Year": 2023,
    Chassis: "BS",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "H (8A)",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHK (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "Outback (Keyed)",
    "Start Year": 2020,
    "End Year": 2023,
    Chassis: "BW",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (8A/AES)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G077 (433MHz) blue pod",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: "CWTB1G077 blue pod. H chip. Blue interior pod. Verify PN.",
  },
  {
    Make: "Subaru",
    Model: "Outback (Keyed)",
    "Start Year": 2024,
    "End Year": 2025,
    Chassis: "BW",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (AES WS21)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G496 (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites / Smart Pro / Autel",
    AKL: "Abrites",
    Notes: "New FCC ID. 434MHz. CR2025 battery (changed from CR1620).",
  },
  {
    Make: "Subaru",
    Model: "Outback (Smart Key)",
    "Start Year": 2024,
    "End Year": 2025,
    Chassis: "BW",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "8A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AKB (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites",
    AKL: "Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "STI",
    "Start Year": 2004,
    "End Year": 2004,
    Chassis: "GD",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "None",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "OBP",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes:
      "First year STI in US. No immobilizer, no remote. DA34 keyway on GD chassis.",
  },
  {
    Make: "Subaru",
    Model: "STI",
    "Start Year": 2005,
    "End Year": 2007,
    Chassis: "GD",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62",
    "Cloneable?": "Yes",
    "FCC ID": "NHVWB1U711 (433MHz)",
    "RKE Prog": "OBP+Code",
    "Add Key": "Dealer SSM / Smart Pro",
    AKL: "Dealer SSM / Smart Pro",
    Notes:
      "Immo standard on STI from 2005. RKE: OBP+Code (8-digit code). Dealer SSM can AKL.",
  },
  {
    Make: "Subaru",
    Model: "STI",
    "Start Year": 2008,
    "End Year": 2014,
    Chassis: "GR/GV",
    "Key Blank": "DAT17",
    "Lishi Tool": "DAT17",
    "Code Series": "T0001-T3000",
    "Transponder Chip": "4D62 pwFF",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWB1U811",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "STI stayed on DAT17 longer than other Impreza-chassis models. Dealer SSM can do AKL on these models.",
  },
  {
    Make: "Subaru",
    Model: "STI (Keyed)",
    "Start Year": 2015,
    "End Year": 2021,
    Chassis: "VA",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "No",
    "FCC ID": "CWTWB1U811 (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes:
      "STI becomes own model on VA platform (no longer Impreza). G chip CWTWB1U811 entire run. Last STI was 2021. 2019+ may require eeprom for AKL.",
  },
  {
    Make: "Subaru",
    Model: "STI (Smart Key)",
    "Start Year": 2019,
    "End Year": 2021,
    Chassis: "VA",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "H (8A)",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHK (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "SVX",
    "Start Year": 1992,
    "End Year": 1997,
    Chassis: "CX",
    "Key Blank": "DA25",
    "Lishi Tool": "NSN11",
    "Code Series": "X8001-X9000",
    "Transponder Chip": "None",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "N/A",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes: "Flat-6 coupe. DA25 keyway. No immobilizer, no remote.",
  },
  {
    Make: "Subaru",
    Model: "Solterra (Smart Key)",
    "Start Year": 2023,
    "End Year": 2025,
    Chassis: "XEAM",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "80000-89999",
    "Transponder Chip": "8A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14FBX (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Abrites",
    AKL: "Smart Pro / Abrites",
    Notes:
      "EV. Toyota bZ4X twin - more Toyota than Subaru. Uses Toyota HYQ14FBX smart key (315MHz), NOT Subaru HYQ14AKB. Code series 80000-89999 (Toyota). Smart Pro confirmed. Bypass cable required - plug directly into smart ECU.",
  },
  {
    Make: "Subaru",
    Model: "Tribeca (B9)",
    "Start Year": 2006,
    "End Year": 2007,
    Chassis: "WX",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62",
    "Cloneable?": "Yes",
    "FCC ID": "NHVWB1U711 (433MHz)",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "Originally marketed as B9 Tribeca 2006-2007. Dealer SSM can do AKL on these models.",
  },
  {
    Make: "Subaru",
    Model: "Tribeca",
    "Start Year": 2008,
    "End Year": 2011,
    Chassis: "WX",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWBU766 (433) 08-10 / CWTWB1U811 (315) 11",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "DA34 keyway entire Tribeca run. RHK changed 2011 to CWTWB1U811. Dealer SSM can AKL.",
  },
  {
    Make: "Subaru",
    Model: "Tribeca",
    "Start Year": 2012,
    "End Year": 2014,
    Chassis: "WX",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWB1U811 (315MHz)",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "DA34 keyway — Tribeca NEVER switched to DAT17. Last Tribeca produced Jan 2014, delivered Feb 2014. Per ILCO, Locksmith Keyless, PN 57497-XA20A.",
  },
  {
    Make: "Subaru",
    Model: "WRX",
    "Start Year": 2002,
    "End Year": 2004,
    Chassis: "GD",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "N/A",
    "Cloneable?": "N/A",
    "FCC ID": "N/A",
    "RKE Prog": "OBP",
    "Add Key": "N/A",
    AKL: "N/A",
    Notes: "Impreza WRX trim. No immobilizer. No remote.",
  },
  {
    Make: "Subaru",
    Model: "WRX",
    "Start Year": 2005,
    "End Year": 2007,
    Chassis: "GD",
    "Key Blank": "DA34",
    "Lishi Tool": "NSN14",
    "Code Series": "30001-37850",
    "Transponder Chip": "4D62",
    "Cloneable?": "Yes",
    "FCC ID": "NHVWB1U711 (433MHz)",
    "RKE Prog": "OBP / OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "Impreza WRX. Immo standard 2006+ WRX. RKE: OBP (2005) / OBP+Code (2006-07 w/ 8-digit code per cars101).",
  },
  {
    Make: "Subaru",
    Model: "WRX",
    "Start Year": 2008,
    "End Year": 2014,
    Chassis: "GE/GR",
    "Key Blank": "DAT17",
    "Lishi Tool": "DAT17",
    "Code Series": "T0001-T3000",
    "Transponder Chip": "4D62 pwFF",
    "Cloneable?": "Yes",
    "FCC ID": "CWTWB1U811",
    "RKE Prog": "OBP+Code",
    "Add Key": "All (clone or program)",
    AKL: "All (clone or program)",
    Notes:
      "Still officially Impreza WRX through 2014. Shared GE/GR chassis with STI. WRX stayed on DAT17 longer than other Impreza-chassis models. Dealer SSM can do AKL on these models.",
  },
  {
    Make: "Subaru",
    Model: "WRX (Keyed)",
    "Start Year": 2015,
    "End Year": 2021,
    Chassis: "VA",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "G (4D60 80-bit)",
    "Cloneable?": "No",
    "FCC ID": "CWTWB1U811 (315MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes:
      "WRX becomes own model on VA platform (no longer Impreza). G chip CWTWB1U811 through entire keyed WRX run 2015-2021. Never switched to H chip. 2019+ may require eeprom for AKL (confirmed on STI, likely same on WRX).",
  },
  {
    Make: "Subaru",
    Model: "WRX (Keyed)",
    "Start Year": 2022,
    "End Year": 2023,
    Chassis: "VB",
    "Key Blank": "B110",
    "Lishi Tool": "TOY43R",
    "Code Series": "32000-39999",
    "Transponder Chip": "H (8A/AES)",
    "Cloneable?": "No",
    "FCC ID": "CWTB1G077 (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes:
      "VB platform keyed WRX. H chip CWTB1G077. PN 57497-SJ050 / 57497-SJ051. AKL should be doable via OBD (unconfirmed in field).",
  },
  {
    Make: "Subaru",
    Model: "WRX (Smart Key)",
    "Start Year": 2019,
    "End Year": 2021,
    Chassis: "VA",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "H (8A)",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AHK (433MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Smart Pro / Autel / Abrites",
    AKL: "Smart Pro / Autel / Abrites",
    Notes: null,
  },
  {
    Make: "Subaru",
    Model: "WRX (Smart Key)",
    "Start Year": 2022,
    "End Year": 2025,
    Chassis: "VB",
    "Key Blank": "LXP90 thin",
    "Lishi Tool": "TOY 2 track 80k",
    "Code Series": "90000-94999",
    "Transponder Chip": "8A",
    "Cloneable?": "N/A",
    "FCC ID": "HYQ14AKB (434MHz)",
    "RKE Prog": "DIAG",
    "Add Key": "Abrites",
    AKL: "Abrites",
    Notes:
      "New VB platform. Smart key only (no more keyed ignition WRX). Newer FCC supersedes HYQ14AHK. Cross-compatible per AKS.",
  },
];
