export const VOLVO_DATA = [
  {
    Make: "Volvo",
    Model: "C40 Recharge",
    "Start Year": 2022,
    "End Year": 2025,
    Platform: "CMA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes: "CMA platform; all-electric; CEM only; Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "EX30",
    "Start Year": 2024,
    "End Year": 2025,
    Platform: "CMA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes: "All-electric; Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "EX40",
    "Start Year": 2025,
    "End Year": 2025,
    Platform: "CMA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes: "CMA platform; all-electric; Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "XC40",
    "Start Year": 2019,
    "End Year": 2025,
    Platform: "CMA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423 / YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes:
      "CMA platform; CEM only (no KVM); CMA platform; CEM only (no KVM); Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "XC40 Recharge",
    "Start Year": 2021,
    "End Year": 2024,
    Platform: "CMA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes: "CMA platform; all-electric; Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "S40 (NedCar)",
    "Start Year": 2000,
    "End Year": 2003,
    Platform: "NedCar (Mitsubishi)",
    "Key Type": "Transponder Key",
    "Immobilizer System": "Immobilizer Module",
    "Key Blade": "HU56",
    "Lishi Tool": "HU56",
    Transponder: "ID44",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "Under driver dash, above instrument cluster",
    "Programming System": "Dealer Only",
    "Code Series": "DH0001-DH4000",
    Notes: "NedCar/Mitsubishi platform; 2-track key; separate immo module",
  },
  {
    Make: "Volvo",
    Model: "V40 (NedCar)",
    "Start Year": 2000,
    "End Year": 2004,
    Platform: "NedCar (Mitsubishi)",
    "Key Type": "Transponder Key",
    "Immobilizer System": "Immobilizer Module",
    "Key Blade": "HU56",
    "Lishi Tool": "HU56",
    Transponder: "ID44",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "Under driver dash, above instrument cluster",
    "Programming System": "Dealer Only",
    "Code Series": "DH0001-DH4000",
    Notes: "NedCar/Mitsubishi platform; 2-track key; separate immo module",
  },
  {
    Make: "Volvo",
    Model: "C30",
    "Start Year": 2008,
    "End Year": 2013,
    Platform: "P1 (Ford C1)",
    "Key Type": "Fobik (Dash Socket)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency)",
    "Lishi Tool": "HU101",
    Transponder: "ID48",
    "FCC ID": "KR55WK49259",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "10001-11500",
    Notes: "P1 platform",
  },
  {
    Make: "Volvo",
    Model: "C70",
    "Start Year": 2006,
    "End Year": 2013,
    Platform: "P1 (Ford C1)",
    "Key Type": "Fobik (Dash Socket)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency)",
    "Lishi Tool": "HU101",
    Transponder: "ID48",
    "FCC ID": "KR55WK49259",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "10001-11500",
    Notes: "P1 platform; convertible",
  },
  {
    Make: "Volvo",
    Model: "S40",
    "Start Year": 2004,
    "End Year": 2011,
    Platform: "P1 (Ford C1)",
    "Key Type": "Fobik (Dash Socket)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency)",
    "Lishi Tool": "HU101",
    Transponder: "ID48",
    "FCC ID": "KR55WK49259",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "10001-11500",
    Notes:
      "P1 platform (mid-2004+); early 2004 = NedCar gen (HU56/ID44); P1 platform; plastic fobik inserts in dash",
  },
  {
    Make: "Volvo",
    Model: "V50",
    "Start Year": 2005,
    "End Year": 2011,
    Platform: "P1 (Ford C1)",
    "Key Type": "Fobik (Dash Socket)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency)",
    "Lishi Tool": "HU101",
    Transponder: "ID48",
    "FCC ID": "KR55WK49259",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "10001-11500",
    Notes: "P1 platform",
  },
  {
    Make: "Volvo",
    Model: "C70",
    "Start Year": 2001,
    "End Year": 2004,
    Platform: "P2",
    "Key Type": "Transponder Key",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "\u2014",
    "CEM Type": "Gen 1 (L-shaped)",
    "CEM Location": "Under dash, below wiper cowl",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "P2 platform; Early CEM",
  },
  {
    Make: "Volvo",
    Model: "S60",
    "Start Year": 2001,
    "End Year": 2002,
    Platform: "P2",
    "Key Type": "Transponder Key",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "\u2014",
    "CEM Type": "Gen 1 (L-shaped)",
    "CEM Location": "Under dash, below wiper cowl",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "Flip key w/remote available 2003+",
  },
  {
    Make: "Volvo",
    Model: "S60",
    "Start Year": 2003,
    "End Year": 2004,
    Platform: "P2",
    "Key Type": "Flip Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "LQNP2T-APU",
    "CEM Type": "Gen 1 (L-shaped)",
    "CEM Location": "Under dash, below wiper cowl",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "",
  },
  {
    Make: "Volvo",
    Model: "S60",
    "Start Year": 2005,
    "End Year": 2009,
    Platform: "P2",
    "Key Type": "Flip Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "LQNP2T-APU",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "Late P2 CEM",
  },
  {
    Make: "Volvo",
    Model: "S80",
    "Start Year": 1999,
    "End Year": 2004,
    Platform: "P2",
    "Key Type": "Transponder Key",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "LQNP2T-APU",
    "CEM Type": "Gen 1 (L-shaped)",
    "CEM Location": "Under dash, below wiper cowl",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "First Volvo CEM platform; Flip key w/remote available 2003+",
  },
  {
    Make: "Volvo",
    Model: "S80",
    "Start Year": 2005,
    "End Year": 2006,
    Platform: "P2",
    "Key Type": "Flip Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "LQNP2T-APU",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "Late P2 CEM; flip key standard",
  },
  {
    Make: "Volvo",
    Model: "V70",
    "Start Year": 2001,
    "End Year": 2002,
    Platform: "P2",
    "Key Type": "Transponder Key",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "\u2014",
    "CEM Type": "Gen 1 (L-shaped)",
    "CEM Location": "Under dash, below wiper cowl",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "P2 platform",
  },
  {
    Make: "Volvo",
    Model: "V70",
    "Start Year": 2003,
    "End Year": 2004,
    Platform: "P2",
    "Key Type": "Flip Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "LQNP2T-APU",
    "CEM Type": "Gen 1 (L-shaped)",
    "CEM Location": "Under dash, below wiper cowl",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "P2 platform",
  },
  {
    Make: "Volvo",
    Model: "V70",
    "Start Year": 2005,
    "End Year": 2007,
    Platform: "P2",
    "Key Type": "Flip Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "LQNP2T-APU",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "Late P2 CEM",
  },
  {
    Make: "Volvo",
    Model: "V70 XC",
    "Start Year": 2001,
    "End Year": 2002,
    Platform: "P2",
    "Key Type": "Transponder Key",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "\u2014",
    "CEM Type": "Gen 1 (L-shaped)",
    "CEM Location": "Under dash, below wiper cowl",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "P2 platform",
  },
  {
    Make: "Volvo",
    Model: "XC70",
    "Start Year": 2003,
    "End Year": 2004,
    Platform: "P2",
    "Key Type": "Flip Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "LQNP2T-APU",
    "CEM Type": "Gen 1 (L-shaped)",
    "CEM Location": "Under dash, below wiper cowl",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "P2 platform",
  },
  {
    Make: "Volvo",
    Model: "XC70",
    "Start Year": 2005,
    "End Year": 2007,
    Platform: "P2",
    "Key Type": "Flip Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "LQNP2T-APU",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "Late P2 CEM",
  },
  {
    Make: "Volvo",
    Model: "XC90",
    "Start Year": 2003,
    "End Year": 2004,
    Platform: "P2",
    "Key Type": "Flip Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "LQNP2T-APU",
    "CEM Type": "Gen 1 (L-shaped)",
    "CEM Location": "Under dash, below wiper cowl",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "P2 platform",
  },
  {
    Make: "Volvo",
    Model: "XC90",
    "Start Year": 2005,
    "End Year": 2014,
    Platform: "P2",
    "Key Type": "Flip Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "LQNP2T-APU",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "Late P2 CEM; last flip key Volvo",
  },
  {
    Make: "Volvo",
    Model: "S60",
    "Start Year": 2011,
    "End Year": 2018,
    Platform: "P3 (EUCD)",
    "Key Type": "Slot Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency)",
    "Lishi Tool": "HU101",
    Transponder: "ID48",
    "FCC ID": "KR55WK49264 / KR55WK49266",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "10001-11500",
    Notes: "P3 platform; P3 platform; keyless smart option available",
  },
  {
    Make: "Volvo",
    Model: "S80",
    "Start Year": 2007,
    "End Year": 2016,
    Platform: "P3 (EUCD)",
    "Key Type": "Slot Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency)",
    "Lishi Tool": "HU101",
    Transponder: "ID48",
    "FCC ID": "KR55WK49264 / KR55WK49266",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "10001-11500",
    Notes:
      "P3 platform; PCC (6-btn) or non-PCC (5-btn) versions; P3 platform; PCC (6-btn) or non-PCC (5-btn) versions; keyless smart option available",
  },
  {
    Make: "Volvo",
    Model: "V60",
    "Start Year": 2015,
    "End Year": 2018,
    Platform: "P3 (EUCD)",
    "Key Type": "Slot Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency)",
    "Lishi Tool": "HU101",
    Transponder: "ID48",
    "FCC ID": "KR55WK49264 / KR55WK49266",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "10001-11500",
    Notes: "P3 platform; keyless smart option available",
  },
  {
    Make: "Volvo",
    Model: "V70",
    "Start Year": 2008,
    "End Year": 2016,
    Platform: "P3 (EUCD)",
    "Key Type": "Slot Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency)",
    "Lishi Tool": "HU101",
    Transponder: "ID48",
    "FCC ID": "KR55WK49264 / KR55WK49266",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "10001-11500",
    Notes: "P3 platform; P3 platform; keyless smart option available",
  },
  {
    Make: "Volvo",
    Model: "XC60",
    "Start Year": 2010,
    "End Year": 2017,
    Platform: "P3 (EUCD)",
    "Key Type": "Slot Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency)",
    "Lishi Tool": "HU101",
    Transponder: "ID48",
    "FCC ID": "KR55WK49264 / KR55WK49266",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "10001-11500",
    Notes: "P3 platform; P3 platform; keyless smart option available",
  },
  {
    Make: "Volvo",
    Model: "XC70",
    "Start Year": 2008,
    "End Year": 2016,
    Platform: "P3 (EUCD)",
    "Key Type": "Slot Key w/Remote",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency)",
    "Lishi Tool": "HU101",
    Transponder: "ID48",
    "FCC ID": "KR55WK49264 / KR55WK49266",
    "CEM Type": "Gen 2 (White box)",
    "CEM Location": "Passenger side, behind glove box",
    "Programming System": "VIDA/Dealer",
    "Code Series": "10001-11500",
    Notes: "P3 platform; P3 platform; keyless smart option available",
  },
  {
    Make: "Volvo",
    Model: "850",
    "Start Year": 1993,
    "End Year": 1997,
    Platform: "P80",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1V0001-5V12295",
    Notes: "Some late 1997 may have transponder",
  },
  {
    Make: "Volvo",
    Model: "C70",
    "Start Year": 1998,
    "End Year": 1998,
    Platform: "P80",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1V0001-5V12295",
    Notes: "Some late 1998 have ID48 transponder",
  },
  {
    Make: "Volvo",
    Model: "C70",
    "Start Year": 1999,
    "End Year": 2000,
    Platform: "P80",
    "Key Type": "Transponder Key",
    "Immobilizer System": "Immobilizer Module",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "P80 platform; separate immo module",
  },
  {
    Make: "Volvo",
    Model: "S70",
    "Start Year": 1998,
    "End Year": 1998,
    Platform: "P80",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1V0001-5V12295",
    Notes: "Some late 1998 have ID48 transponder",
  },
  {
    Make: "Volvo",
    Model: "S70",
    "Start Year": 1999,
    "End Year": 2000,
    Platform: "P80",
    "Key Type": "Transponder Key",
    "Immobilizer System": "Immobilizer Module",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "Separate immobilizer module, not CEM",
  },
  {
    Make: "Volvo",
    Model: "S90",
    "Start Year": 1997,
    "End Year": 1998,
    Platform: "P80",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1V0001-5V12295",
    Notes: "",
  },
  {
    Make: "Volvo",
    Model: "V70",
    "Start Year": 1998,
    "End Year": 1998,
    Platform: "P80",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1V0001-5V12295",
    Notes: "Some late 1998 have ID48 transponder",
  },
  {
    Make: "Volvo",
    Model: "V70",
    "Start Year": 1999,
    "End Year": 2000,
    Platform: "P80",
    "Key Type": "Transponder Key",
    "Immobilizer System": "Immobilizer Module",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "ID48",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "VIDA/Dealer",
    "Code Series": "1V0001-5V12295",
    Notes: "P80 platform; separate immo module",
  },
  {
    Make: "Volvo",
    Model: "V90",
    "Start Year": 1997,
    "End Year": 1998,
    Platform: "P80",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE66",
    "Lishi Tool": "NE66",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1V0001-5V12295",
    Notes: "",
  },
  {
    Make: "Volvo",
    Model: "240",
    "Start Year": 1985,
    "End Year": 1993,
    Platform: "RWD (Pre-platform)",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE34",
    "Lishi Tool": "\u2014",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1A000-5A745",
    Notes: "",
  },
  {
    Make: "Volvo",
    Model: "740",
    "Start Year": 1985,
    "End Year": 1992,
    Platform: "RWD (Pre-platform)",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE34",
    "Lishi Tool": "\u2014",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1A000-5A745",
    Notes: "",
  },
  {
    Make: "Volvo",
    Model: "760",
    "Start Year": 1985,
    "End Year": 1990,
    Platform: "RWD (Pre-platform)",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE34",
    "Lishi Tool": "\u2014",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1V0001-5V12295",
    Notes: "",
  },
  {
    Make: "Volvo",
    Model: "780",
    "Start Year": 1986,
    "End Year": 1991,
    Platform: "RWD (Pre-platform)",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE34",
    "Lishi Tool": "\u2014",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1V0001-5V12295",
    Notes: "",
  },
  {
    Make: "Volvo",
    Model: "940",
    "Start Year": 1991,
    "End Year": 1995,
    Platform: "RWD 900-series",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE34",
    "Lishi Tool": "\u2014",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1V0001-5V12295",
    Notes: "",
  },
  {
    Make: "Volvo",
    Model: "960",
    "Start Year": 1992,
    "End Year": 1997,
    Platform: "RWD 900-series",
    "Key Type": "Metal Key",
    "Immobilizer System": "No Immobilizer",
    "Key Blade": "NE34",
    "Lishi Tool": "\u2014",
    Transponder: "\u2014",
    "FCC ID": "\u2014",
    "CEM Type": "\u2014",
    "CEM Location": "\u2014",
    "Programming System": "\u2014",
    "Code Series": "1V0001-5V12295",
    Notes: "",
  },
  {
    Make: "Volvo",
    Model: "S60",
    "Start Year": 2019,
    "End Year": 2025,
    Platform: "SPA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423 / YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes:
      "SPA platform; CEM + KVM; SPA platform; CEM + KVM; Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "S90",
    "Start Year": 2017,
    "End Year": 2025,
    Platform: "SPA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423 / YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes:
      "SPA platform; CEM + KVM; SPA platform; CEM + KVM; Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "V60 / V60 CC",
    "Start Year": 2019,
    "End Year": 2025,
    Platform: "SPA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423 / YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes:
      "SPA platform; CEM + KVM; SPA platform; CEM + KVM; Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "V90 / V90 CC",
    "Start Year": 2017,
    "End Year": 2025,
    Platform: "SPA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423 / YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes:
      "SPA platform; CEM + KVM; SPA platform; CEM + KVM; Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "XC60",
    "Start Year": 2018,
    "End Year": 2025,
    Platform: "SPA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423 / YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes:
      "SPA platform; CEM + KVM; SPA platform; CEM + KVM; Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "XC90",
    "Start Year": 2016,
    "End Year": 2025,
    Platform: "SPA",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423 / YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes:
      "SPA platform; CEM + KVM; SPA platform; CEM + KVM; PIN code programming available via 3rd party; SPA platform; CEM + KVM; PIN code programming available via 3rd party; Motion Sensing key",
  },
  {
    Make: "Volvo",
    Model: "EX90",
    "Start Year": 2024,
    "End Year": 2025,
    Platform: "SPA2",
    "Key Type": "Smart Key (Full Smart)",
    "Immobilizer System": "CEM",
    "Key Blade": "HU101 (emergency, 8-cut)",
    "Lishi Tool": "HU101",
    Transponder: "ID49",
    "FCC ID": "YGOHUF8423MS",
    "CEM Type": "Gen 3 (Small box)",
    "CEM Location": "Driver side dash",
    "Programming System": "VIDA/Dealer / PIN code",
    "Code Series": "1-4000 / 8001-81500",
    Notes: "SPA2 platform; all-electric; Motion Sensing key",
  },
];
