export const VW_DATA = [
  {
    Make: "Volkswagen",
    Model: "Arteon",
    "Chassis Platform": "MQB (3H)",
    "Start Year": 2019,
    "End Year": 2019,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU162T (OEM)",
    "Code Series": "",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Arteon",
    "Chassis Platform": "MQB (3H)",
    "Start Year": 2020,
    "End Year": 2023,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU162T (OEM)",
    "Code Series": "",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Atlas",
    "Chassis Platform": "MQB (CA1)",
    "Start Year": 2018,
    "End Year": 2019,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Atlas",
    "Chassis Platform": "MQB (CA1)",
    "Start Year": 2020,
    "End Year": 2020,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Atlas",
    "Chassis Platform": "MQB (CA1)",
    "Start Year": 2021,
    "End Year": 2025,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU162T (OEM)",
    "Code Series": "",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Atlas Cross Sport",
    "Chassis Platform": "MQB (CA1)",
    "Start Year": 2020,
    "End Year": 2020,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU162T (OEM)",
    "Code Series": "0001-6000",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Atlas Cross Sport",
    "Chassis Platform": "MQB (CA1)",
    "Start Year": 2021,
    "End Year": 2025,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU162T (OEM)",
    "Code Series": "",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Beetle",
    "Chassis Platform": "A4 (1C)",
    "Start Year": 1998,
    "End Year": 1999,
    "Immobilizer Type": "",
    "Key Blank": "HU66-P",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Beetle",
    "Chassis Platform": "A4 (1C)",
    "Start Year": 2000,
    "End Year": 2001,
    "Immobilizer Type": "Immo 2",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Beetle",
    "Chassis Platform": "A4 (1C)",
    "Start Year": 2002,
    "End Year": 2005,
    "Immobilizer Type": "Immo 3",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Beetle",
    "Chassis Platform": "A5 (1C)",
    "Start Year": 2006,
    "End Year": 2010,
    "Immobilizer Type": "Immo 3",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Beetle",
    "Chassis Platform": "A5 (5C)",
    "Start Year": 2012,
    "End Year": 2016,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Beetle",
    "Chassis Platform": "A5 (5C)",
    "Start Year": 2017,
    "End Year": 2019,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Cabrio / Cabriolet",
    "Chassis Platform": "A1 (Typ 17)",
    "Start Year": 1985,
    "End Year": 1987,
    "Immobilizer Type": "",
    "Key Blank": "X88 / PA8",
    "Code Series": "HV1-HV9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Cabrio / Cabriolet",
    "Chassis Platform": "A1 (Typ 17)",
    "Start Year": 1988,
    "End Year": 1993,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Cabrio / Cabriolet",
    "Chassis Platform": "A3 (Typ 1E)",
    "Start Year": 1994,
    "End Year": 1997,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Cabrio / Cabriolet",
    "Chassis Platform": "A3 (Typ 1E)",
    "Start Year": 1998,
    "End Year": 1998,
    "Immobilizer Type": "",
    "Key Blank": "HU66-P",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Cabrio / Cabriolet",
    "Chassis Platform": "A3 (Typ 1E)",
    "Start Year": 1999,
    "End Year": 1999,
    "Immobilizer Type": "",
    "Key Blank": "HU66-P",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Cabrio / Cabriolet",
    "Chassis Platform": "A3 (Typ 1E)",
    "Start Year": 2000,
    "End Year": 2002,
    "Immobilizer Type": "Immo 2",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "CC",
    "Chassis Platform": "B6 (Typ 3C)",
    "Start Year": 2009,
    "End Year": 2017,
    "Immobilizer Type": "Immo 4 (Comfort Module)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Corrado",
    "Chassis Platform": "A2 (Typ 53i)",
    "Start Year": 1990,
    "End Year": 1994,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Eos",
    "Chassis Platform": "A5 (1F)",
    "Start Year": 2007,
    "End Year": 2008,
    "Immobilizer Type": "Immo 4 (Micronas)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Eos",
    "Chassis Platform": "A5 (1F)",
    "Start Year": 2009,
    "End Year": 2015,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Eurovan",
    "Chassis Platform": "T4 (Typ 70)",
    "Start Year": 1993,
    "End Year": 1997,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Eurovan",
    "Chassis Platform": "T4 (Typ 70)",
    "Start Year": 1998,
    "End Year": 1999,
    "Immobilizer Type": "",
    "Key Blank": "HU66-P",
    "Code Series": "0001-6000",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Eurovan",
    "Chassis Platform": "T4 (Typ 70)",
    "Start Year": 2000,
    "End Year": 2003,
    "Immobilizer Type": "Immo 2",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Fox",
    "Chassis Platform": "A1 (Typ 33)",
    "Start Year": 1987,
    "End Year": 1992,
    "Immobilizer Type": "",
    "Key Blank": "X88 / PA8",
    "Code Series": "HV1-HV9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Fox",
    "Chassis Platform": "A1 (Typ 33)",
    "Start Year": 1993,
    "End Year": 1993,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "A1 (Mk1)",
    "Start Year": 1985,
    "End Year": 1987,
    "Immobilizer Type": "",
    "Key Blank": "X88 / PA8",
    "Code Series": "HV1-HV9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "A2 (Mk2)",
    "Start Year": 1988,
    "End Year": 1992,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "A3 (Mk3)",
    "Start Year": 1993,
    "End Year": 1998,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 1999,
    "End Year": 1999,
    "Immobilizer Type": "",
    "Key Blank": "HU66-P",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 2000,
    "End Year": 2001,
    "Immobilizer Type": "Immo 2",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 2002,
    "End Year": 2005,
    "Immobilizer Type": "Immo 3",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "A5 (Mk5)",
    "Start Year": 2006,
    "End Year": 2006,
    "Immobilizer Type": "Immo 4 (Micronas)",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "A5 (Mk5)",
    "Start Year": 2007,
    "End Year": 2008,
    "Immobilizer Type": "Immo 4 (Micronas)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "A5/A6 (Mk5/Mk6)",
    "Start Year": 2009,
    "End Year": 2014,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2015,
    "End Year": 2016,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2017,
    "End Year": 2021,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf Alltrack",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2017,
    "End Year": 2019,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf R",
    "Chassis Platform": "A5 (Mk6)",
    "Start Year": 2012,
    "End Year": 2014,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf R",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2015,
    "End Year": 2021,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf R",
    "Chassis Platform": "MQB (Mk7.5/Mk8)",
    "Start Year": 2022,
    "End Year": 2023,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Golf SportWagen",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2015,
    "End Year": 2019,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "GTI",
    "Chassis Platform": "A1 (Mk1)",
    "Start Year": 1985,
    "End Year": 1987,
    "Immobilizer Type": "",
    "Key Blank": "X88 / PA8",
    "Code Series": "HV1-HV9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "GTI",
    "Chassis Platform": "A2 (Mk2)",
    "Start Year": 1988,
    "End Year": 1992,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "GTI",
    "Chassis Platform": "A3 (Mk3)",
    "Start Year": 1993,
    "End Year": 1998,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "GTI",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 1999,
    "End Year": 1999,
    "Immobilizer Type": "",
    "Key Blank": "HU66-P",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "GTI",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 2000,
    "End Year": 2001,
    "Immobilizer Type": "Immo 2",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "GTI",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 2002,
    "End Year": 2005,
    "Immobilizer Type": "Immo 3",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "GTI",
    "Chassis Platform": "A5 (Mk5)",
    "Start Year": 2006,
    "End Year": 2008,
    "Immobilizer Type": "Immo 4 (Micronas)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "GTI",
    "Chassis Platform": "A5/A6 (Mk5/Mk6)",
    "Start Year": 2009,
    "End Year": 2014,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "GTI",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2015,
    "End Year": 2021,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "GTI",
    "Chassis Platform": "MQB (Mk8)",
    "Start Year": 2022,
    "End Year": 2025,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "ID.4",
    "Chassis Platform": "MEB",
    "Start Year": 2021,
    "End Year": 2025,
    "Immobilizer Type": "MEB (EV)",
    "Key Blank": "",
    "Code Series": "",
    Lishi: "",
  },
  {
    Make: "Volkswagen",
    Model: "ID.Buzz",
    "Chassis Platform": "MEB",
    "Start Year": 2024,
    "End Year": 2025,
    "Immobilizer Type": "MEB (EV)",
    "Key Blank": "",
    "Code Series": "",
    Lishi: "",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "A1 (Mk1)",
    "Start Year": 1985,
    "End Year": 1987,
    "Immobilizer Type": "",
    "Key Blank": "X88 / PA8",
    "Code Series": "HV1-HV9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "A2 (Mk2)",
    "Start Year": 1988,
    "End Year": 1992,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "A3 (Mk3)",
    "Start Year": 1993,
    "End Year": 1998,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 1999,
    "End Year": 1999,
    "Immobilizer Type": "",
    "Key Blank": "HU66-P",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 2000,
    "End Year": 2001,
    "Immobilizer Type": "Immo 2",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 2002,
    "End Year": 2005,
    "Immobilizer Type": "Immo 3",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "A5 (Mk5)",
    "Start Year": 2006,
    "End Year": 2008,
    "Immobilizer Type": "Immo 4 (Micronas)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "A5/A6 (Mk5/Mk6)",
    "Start Year": 2009,
    "End Year": 2016,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "A6 (Mk6)",
    "Start Year": 2017,
    "End Year": 2018,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2019,
    "End Year": 2019,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU162T (OEM)",
    "Code Series": "",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2020,
    "End Year": 2025,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU162T (OEM)",
    "Code Series": "",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "A1 (Mk1)",
    "Start Year": 1985,
    "End Year": 1987,
    "Immobilizer Type": "",
    "Key Blank": "X88 / PA8",
    "Code Series": "HV1-HV9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "A2 (Mk2)",
    "Start Year": 1988,
    "End Year": 1992,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "A3 (Mk3)",
    "Start Year": 1993,
    "End Year": 1998,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 1999,
    "End Year": 1999,
    "Immobilizer Type": "",
    "Key Blank": "HU66-P",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 2000,
    "End Year": 2001,
    "Immobilizer Type": "Immo 2",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 2002,
    "End Year": 2005,
    "Immobilizer Type": "Immo 3",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "A5 (Mk5)",
    "Start Year": 2006,
    "End Year": 2008,
    "Immobilizer Type": "Immo 4 (Micronas)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "A5/A6 (Mk5/Mk6)",
    "Start Year": 2009,
    "End Year": 2016,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "A6 (Mk6)",
    "Start Year": 2017,
    "End Year": 2018,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2019,
    "End Year": 2019,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2020,
    "End Year": 2020,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Jetta GLI",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2021,
    "End Year": 2025,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU162T (OEM)",
    "Code Series": "",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Passat",
    "Chassis Platform": "B3 (Typ 35i)",
    "Start Year": 1990,
    "End Year": 1994,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Passat",
    "Chassis Platform": "B4 (Typ 3A)",
    "Start Year": 1995,
    "End Year": 1997,
    "Immobilizer Type": "",
    "Key Blank": "X203 / V37",
    "Code Series": "AH1-AH9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Passat",
    "Chassis Platform": "B5 (Typ 3B)",
    "Start Year": 1998,
    "End Year": 1998,
    "Immobilizer Type": "",
    "Key Blank": "HU66-P",
    "Code Series": "AH1-AH9282",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Passat",
    "Chassis Platform": "B5 (Typ 3B)",
    "Start Year": 1999,
    "End Year": 1999,
    "Immobilizer Type": "",
    "Key Blank": "HU66-P",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Passat",
    "Chassis Platform": "B5 (Typ 3B)",
    "Start Year": 2000,
    "End Year": 2001,
    "Immobilizer Type": "Immo 2",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Passat",
    "Chassis Platform": "B5.5 (Typ 3BG)",
    "Start Year": 2002,
    "End Year": 2005,
    "Immobilizer Type": "Immo 3",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Passat",
    "Chassis Platform": "B6 (Typ 3C)",
    "Start Year": 2006,
    "End Year": 2011,
    "Immobilizer Type": "Immo 4 (Comfort Module)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Passat",
    "Chassis Platform": "NMS (Typ 3C/A32)",
    "Start Year": 2012,
    "End Year": 2019,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Passat",
    "Chassis Platform": "NMS (Typ 3C/A32)",
    "Start Year": 2020,
    "End Year": 2022,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Phaeton",
    "Chassis Platform": "D1 (Typ 3D)",
    "Start Year": 2004,
    "End Year": 2006,
    "Immobilizer Type": "Immo 3",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Quantum",
    "Chassis Platform": "B2 (Typ 32B)",
    "Start Year": 1985,
    "End Year": 1988,
    "Immobilizer Type": "",
    "Key Blank": "X88 / PA8",
    "Code Series": "HV1-HV9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "R32",
    "Chassis Platform": "A4 (Mk4)",
    "Start Year": 2004,
    "End Year": 2004,
    "Immobilizer Type": "Immo 3",
    "Key Blank": "HU66T6",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "R32",
    "Chassis Platform": "A5 (Mk5)",
    "Start Year": 2008,
    "End Year": 2008,
    "Immobilizer Type": "Immo 4 (Micronas)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Rabbit (Mk1)",
    "Chassis Platform": "A1 (Typ 17)",
    "Start Year": 1985,
    "End Year": 1986,
    "Immobilizer Type": "",
    "Key Blank": "X88 / PA8",
    "Code Series": "HV1-HV9282",
    Lishi: "",
  },
  {
    Make: "Volkswagen",
    Model: "Rabbit",
    "Chassis Platform": "A5 (Mk5)",
    "Start Year": 2006,
    "End Year": 2008,
    "Immobilizer Type": "Immo 4 (Micronas)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Rabbit",
    "Chassis Platform": "A5 (Mk5)",
    "Start Year": 2009,
    "End Year": 2009,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Routan",
    "Chassis Platform": "RT (Chrysler RT)",
    "Start Year": 2009,
    "End Year": 2014,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "Y170-PT",
    "Code Series": "M1-M2618",
    Lishi: "CY24",
  },
  {
    Make: "Volkswagen",
    Model: "Scirocco",
    "Chassis Platform": "A1 (Typ 53)",
    "Start Year": 1985,
    "End Year": 1988,
    "Immobilizer Type": "",
    "Key Blank": "X88 / PA8",
    "Code Series": "HV1-HV9282",
    Lishi: "HU49",
  },
  {
    Make: "Volkswagen",
    Model: "Taos",
    "Chassis Platform": "MQB (BW2)",
    "Start Year": 2022,
    "End Year": 2025,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU162T (OEM)",
    "Code Series": "",
    Lishi: "HU162T",
  },
  {
    Make: "Volkswagen",
    Model: "Tiguan",
    "Chassis Platform": "A5 (5N)",
    "Start Year": 2009,
    "End Year": 2016,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66T24",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Tiguan",
    "Chassis Platform": "A5 (5N)",
    "Start Year": 2017,
    "End Year": 2017,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Tiguan",
    "Chassis Platform": "MQB (AD1)",
    "Start Year": 2018,
    "End Year": 2019,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Tiguan",
    "Chassis Platform": "MQB (AD1)",
    "Start Year": 2020,
    "End Year": 2025,
    "Immobilizer Type": "MQB49",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Touareg",
    "Chassis Platform": "7L (Typ 7L)",
    "Start Year": 2004,
    "End Year": 2005,
    "Immobilizer Type": "Immo 3",
    "Key Blank": "HU66 (Dealer FOB)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Touareg",
    "Chassis Platform": "7L (Typ 7L)",
    "Start Year": 2006,
    "End Year": 2008,
    "Immobilizer Type": "Immo 4 (Micronas)",
    "Key Blank": "HU66 (Dealer FOB)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Touareg",
    "Chassis Platform": "7P (Typ 7P)",
    "Start Year": 2009,
    "End Year": 2016,
    "Immobilizer Type": "Immo 4 (UDS/NEC)",
    "Key Blank": "HU66 (Dealer FOB)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
  {
    Make: "Volkswagen",
    Model: "Vanagon",
    "Chassis Platform": "T3 (Typ 25)",
    "Start Year": 1985,
    "End Year": 1991,
    "Immobilizer Type": "",
    "Key Blank": "X110 / V33",
    "Code Series": "N1-N9282",
    Lishi: "",
  },
  {
    Make: "Volkswagen",
    Model: "e-Golf",
    "Chassis Platform": "MQB (Mk7)",
    "Start Year": 2015,
    "End Year": 2020,
    "Immobilizer Type": "MQB48",
    "Key Blank": "HU66 (OEM Remote)",
    "Code Series": "0001-6000",
    Lishi: "HU66",
  },
];
